In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import random
from pathlib import Path
import sys
import json


from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from tqdm import tqdm
from torch.optim import AdamW
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import f1_score, classification_report

import torch.nn as nn
import torch

d:\Python\Learning\NLP_Classification\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
project_root = Path().resolve().parent

# добавляем в sys.path
sys.path.append(str(project_root))

from core.graf import *
from core.func import *
from core.nn_models import *

In [4]:
# ── Конфиг ──────────────────────────────────────────────────────────────────
DATA_PATH           = '../data/News_Category_Dataset_v3.json'
MODEL_NAME          = 'roberta-base' # 'cointegrated/rubert-tiny2'
MODEL_DIR           = f'models/{MODEL_NAME.split("/")[-1]}' 
SAVE_PATH           = f'news_classifier_{MODEL_NAME.split("/")[-1]}'
MAX_LEN             = 500
BATCH_SIZE          = 32
EPOCHS              = 100
ACCUM_STEPS         = 4
WARMUP_FRAC         = 0.1
LR                  = 2e-5
SEED                = 42
DEVICE              = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if torch.cuda.is_available():
    print("GPU: ", torch.cuda.get_device_name())
    print("VRAM:", round(torch.cuda.get_device_properties().total_memory / 1e9, 1),  'Gb')

random.seed(SEED)
torch.manual_seed(SEED)
np.random.seed(SEED)

GPU:  NVIDIA GeForce RTX 5070
VRAM: 12.8 Gb

In [5]:
with open(DATA_PATH, 'r') as file:
    data = pd.DataFrame([json.loads(line) for line in file])

data.sample(5)

,link,headline,category,short_description,authors,date
128310,https://www.huffingtonpost.com/entry/what-if-w...,What If We Were All Family Generation Changers?,IMPACT,"What if, in doing so, we won't just create new...","Matt Murrie, ContributorEdupreneur, Cofounder/...",2014-06-20
139983,https://www.huffingtonpost.comhttp://www.washi...,Firestorm At AOL Over Employee Benefit Cuts,BUSINESS,It should have been a glorious week for AOL ch...,,2014-02-08
42339,https://www.huffingtonpost.com/entry/time-runs...,Dakota Access Protesters Arrested As Deadline ...,POLITICS,A few protesters who refused to leave remained...,"Michael McLaughlin & Josh Morgan, The Huffingt...",2017-02-22
131494,https://www.huffingtonpost.com/entry/one-glimp...,One Glimpse Of These Baby Kit Foxes And You'll...,GREEN,,,2014-05-14
163649,https://www.huffingtonpost.com/entry/mens-swea...,"Mens' Sweat Pheromone, Androstadienone, Influe...",SCIENCE,Scientists didn't know if humans played that g...,Melissa Cronin,2013-06-02

In [6]:
preprocesed_data = data.copy()
preprocesed_data.drop_duplicates(inplace=True)
preprocesed_data["headline"] = preprocesed_data["headline"].str.replace("’", "'")
preprocesed_data["short_description"] = preprocesed_data["short_description"].str.replace("’", "'")
preprocesed_data["input_text"] = preprocesed_data["headline"] + " [SEP] " + preprocesed_data["authors"] + " [SEP] " + preprocesed_data["short_description"]
y = preprocesed_data[["category"]]
X = preprocesed_data["input_text"]

In [7]:
train_X, val_X, train_y, val_y = train_test_split(X, y, test_size=0.4, random_state=SEED, shuffle=True, stratify=y)
val_X, test_X, val_y, test_y = train_test_split(val_X, val_y, test_size=0.5, random_state=SEED, shuffle=True, stratify=val_y)

In [8]:
# ── Dataset с претокенизацией ─────────────────────────────────────────────────
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
le = OneHotEncoder() # LabelEncoder()

def batch_tokenization(tokenizer, texts, desc: str = "Токенизация", batch_size: int = 5000):
    all_ids, all_masks = [], []
    for i in tqdm(range(0, len(texts), batch_size), desc=desc):
        tokens = tokenizer(
            texts[i : i+batch_size],
            max_length=MAX_LEN,
            padding="max_length",
            truncation=True,
            return_tensors='pt'
        )
        all_ids.append(tokens["input_ids"])
        all_masks.append(tokens["attention_mask"])
    return torch.cat(all_ids), torch.cat(all_masks)

In [9]:
train_ids, train_masks = batch_tokenization(tokenizer=tokenizer, texts=train_X.to_list())
train_labels = le.fit_transform(train_y).toarray()
train_labels

Токенизация: 100%|██████████| 26/26 [00:19<00:00,  1.31it/s]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(125708, 42))

In [10]:
counts = train_labels.sum(axis=0)

pos_weight = torch.tensor([(len(train_labels) - c) / c for c in counts], dtype=torch.float).to(DEVICE)
print('pos_weight:', pos_weight)

pos_weight: tensor([137.9039, 155.5479,  44.7120,  33.9675, 182.2478,  37.7988,  57.8245,
        193.8961,  60.1420, 205.4171,  11.0676, 144.1593, 148.4744,  32.0463,
        148.8307,  78.9161,  30.3018,  47.4985,  59.1474, 184.4100,  70.1823,
        118.2676,  22.8309,  51.9743,   4.8849,  32.0116,  80.3118,  93.9456,
         40.2699,  91.9793,  20.3535,  98.9269,  98.7683,  56.1920,  20.1630,
        151.1889,  56.3485,  74.4550,  10.6775,  57.6598,  62.5210,  80.2592],
       device='cuda:0')

In [11]:
train_ds = TextDataset(train_ids, train_masks, train_labels)
train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True)

In [12]:
val_ids, val_masks = batch_tokenization(tokenizer=tokenizer, texts=val_X.to_list())
val_labels = le.transform(val_y).toarray()

val_ds = TextDataset(val_ids, val_masks, val_labels)
val_dl = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True)

Токенизация: 100%|██████████| 9/9 [00:06<00:00,  1.38it/s]

In [13]:
lstm_model = LSTM_Classifier(num_classes=len(le.categories_[0]),
                             vocab_size=len(tokenizer.get_vocab()),
                             embedding_dim=256,
                             lstm_units=64,
                             num_layers=1,
                             )

In [14]:
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = AdamW(lstm_model.parameters(), lr=0.001, weight_decay=0.01)
lstm_model.to(DEVICE)

training(
    model=lstm_model,
    train_data_loader=train_dl,
    val_data_loader=val_dl,
    optimizer=optimizer,
    epoches=EPOCHS,
    criterion=criterion,
    tokenizator=le,
    accum_steps=ACCUM_STEPS,
    warmup_frac=WARMUP_FRAC,
    device=DEVICE,
    save_path="LSTM_news_classifier"
    )

Epoch 1/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.45it/s, loss=1.2954]

Epoch 1 | train_loss=1.3412 | val_loss=1.2733 | val_f1_mean=0.0674 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.044008,0.022593,0.052099,0.069984,0.015234,0.079956,0.050371,0.017359,0.047717,0.016813,...,0.020933,0.046334,0.152488,0.023916,0.055073,0.050867,0.263282,0.035561,0.04205,0.089702

  → Сохранена лучшая модель (mean F1=0.0674)

Epoch 2/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.50it/s, loss=1.1078]

Epoch 2 | train_loss=1.1807 | val_loss=1.0987 | val_f1_mean=0.0856 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.040418,0.03126,0.057155,0.073507,0.018472,0.094992,0.059501,0.018408,0.071966,0.028433,...,0.029623,0.073396,0.16859,0.04399,0.082358,0.061673,0.309945,0.041618,0.077559,0.073479

  → Сохранена лучшая модель (mean F1=0.0856)

Epoch 3/100: 100%|██████████| 3929/3929 [00:27<00:00, 145.36it/s, loss=0.8457]

Epoch 3 | train_loss=0.9885 | val_loss=0.9041 | val_f1_mean=0.1122 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.061062,0.042745,0.069192,0.112165,0.033279,0.132052,0.079138,0.026321,0.092691,0.052854,...,0.032117,0.117865,0.181542,0.053174,0.097437,0.075244,0.407396,0.067963,0.114982,0.115283

  → Сохранена лучшая модель (mean F1=0.1122)

Epoch 4/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.65it/s, loss=0.8189]

Epoch 4 | train_loss=0.8435 | val_loss=0.7888 | val_f1_mean=0.1320 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.06903,0.077081,0.080819,0.126655,0.039314,0.153773,0.093516,0.029515,0.10211,0.052456,...,0.054922,0.134445,0.197123,0.066964,0.104288,0.091316,0.466736,0.099059,0.134009,0.135938

  → Сохранена лучшая модель (mean F1=0.1320)

Epoch 5/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.21it/s, loss=0.5882]

Epoch 5 | train_loss=0.7259 | val_loss=0.7108 | val_f1_mean=0.1495 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.091267,0.06377,0.099962,0.150054,0.041939,0.179029,0.108776,0.048647,0.116221,0.055638,...,0.065202,0.137352,0.206464,0.07064,0.119124,0.114082,0.479314,0.104776,0.130595,0.179235

  → Сохранена лучшая модель (mean F1=0.1495)

Epoch 6/100: 100%|██████████| 3929/3929 [00:26<00:00, 146.55it/s, loss=0.4535]

Epoch 6 | train_loss=0.6320 | val_loss=0.6526 | val_f1_mean=0.1702 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.07888,0.082057,0.141077,0.173761,0.041636,0.168447,0.149341,0.064085,0.151274,0.062458,...,0.089772,0.190065,0.239827,0.096028,0.144343,0.133067,0.512862,0.115541,0.19623,0.193739

  → Сохранена лучшая модель (mean F1=0.1702)

Epoch 7/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.61it/s, loss=0.7710]

Epoch 7 | train_loss=0.5546 | val_loss=0.6124 | val_f1_mean=0.1910 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.113489,0.099159,0.137705,0.193675,0.056441,0.216948,0.143731,0.084837,0.154605,0.072464,...,0.120007,0.185359,0.274326,0.09533,0.176556,0.161636,0.522865,0.128017,0.181682,0.20782

  → Сохранена лучшая модель (mean F1=0.1910)

Epoch 8/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.71it/s, loss=0.3554]

Epoch 8 | train_loss=0.4874 | val_loss=0.5837 | val_f1_mean=0.2105 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.114075,0.112571,0.152802,0.192235,0.055445,0.241732,0.140744,0.105513,0.256768,0.081005,...,0.101119,0.197315,0.342416,0.096806,0.249136,0.188208,0.55572,0.131242,0.188778,0.224663

  → Сохранена лучшая модель (mean F1=0.2105)

Epoch 9/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.24it/s, loss=0.2108]

Epoch 9 | train_loss=0.4278 | val_loss=0.5695 | val_f1_mean=0.2417 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.202328,0.16834,0.19095,0.226495,0.079259,0.277095,0.183007,0.126996,0.243416,0.09736,...,0.138177,0.262179,0.399171,0.117327,0.278982,0.213658,0.530869,0.162527,0.241986,0.238388

  → Сохранена лучшая модель (mean F1=0.2417)

Epoch 10/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.42it/s, loss=0.2257]

Epoch 10 | train_loss=0.3745 | val_loss=0.5600 | val_f1_mean=0.2533 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.170498,0.146515,0.187805,0.234524,0.108058,0.290921,0.1819,0.163823,0.283766,0.118323,...,0.140052,0.236582,0.458701,0.143903,0.327381,0.20669,0.604481,0.161531,0.233063,0.265087

  → Сохранена лучшая модель (mean F1=0.2533)

Epoch 11/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.66it/s, loss=0.2223]

Epoch 11 | train_loss=0.3273 | val_loss=0.5631 | val_f1_mean=0.2710 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.212801,0.139041,0.191285,0.246854,0.139785,0.297586,0.228514,0.152672,0.31213,0.123536,...,0.146261,0.264486,0.452287,0.12354,0.283536,0.209469,0.648615,0.165375,0.251999,0.291865

  → Сохранена лучшая модель (mean F1=0.2710)

Epoch 12/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.65it/s, loss=0.5305]

Epoch 12 | train_loss=0.2823 | val_loss=0.5833 | val_f1_mean=0.2996 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.22475,0.139898,0.212681,0.26787,0.170065,0.291062,0.267633,0.2,0.372537,0.137495,...,0.195906,0.273649,0.568083,0.173878,0.413555,0.244995,0.656753,0.165398,0.245056,0.286493

  → Сохранена лучшая модель (mean F1=0.2996)

Epoch 13/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.49it/s, loss=0.2755]

Epoch 13 | train_loss=0.2479 | val_loss=0.6171 | val_f1_mean=0.3282 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.27234,0.192357,0.255843,0.260846,0.121273,0.329011,0.266355,0.25082,0.44153,0.17427,...,0.265132,0.28747,0.514846,0.179476,0.4679,0.249525,0.651263,0.225639,0.261501,0.306478

  → Сохранена лучшая модель (mean F1=0.3282)

Epoch 14/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.28it/s, loss=0.1191]

Epoch 14 | train_loss=0.2176 | val_loss=0.6294 | val_f1_mean=0.3364 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.293413,0.25818,0.22413,0.300773,0.160557,0.332664,0.242188,0.279288,0.441767,0.191657,...,0.207171,0.33667,0.603108,0.19447,0.410065,0.243864,0.688584,0.213908,0.278894,0.350836

  → Сохранена лучшая модель (mean F1=0.3364)

Epoch 15/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.58it/s, loss=0.2301]

Epoch 15 | train_loss=0.1938 | val_loss=0.6631 | val_f1_mean=0.3639 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.287778,0.304721,0.266569,0.309663,0.205128,0.365453,0.291012,0.248614,0.45592,0.211669,...,0.254688,0.38402,0.591193,0.172601,0.484647,0.27746,0.719187,0.220249,0.331446,0.369448

  → Сохранена лучшая модель (mean F1=0.3639)

Epoch 16/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.34it/s, loss=0.1338]

Epoch 16 | train_loss=0.1724 | val_loss=0.7542 | val_f1_mean=0.3866 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.383264,0.340114,0.320492,0.356436,0.241569,0.362751,0.327186,0.320175,0.377593,0.242138,...,0.288081,0.368819,0.648964,0.208871,0.430968,0.286814,0.713306,0.244248,0.340439,0.391421

  → Сохранена лучшая модель (mean F1=0.3866)

Epoch 17/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.05it/s, loss=0.1270]

Epoch 17 | train_loss=0.1560 | val_loss=0.7801 | val_f1_mean=0.4058 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.360902,0.388406,0.297427,0.325074,0.264493,0.368134,0.304432,0.370968,0.518966,0.24979,...,0.305151,0.398039,0.672971,0.231693,0.506613,0.291555,0.73932,0.267342,0.33775,0.396606

  → Сохранена лучшая модель (mean F1=0.4058)

Epoch 18/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.81it/s, loss=0.1092]

Epoch 18 | train_loss=0.1413 | val_loss=0.7882 | val_f1_mean=0.4084 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.289577,0.27724,0.326742,0.374731,0.284519,0.386473,0.304336,0.271739,0.520807,0.302204,...,0.344561,0.399732,0.700272,0.191919,0.472857,0.282243,0.744624,0.255841,0.33423,0.416392

  → Сохранена лучшая модель (mean F1=0.4084)

Epoch 19/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.35it/s, loss=0.1315]

Epoch 19 | train_loss=0.1261 | val_loss=0.8530 | val_f1_mean=0.4323 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.355685,0.273779,0.34696,0.382531,0.293305,0.457864,0.3425,0.379642,0.561599,0.252144,...,0.371235,0.388802,0.70677,0.228998,0.531897,0.308244,0.736807,0.272251,0.347227,0.354135

  → Сохранена лучшая модель (mean F1=0.4323)

Epoch 20/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.17it/s, loss=0.1142]

Epoch 20 | train_loss=0.1150 | val_loss=0.8859 | val_f1_mean=0.4381 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.337432,0.31746,0.39307,0.400184,0.257143,0.443576,0.36313,0.330673,0.572111,0.274336,...,0.388402,0.43475,0.659977,0.234456,0.510588,0.326344,0.77066,0.279592,0.359864,0.435564

  → Сохранена лучшая модель (mean F1=0.4381)

Epoch 21/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.77it/s, loss=0.1201]

Epoch 21 | train_loss=0.1048 | val_loss=0.9224 | val_f1_mean=0.4496 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.368071,0.393638,0.376157,0.398017,0.315294,0.483919,0.360558,0.40416,0.588808,0.271375,...,0.275253,0.425872,0.696805,0.228916,0.570657,0.356054,0.775121,0.273561,0.386338,0.489722

  → Сохранена лучшая модель (mean F1=0.4496)

Epoch 22/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.39it/s, loss=0.1238]

Epoch 22 | train_loss=0.0964 | val_loss=0.9776 | val_f1_mean=0.4657 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.44052,0.355556,0.397994,0.401271,0.271583,0.444731,0.398607,0.357868,0.659065,0.323831,...,0.354143,0.409045,0.72283,0.244152,0.59044,0.343069,0.756052,0.294017,0.361674,0.438951

  → Сохранена лучшая модель (mean F1=0.4657)

Epoch 23/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.61it/s, loss=0.0308]

Epoch 23 | train_loss=0.0862 | val_loss=1.0734 | val_f1_mean=0.4815 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.430769,0.411043,0.427465,0.421104,0.351852,0.478049,0.399076,0.393064,0.630329,0.32139,...,0.36528,0.462645,0.716174,0.269395,0.629236,0.389242,0.773768,0.304334,0.393963,0.517197

  → Сохранена лучшая модель (mean F1=0.4815)

Epoch 24/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.09it/s, loss=0.0867]

Epoch 24 | train_loss=0.0801 | val_loss=1.0953 | val_f1_mean=0.4942 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.530713,0.499356,0.391672,0.404708,0.328626,0.488487,0.409791,0.47099,0.66935,0.320346,...,0.409639,0.440868,0.729051,0.250375,0.599152,0.379972,0.775653,0.302882,0.411014,0.48445

  → Сохранена лучшая модель (mean F1=0.4942)

Epoch 25/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.40it/s, loss=0.0350]

Epoch 25 | train_loss=0.0735 | val_loss=1.1291 | val_f1_mean=0.4953 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.465116,0.401216,0.441804,0.432281,0.362069,0.475645,0.416839,0.392211,0.625786,0.361783,...,0.401365,0.449123,0.741851,0.277929,0.639378,0.359155,0.783168,0.337451,0.392473,0.506912

  → Сохранена лучшая модель (mean F1=0.4953)

Epoch 26/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.70it/s, loss=0.0533]

Epoch 26 | train_loss=0.0662 | val_loss=1.1880 | val_f1_mean=0.5111 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.456677,0.496847,0.437029,0.468704,0.296223,0.4868,0.452778,0.451299,0.715561,0.343387,...,0.429429,0.476435,0.740468,0.277333,0.661273,0.414365,0.788819,0.33771,0.421145,0.50347

  → Сохранена лучшая модель (mean F1=0.5111)

Epoch 27/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.71it/s, loss=0.0597]

Epoch 27 | train_loss=0.0621 | val_loss=1.2105 | val_f1_mean=0.5143 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.444444,0.56621,0.474768,0.45417,0.339024,0.491551,0.407689,0.441971,0.711563,0.349169,...,0.406685,0.48547,0.777388,0.276292,0.610251,0.377323,0.802847,0.363783,0.419875,0.521108

  → Сохранена лучшая модель (mean F1=0.5143)

Epoch 28/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.21it/s, loss=0.0326]

Epoch 28 | train_loss=0.0574 | val_loss=1.2339 | val_f1_mean=0.5173 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.515366,0.463734,0.448819,0.452606,0.31699,0.521622,0.459646,0.504744,0.690107,0.391502,...,0.367104,0.432194,0.753357,0.278557,0.702263,0.385294,0.775056,0.314019,0.405832,0.529774

  → Сохранена лучшая модель (mean F1=0.5173)

Epoch 29/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.15it/s, loss=0.0405]

Epoch 29 | train_loss=0.0528 | val_loss=1.3384 | val_f1_mean=0.5318 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.560819,0.433815,0.466848,0.481293,0.376119,0.510866,0.447902,0.465608,0.706246,0.414673,...,0.462036,0.480969,0.755345,0.272816,0.683196,0.387383,0.805698,0.361829,0.424188,0.507152

  → Сохранена лучшая модель (mean F1=0.5318)

Epoch 30/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.15it/s, loss=0.0212]

Epoch 30 | train_loss=0.0484 | val_loss=1.3834 | val_f1_mean=0.5314 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.476987,0.532751,0.488163,0.477048,0.346103,0.518711,0.439482,0.461806,0.657763,0.422156,...,0.466724,0.493872,0.76916,0.285092,0.656545,0.395023,0.802697,0.389878,0.414993,0.485697

Epoch 31/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.61it/s, loss=0.0478]

Epoch 31 | train_loss=0.0449 | val_loss=1.4313 | val_f1_mean=0.5454 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.520681,0.554396,0.472134,0.509373,0.329697,0.548815,0.440424,0.469314,0.721795,0.365239,...,0.456053,0.496632,0.780442,0.280584,0.678748,0.399777,0.804769,0.390105,0.417066,0.488067

  → Сохранена лучшая модель (mean F1=0.5454)

Epoch 32/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.39it/s, loss=0.0035]

Epoch 32 | train_loss=0.0416 | val_loss=1.4778 | val_f1_mean=0.5487 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.53706,0.542773,0.487745,0.49923,0.331646,0.538085,0.444952,0.475836,0.708564,0.391176,...,0.465155,0.502116,0.762761,0.284393,0.69308,0.402044,0.802676,0.388358,0.424103,0.507857

  → Сохранена лучшая модель (mean F1=0.5487)

Epoch 33/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.98it/s, loss=0.0608]

Epoch 33 | train_loss=0.0391 | val_loss=1.5413 | val_f1_mean=0.5488 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.547588,0.496104,0.505603,0.497537,0.35514,0.530379,0.46326,0.469725,0.716933,0.392603,...,0.468198,0.485333,0.768206,0.277883,0.700571,0.404455,0.803065,0.374733,0.4289,0.508018

  → Сохранена лучшая модель (mean F1=0.5488)

Epoch 34/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.54it/s, loss=0.0866]

Epoch 34 | train_loss=0.0362 | val_loss=1.5171 | val_f1_mean=0.5482 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.527316,0.549192,0.509873,0.490959,0.335106,0.541312,0.437104,0.505051,0.715457,0.452504,...,0.41954,0.49346,0.761689,0.264957,0.703297,0.388301,0.80261,0.380195,0.460364,0.588613

Epoch 35/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.45it/s, loss=0.0345]

Epoch 35 | train_loss=0.0340 | val_loss=1.6073 | val_f1_mean=0.5608 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.582857,0.618056,0.483092,0.50886,0.395189,0.540191,0.46771,0.523013,0.745202,0.472924,...,0.466216,0.485187,0.766999,0.285041,0.684932,0.402033,0.812083,0.393617,0.451158,0.56192

  → Сохранена лучшая модель (mean F1=0.5608)

Epoch 36/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.49it/s, loss=0.0048]

Epoch 36 | train_loss=0.0299 | val_loss=1.5947 | val_f1_mean=0.5572 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.567674,0.573152,0.511111,0.507521,0.395147,0.538278,0.462132,0.481973,0.736639,0.444444,...,0.450612,0.486173,0.789908,0.275574,0.705476,0.412186,0.81062,0.34789,0.421203,0.543847

Epoch 37/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.48it/s, loss=0.0389]

Epoch 37 | train_loss=0.0281 | val_loss=1.7455 | val_f1_mean=0.5664 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.60767,0.597403,0.509946,0.51294,0.396296,0.567497,0.468973,0.481752,0.756463,0.444846,...,0.47585,0.517588,0.76496,0.292479,0.717979,0.421569,0.806587,0.386648,0.430785,0.555224

  → Сохранена лучшая модель (mean F1=0.5664)

Epoch 38/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.59it/s, loss=0.0192]

Epoch 38 | train_loss=0.0272 | val_loss=1.7333 | val_f1_mean=0.5697 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.551546,0.566265,0.525709,0.505859,0.395062,0.559502,0.471183,0.489627,0.749485,0.445652,...,0.468551,0.518182,0.779086,0.277356,0.73084,0.422466,0.793827,0.404266,0.442716,0.532414

  → Сохранена лучшая модель (mean F1=0.5697)

Epoch 39/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.24it/s, loss=0.0138]

Epoch 39 | train_loss=0.0252 | val_loss=1.8008 | val_f1_mean=0.5743 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.589413,0.584565,0.530906,0.526014,0.397284,0.563185,0.473939,0.507527,0.743746,0.459259,...,0.474191,0.512846,0.790952,0.276289,0.717647,0.430284,0.803362,0.426966,0.459875,0.577192

  → Сохранена лучшая модель (mean F1=0.5743)

Epoch 40/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.29it/s, loss=0.0249]

Epoch 40 | train_loss=0.0228 | val_loss=1.7814 | val_f1_mean=0.5712 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.587904,0.554252,0.535904,0.516701,0.393277,0.569112,0.484914,0.497018,0.746888,0.429936,...,0.489716,0.495822,0.785153,0.283044,0.705815,0.417706,0.81504,0.421339,0.449945,0.561584

Epoch 41/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.91it/s, loss=0.0072]

Epoch 41 | train_loss=0.0215 | val_loss=1.7956 | val_f1_mean=0.5690 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.550251,0.557078,0.527368,0.522399,0.40354,0.553025,0.498571,0.460145,0.766106,0.41116,...,0.478145,0.514883,0.776952,0.294833,0.747155,0.411799,0.811469,0.400576,0.455237,0.566009

Epoch 42/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.29it/s, loss=0.0110]

Epoch 42 | train_loss=0.0210 | val_loss=1.8771 | val_f1_mean=0.5757 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.585499,0.489796,0.526934,0.518468,0.434238,0.561113,0.480477,0.489796,0.753247,0.450867,...,0.494706,0.490425,0.796121,0.279863,0.729355,0.417425,0.807245,0.417778,0.433508,0.587156

  → Сохранена лучшая модель (mean F1=0.5757)

Epoch 43/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.94it/s, loss=0.0268]

Epoch 43 | train_loss=0.0184 | val_loss=1.8594 | val_f1_mean=0.5701 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.542289,0.535817,0.510788,0.539118,0.422311,0.581733,0.482074,0.45283,0.741784,0.458824,...,0.464348,0.504161,0.770541,0.275542,0.712345,0.406452,0.809655,0.411187,0.454348,0.562092

Epoch 44/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.45it/s, loss=0.0163]

Epoch 44 | train_loss=0.0173 | val_loss=1.9359 | val_f1_mean=0.5846 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.576503,0.604341,0.529768,0.544643,0.422764,0.567826,0.477045,0.5,0.750172,0.477366,...,0.502924,0.524778,0.786597,0.270981,0.713429,0.432773,0.806768,0.441496,0.462974,0.549387

  → Сохранена лучшая модель (mean F1=0.5846)

Epoch 45/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.17it/s, loss=0.0166]

Epoch 45 | train_loss=0.0165 | val_loss=1.9407 | val_f1_mean=0.5820 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.610795,0.604269,0.525849,0.533333,0.422222,0.593954,0.473684,0.512035,0.741176,0.420701,...,0.504348,0.528944,0.790342,0.295775,0.710526,0.429945,0.810014,0.416796,0.447942,0.58121

Epoch 46/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.79it/s, loss=0.0049]

Epoch 46 | train_loss=0.0155 | val_loss=1.9786 | val_f1_mean=0.5776 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.576577,0.597403,0.526621,0.535629,0.415094,0.562707,0.491913,0.450091,0.751161,0.424132,...,0.500501,0.540873,0.801568,0.277487,0.731156,0.428266,0.81235,0.422653,0.446243,0.562691

Epoch 47/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.83it/s, loss=0.0050]

Epoch 47 | train_loss=0.0133 | val_loss=2.0533 | val_f1_mean=0.5809 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.594816,0.610229,0.537194,0.518519,0.372093,0.574211,0.49763,0.447602,0.759476,0.43152,...,0.508197,0.534111,0.786378,0.284457,0.736173,0.445066,0.813193,0.425532,0.452242,0.585446

Epoch 48/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.58it/s, loss=0.0007]

Epoch 48 | train_loss=0.0127 | val_loss=2.1254 | val_f1_mean=0.5873 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.63253,0.611511,0.518735,0.530903,0.427419,0.600421,0.485149,0.517544,0.74718,0.456814,...,0.466036,0.525196,0.7898,0.312155,0.727273,0.442504,0.799334,0.413862,0.443933,0.588916

  → Сохранена лучшая модель (mean F1=0.5873)

Epoch 49/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.98it/s, loss=0.0087]

Epoch 49 | train_loss=0.0123 | val_loss=2.1127 | val_f1_mean=0.5831 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.53753,0.586885,0.466012,0.512104,0.399254,0.601724,0.505846,0.460967,0.764376,0.436823,...,0.489594,0.517507,0.790787,0.290855,0.718938,0.446545,0.812823,0.430769,0.447115,0.584342

Epoch 50/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.13it/s, loss=0.0098]

Epoch 50 | train_loss=0.0117 | val_loss=2.1080 | val_f1_mean=0.5884 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.622433,0.625442,0.535491,0.528426,0.408818,0.571104,0.490859,0.516949,0.773427,0.445269,...,0.504892,0.537346,0.782445,0.265332,0.740648,0.445078,0.803441,0.421053,0.459494,0.594915

  → Сохранена лучшая модель (mean F1=0.5884)

Epoch 51/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.52it/s, loss=0.0065]

Epoch 51 | train_loss=0.0104 | val_loss=2.1868 | val_f1_mean=0.5833 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.628305,0.589404,0.540893,0.529204,0.431535,0.584468,0.494355,0.488889,0.758715,0.473581,...,0.504082,0.523566,0.781272,0.269504,0.720527,0.421981,0.811897,0.402892,0.445293,0.592466

Epoch 52/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.67it/s, loss=0.0017]

Epoch 52 | train_loss=0.0100 | val_loss=2.2034 | val_f1_mean=0.5936 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.623881,0.629496,0.508118,0.539378,0.42953,0.602479,0.48764,0.49497,0.753989,0.461248,...,0.500493,0.528217,0.792471,0.282913,0.726044,0.454142,0.816478,0.442229,0.456,0.579235

  → Сохранена лучшая модель (mean F1=0.5936)

Epoch 53/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.92it/s, loss=0.0734]

Epoch 53 | train_loss=0.0088 | val_loss=2.1951 | val_f1_mean=0.5886 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.568475,0.606383,0.536893,0.529734,0.411523,0.593611,0.491389,0.486022,0.757085,0.452242,...,0.502058,0.546628,0.798131,0.27027,0.738796,0.444931,0.806836,0.435258,0.453608,0.592094

Epoch 54/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.22it/s, loss=0.0033]

Epoch 54 | train_loss=0.0089 | val_loss=2.2719 | val_f1_mean=0.5932 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.631579,0.619718,0.529843,0.538402,0.441048,0.59511,0.487662,0.453686,0.765027,0.465696,...,0.510917,0.521539,0.805041,0.276176,0.731061,0.452544,0.809617,0.426869,0.445836,0.579424

Epoch 55/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.45it/s, loss=0.0096]

Epoch 55 | train_loss=0.0081 | val_loss=2.2208 | val_f1_mean=0.5887 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.572539,0.590604,0.524733,0.53814,0.429185,0.598312,0.503632,0.472222,0.745407,0.422877,...,0.515312,0.526608,0.787017,0.270106,0.721724,0.434783,0.815487,0.421569,0.446688,0.589441

Epoch 56/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.57it/s, loss=0.0047]

Epoch 56 | train_loss=0.0076 | val_loss=2.3145 | val_f1_mean=0.5958 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.620087,0.632143,0.517274,0.545383,0.436681,0.596186,0.477581,0.468619,0.76257,0.43088,...,0.508039,0.533178,0.790608,0.275862,0.739432,0.458797,0.817085,0.446914,0.446009,0.599327

  → Сохранена лучшая модель (mean F1=0.5958)

Epoch 57/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.43it/s, loss=0.0078]

Epoch 57 | train_loss=0.0072 | val_loss=2.3834 | val_f1_mean=0.5970 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.639053,0.649156,0.527938,0.534572,0.428256,0.598305,0.490657,0.478528,0.773276,0.483221,...,0.496208,0.532143,0.796985,0.277778,0.745073,0.444287,0.817028,0.4375,0.463514,0.603707

  → Сохранена лучшая модель (mean F1=0.5970)

Epoch 58/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.37it/s, loss=0.0036]

Epoch 58 | train_loss=0.0070 | val_loss=2.3791 | val_f1_mean=0.5972 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.659341,0.642023,0.535385,0.535974,0.433781,0.607394,0.497231,0.50211,0.762166,0.419795,...,0.509372,0.527436,0.803283,0.276498,0.759309,0.448071,0.808583,0.434629,0.450034,0.601695

  → Сохранена лучшая модель (mean F1=0.5972)

Epoch 59/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.70it/s, loss=0.0078]

Epoch 59 | train_loss=0.0065 | val_loss=2.4276 | val_f1_mean=0.5966 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.658228,0.640596,0.527397,0.539557,0.435556,0.574016,0.489846,0.482353,0.754458,0.463938,...,0.481707,0.535312,0.80559,0.27543,0.732834,0.447474,0.809625,0.429074,0.454228,0.596462

Epoch 60/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.13it/s, loss=0.0019]

Epoch 60 | train_loss=0.0061 | val_loss=2.3888 | val_f1_mean=0.5958 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.645926,0.641929,0.53285,0.535156,0.449541,0.590269,0.499389,0.484,0.747268,0.459016,...,0.482688,0.531975,0.793444,0.26685,0.758435,0.424364,0.812222,0.445394,0.461434,0.595525

Epoch 61/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.43it/s, loss=0.0024]

Epoch 61 | train_loss=0.0057 | val_loss=2.5005 | val_f1_mean=0.6020 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.605375,0.634686,0.52535,0.537795,0.449649,0.602389,0.501211,0.483801,0.774658,0.471338,...,0.511312,0.53231,0.800894,0.277228,0.759443,0.444619,0.812492,0.440356,0.458509,0.609735

  → Сохранена лучшая модель (mean F1=0.6020)

Epoch 62/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.48it/s, loss=0.0027]

Epoch 62 | train_loss=0.0053 | val_loss=2.4647 | val_f1_mean=0.6004 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.618557,0.641651,0.53006,0.538217,0.445476,0.616797,0.5,0.512472,0.757016,0.44664,...,0.533178,0.522624,0.798524,0.274062,0.736776,0.460683,0.816967,0.43554,0.46185,0.600161

Epoch 63/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.77it/s, loss=0.0009]

Epoch 63 | train_loss=0.0051 | val_loss=2.5335 | val_f1_mean=0.6027 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.659375,0.639405,0.544858,0.540937,0.431624,0.597643,0.495858,0.522936,0.762712,0.47983,...,0.521452,0.52434,0.808261,0.290909,0.733123,0.459608,0.811668,0.427964,0.442359,0.605802

  → Сохранена лучшая модель (mean F1=0.6027)

Epoch 64/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.59it/s, loss=0.0019]

Epoch 64 | train_loss=0.0048 | val_loss=2.5362 | val_f1_mean=0.5983 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.64486,0.642166,0.518519,0.539007,0.424908,0.612096,0.486201,0.497942,0.700844,0.472574,...,0.539352,0.549304,0.796447,0.290172,0.701449,0.463038,0.809549,0.428316,0.449731,0.599479

Epoch 65/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.24it/s, loss=0.0093]

Epoch 65 | train_loss=0.0044 | val_loss=2.5574 | val_f1_mean=0.6015 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.60745,0.644068,0.538462,0.546008,0.42623,0.611934,0.50226,0.520362,0.758715,0.477477,...,0.523179,0.543367,0.800591,0.292758,0.762416,0.440367,0.810433,0.435768,0.457393,0.615385

Epoch 66/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.41it/s, loss=0.0003]

Epoch 66 | train_loss=0.0043 | val_loss=2.5824 | val_f1_mean=0.6024 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.632716,0.651852,0.52451,0.536107,0.429864,0.611607,0.495012,0.519016,0.752925,0.471366,...,0.519337,0.530266,0.796305,0.288079,0.749177,0.445188,0.812517,0.433591,0.45082,0.61913

Epoch 67/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.62it/s, loss=0.0090]

Epoch 67 | train_loss=0.0042 | val_loss=2.5295 | val_f1_mean=0.6002 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.619677,0.630631,0.522717,0.547629,0.427928,0.61573,0.497512,0.496703,0.724936,0.484581,...,0.515575,0.522854,0.800098,0.289634,0.741814,0.448276,0.816398,0.442198,0.450488,0.611399

Epoch 68/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.10it/s, loss=0.0344]

Epoch 68 | train_loss=0.0037 | val_loss=2.6136 | val_f1_mean=0.6044 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.646593,0.651252,0.538341,0.548909,0.425629,0.60964,0.484886,0.530806,0.742934,0.482759,...,0.521158,0.529717,0.807634,0.286982,0.733624,0.461187,0.811884,0.441943,0.457926,0.607725

  → Сохранена лучшая модель (mean F1=0.6044)

Epoch 69/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.25it/s, loss=0.0052]

Epoch 69 | train_loss=0.0035 | val_loss=2.6135 | val_f1_mean=0.6064 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.637636,0.647619,0.5483,0.550358,0.442922,0.615315,0.498084,0.483168,0.757388,0.467925,...,0.543902,0.543849,0.812326,0.277286,0.749835,0.455108,0.812723,0.454602,0.462162,0.592532

  → Сохранена лучшая модель (mean F1=0.6064)

Epoch 70/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.36it/s, loss=0.0016]

Epoch 70 | train_loss=0.0032 | val_loss=2.6860 | val_f1_mean=0.6066 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.652174,0.642857,0.543547,0.554506,0.432802,0.617426,0.497182,0.512141,0.758669,0.481308,...,0.519337,0.539559,0.806957,0.291066,0.756579,0.462662,0.814046,0.441065,0.466617,0.615385

  → Сохранена лучшая модель (mean F1=0.6066)

Epoch 71/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.98it/s, loss=0.0012]

Epoch 71 | train_loss=0.0033 | val_loss=2.6355 | val_f1_mean=0.6067 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.657051,0.651429,0.540336,0.548731,0.43956,0.615244,0.496077,0.488613,0.761111,0.477223,...,0.517857,0.538745,0.803536,0.285714,0.741915,0.465667,0.814647,0.450331,0.460114,0.605263

  → Сохранена лучшая модель (mean F1=0.6067)

Epoch 72/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.69it/s, loss=0.0021]

Epoch 72 | train_loss=0.0030 | val_loss=2.7040 | val_f1_mean=0.6078 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.65,0.644567,0.528917,0.551201,0.446512,0.606113,0.491505,0.52381,0.759529,0.478261,...,0.558897,0.521348,0.810038,0.268966,0.748523,0.460899,0.815906,0.432977,0.454172,0.594228

  → Сохранена лучшая модель (mean F1=0.6078)

Epoch 73/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.06it/s, loss=0.0013]

Epoch 73 | train_loss=0.0026 | val_loss=2.6747 | val_f1_mean=0.6104 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.666667,0.664107,0.552207,0.553579,0.421978,0.619861,0.509186,0.532067,0.769774,0.478814,...,0.529089,0.538755,0.799509,0.285276,0.750484,0.462992,0.816332,0.454311,0.452675,0.604895

  → Сохранена лучшая модель (mean F1=0.6104)

Epoch 74/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.47it/s, loss=0.0050]

Epoch 74 | train_loss=0.0028 | val_loss=2.7043 | val_f1_mean=0.6116 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.674304,0.667969,0.545738,0.548652,0.445916,0.618018,0.501229,0.518868,0.759094,0.497696,...,0.52968,0.531966,0.809571,0.270769,0.732377,0.476423,0.81715,0.456682,0.451474,0.603902

  → Сохранена лучшая модель (mean F1=0.6116)

Epoch 75/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.05it/s, loss=0.0007]

Epoch 75 | train_loss=0.0023 | val_loss=2.7233 | val_f1_mean=0.6094 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.657364,0.648855,0.549342,0.539117,0.431373,0.612172,0.509908,0.519722,0.769774,0.48951,...,0.508827,0.539233,0.806764,0.265842,0.757191,0.443503,0.819943,0.435821,0.447626,0.601641

Epoch 76/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.17it/s, loss=0.0007]

Epoch 76 | train_loss=0.0022 | val_loss=2.7956 | val_f1_mean=0.6105 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.667758,0.638941,0.559294,0.54112,0.439614,0.612605,0.514001,0.498886,0.764539,0.465209,...,0.526193,0.541927,0.804745,0.280811,0.75,0.467105,0.818244,0.448319,0.450766,0.61326

Epoch 77/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.26it/s, loss=0.0023]

Epoch 77 | train_loss=0.0021 | val_loss=2.7263 | val_f1_mean=0.6077 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.61516,0.669246,0.54874,0.55076,0.432802,0.607407,0.495368,0.502242,0.782546,0.490991,...,0.504772,0.539823,0.808329,0.288344,0.752137,0.455942,0.818034,0.44644,0.449213,0.615529

Epoch 78/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.90it/s, loss=0.0044]

Epoch 78 | train_loss=0.0021 | val_loss=2.8637 | val_f1_mean=0.6108 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.650641,0.654902,0.551043,0.55002,0.440449,0.615595,0.505452,0.520681,0.76762,0.497653,...,0.520397,0.539326,0.807509,0.280639,0.755116,0.461165,0.818182,0.452583,0.458015,0.611765

Epoch 79/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.24it/s, loss=0.0014]

Epoch 79 | train_loss=0.0019 | val_loss=2.8487 | val_f1_mean=0.6126 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.66343,0.643939,0.555494,0.555462,0.444988,0.616608,0.502295,0.514943,0.758527,0.486726,...,0.540284,0.541176,0.808106,0.28436,0.744819,0.47619,0.817849,0.442758,0.459088,0.61302

  → Сохранена лучшая модель (mean F1=0.6126)

Epoch 80/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.46it/s, loss=0.0008]

Epoch 80 | train_loss=0.0019 | val_loss=2.8377 | val_f1_mean=0.6100 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.633484,0.641166,0.548523,0.556061,0.443902,0.61188,0.502604,0.509091,0.763736,0.463074,...,0.519274,0.550687,0.80238,0.297872,0.746926,0.459397,0.815462,0.452618,0.459636,0.615658

Epoch 81/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.18it/s, loss=0.0009]

Epoch 81 | train_loss=0.0019 | val_loss=2.8812 | val_f1_mean=0.6122 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.651969,0.656546,0.54721,0.557789,0.436451,0.61633,0.505867,0.512941,0.765229,0.481308,...,0.545232,0.53866,0.799409,0.282759,0.755937,0.459697,0.816978,0.450031,0.450216,0.614035

Epoch 82/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.18it/s, loss=0.0006]

Epoch 82 | train_loss=0.0016 | val_loss=2.9107 | val_f1_mean=0.6124 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.660099,0.650558,0.553215,0.550928,0.420804,0.618297,0.504673,0.516432,0.765229,0.486998,...,0.525967,0.548741,0.804988,0.292913,0.750653,0.465116,0.817974,0.451157,0.450037,0.614159

Epoch 83/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.46it/s, loss=0.0004]

Epoch 83 | train_loss=0.0017 | val_loss=2.8722 | val_f1_mean=0.6115 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.649762,0.661654,0.550756,0.554792,0.451902,0.627002,0.500968,0.502283,0.768385,0.502262,...,0.527043,0.548896,0.806067,0.298812,0.745301,0.461017,0.81915,0.448254,0.45116,0.610659

Epoch 84/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.49it/s, loss=0.0002]

Epoch 84 | train_loss=0.0016 | val_loss=2.9025 | val_f1_mean=0.6139 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.655949,0.656,0.549206,0.54883,0.460497,0.614973,0.497885,0.528037,0.775596,0.494118,...,0.531178,0.550613,0.805673,0.302067,0.743738,0.472973,0.817581,0.447781,0.455959,0.609991

  → Сохранена лучшая модель (mean F1=0.6139)

Epoch 85/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.82it/s, loss=0.0011]

Epoch 85 | train_loss=0.0015 | val_loss=2.8620 | val_f1_mean=0.6130 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.652597,0.662791,0.547771,0.56338,0.460465,0.618392,0.5,0.505495,0.773427,0.494279,...,0.529279,0.528779,0.806718,0.294294,0.740088,0.467836,0.821224,0.451196,0.457321,0.608924

Epoch 86/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.39it/s, loss=0.0002]

Epoch 86 | train_loss=0.0014 | val_loss=2.9194 | val_f1_mean=0.6131 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.651685,0.658041,0.551724,0.561346,0.438903,0.622906,0.511959,0.503341,0.781495,0.494005,...,0.53139,0.540789,0.805638,0.290323,0.748523,0.454698,0.819386,0.445722,0.454609,0.617462

Epoch 87/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.80it/s, loss=0.0004]

Epoch 87 | train_loss=0.0012 | val_loss=2.9178 | val_f1_mean=0.6129 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.635368,0.647727,0.549061,0.553783,0.444444,0.612084,0.494408,0.525822,0.78556,0.494005,...,0.541618,0.544423,0.806082,0.288557,0.757191,0.462036,0.818528,0.457105,0.443615,0.609524

Epoch 88/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.67it/s, loss=0.0003]

Epoch 88 | train_loss=0.0013 | val_loss=2.9992 | val_f1_mean=0.6146 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.664441,0.664062,0.556679,0.550079,0.447005,0.603774,0.501906,0.521127,0.782298,0.495238,...,0.537835,0.546782,0.808972,0.301639,0.758205,0.466278,0.81671,0.449935,0.45085,0.608133

  → Сохранена лучшая модель (mean F1=0.6146)

Epoch 89/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.57it/s, loss=0.0008]

Epoch 89 | train_loss=0.0012 | val_loss=2.9960 | val_f1_mean=0.6141 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.653907,0.649903,0.55525,0.550822,0.454333,0.594438,0.507266,0.513761,0.786436,0.5,...,0.537915,0.549538,0.807159,0.286184,0.765064,0.468828,0.816349,0.460131,0.438125,0.614515

Epoch 90/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.35it/s, loss=0.0006]

Epoch 90 | train_loss=0.0011 | val_loss=2.9995 | val_f1_mean=0.6157 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.647887,0.653386,0.559425,0.553036,0.453271,0.61706,0.505566,0.533654,0.77937,0.514851,...,0.535673,0.55168,0.806029,0.283912,0.754843,0.471074,0.817277,0.455497,0.449695,0.611059

  → Сохранена лучшая модель (mean F1=0.6157)

Epoch 91/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.08it/s, loss=0.0003]

Epoch 91 | train_loss=0.0011 | val_loss=3.0233 | val_f1_mean=0.6154 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.668852,0.653465,0.560922,0.552907,0.449438,0.619718,0.502939,0.515419,0.769659,0.497653,...,0.537241,0.541535,0.813242,0.278317,0.758713,0.47,0.816156,0.455796,0.454142,0.606285

Epoch 92/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.50it/s, loss=0.0004]

Epoch 92 | train_loss=0.0010 | val_loss=3.0597 | val_f1_mean=0.6160 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.659091,0.649805,0.554283,0.555788,0.455206,0.6125,0.506876,0.52093,0.780172,0.495146,...,0.539192,0.539703,0.810362,0.280405,0.763908,0.46932,0.816712,0.462799,0.461988,0.6164

  → Сохранена лучшая модель (mean F1=0.6160)

Epoch 93/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.86it/s, loss=0.0003]

Epoch 93 | train_loss=0.0010 | val_loss=3.0400 | val_f1_mean=0.6157 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.648986,0.656126,0.55902,0.558199,0.454976,0.615801,0.510152,0.525346,0.77574,0.485981,...,0.54633,0.53996,0.812011,0.270728,0.759732,0.469609,0.818565,0.46123,0.457393,0.611765

Epoch 94/100: 100%|██████████| 3929/3929 [00:26<00:00, 151.11it/s, loss=0.0006]

Epoch 94 | train_loss=0.0011 | val_loss=3.0630 | val_f1_mean=0.6165 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.665568,0.662835,0.563492,0.557078,0.454545,0.619134,0.510471,0.523364,0.785303,0.494172,...,0.543504,0.535598,0.810648,0.285223,0.759732,0.472881,0.819382,0.45149,0.455133,0.609403

  → Сохранена лучшая модель (mean F1=0.6165)

Epoch 95/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.97it/s, loss=0.0006]

Epoch 95 | train_loss=0.0009 | val_loss=3.0624 | val_f1_mean=0.6173 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.662295,0.657895,0.563616,0.559294,0.45933,0.626852,0.511658,0.523364,0.780558,0.493023,...,0.544803,0.53493,0.813482,0.281457,0.754843,0.472574,0.820408,0.44623,0.455072,0.609645

  → Сохранена лучшая модель (mean F1=0.6173)

Epoch 96/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.29it/s, loss=0.0001]

Epoch 96 | train_loss=0.0009 | val_loss=3.0577 | val_f1_mean=0.6156 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.655897,0.653846,0.562063,0.560732,0.462287,0.60733,0.51092,0.51954,0.767085,0.501149,...,0.540476,0.540067,0.814124,0.288625,0.750329,0.466003,0.81905,0.454837,0.449589,0.612546

Epoch 97/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.55it/s, loss=0.0004]

Epoch 97 | train_loss=0.0009 | val_loss=3.0834 | val_f1_mean=0.6174 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.653907,0.654832,0.55832,0.559664,0.458537,0.621536,0.514582,0.525822,0.777541,0.501149,...,0.544554,0.536939,0.809917,0.291096,0.751323,0.468966,0.817398,0.460212,0.457393,0.609403

  → Сохранена лучшая модель (mean F1=0.6174)

Epoch 98/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.07it/s, loss=0.0072]

Epoch 98 | train_loss=0.0009 | val_loss=3.0780 | val_f1_mean=0.6164 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.662359,0.660156,0.560894,0.558491,0.456576,0.618659,0.516513,0.522145,0.769446,0.50463,...,0.538922,0.537234,0.813936,0.290598,0.753836,0.468193,0.817443,0.458607,0.453623,0.614535

Epoch 99/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.96it/s, loss=0.0009]

Epoch 99 | train_loss=0.0008 | val_loss=3.0952 | val_f1_mean=0.6169 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.661264,0.654832,0.560976,0.557652,0.455882,0.621129,0.517241,0.528302,0.767296,0.503464,...,0.531863,0.538667,0.81332,0.291032,0.757229,0.466383,0.817715,0.459709,0.453353,0.613699

Epoch 100/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.84it/s, loss=0.0002]

Epoch 100 | train_loss=0.0010 | val_loss=3.0959 | val_f1_mean=0.6174 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.660194,0.656189,0.560354,0.557983,0.458937,0.621572,0.517241,0.525822,0.767832,0.503464,...,0.537129,0.537849,0.812783,0.292096,0.757229,0.46587,0.8171,0.458691,0.450867,0.613285

  → Сохранена лучшая модель (mean F1=0.6174)

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.660194,0.656189,0.560354,0.557983,0.458937,0.621572,0.517241,0.525822,0.767832,0.503464,...,0.537129,0.537849,0.812783,0.292096,0.757229,0.46587,0.8171,0.458691,0.450867,0.613285

In [ ]:
rnn_model = RNN_Text_Classifier(
    num_classes=len(le.categories_[0]),
    vocab_size=len(tokenizer.get_vocab()),
    embedding_dim=256,
    hidden_size=64,
)

In [ ]:
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = AdamW(rnn_model.parameters(), lr=0.001, weight_decay=0.01)
rnn_model.to(DEVICE)

training(
    model=rnn_model,
    train_data_loader=train_dl,
    val_data_loader=val_dl,
    optimizer=optimizer,
    epoches=EPOCHS,
    criterion=criterion,
    tokenizator=le,
    accum_steps=ACCUM_STEPS,
    warmup_frac=WARMUP_FRAC,
    device=DEVICE,
    save_path="RNN_news_classifier"
    )

Epoch 1/100: 100%|██████████| 3929/3929 [00:20<00:00, 191.61it/s, loss=1.0024]

Epoch 1 | train_loss=1.3570 | val_loss=1.3269 | val_f1_mean=0.0573 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.052103,0.017836,0.043781,0.057645,0.019585,0.061354,0.046257,0.019593,0.046925,0.009441,...,0.028508,0.042915,0.080482,0.022516,0.05595,0.028506,0.198272,0.034512,0.041638,0.117872

  → Сохранена лучшая модель (mean F1=0.0573)

Epoch 2/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.97it/s, loss=1.1704]

Epoch 2 | train_loss=1.3025 | val_loss=1.2759 | val_f1_mean=0.0647 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.040181,0.017625,0.040752,0.058185,0.013375,0.07864,0.055243,0.019334,0.063131,0.0,...,0.022055,0.042975,0.099358,0.022946,0.075064,0.03065,0.209654,0.036573,0.045472,0.120461

  → Сохранена лучшая модель (mean F1=0.0647)

Epoch 3/100: 100%|██████████| 3929/3929 [00:20<00:00, 188.92it/s, loss=0.9198]

Epoch 3 | train_loss=1.2702 | val_loss=1.2613 | val_f1_mean=0.0678 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.025324,0.01784,0.043777,0.0641,0.014105,0.087619,0.055021,0.021556,0.066189,0.011514,...,0.028457,0.04359,0.103068,0.022946,0.07841,0.030447,0.2138,0.03715,0.044162,0.121027

  → Сохранена лучшая модель (mean F1=0.0678)

Epoch 4/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.94it/s, loss=0.8162]

Epoch 4 | train_loss=1.2279 | val_loss=1.1708 | val_f1_mean=0.0760 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.036596,0.028024,0.0546,0.06977,0.017996,0.06946,0.053933,0.017955,0.062838,0.024313,...,0.027546,0.068392,0.161366,0.036289,0.070577,0.049023,0.286198,0.038839,0.067045,0.064892

  → Сохранена лучшая модель (mean F1=0.0760)

Epoch 5/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.80it/s, loss=1.6975]

Epoch 5 | train_loss=1.1545 | val_loss=1.1374 | val_f1_mean=0.0791 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.035538,0.032027,0.057419,0.075211,0.019157,0.07516,0.05792,0.020061,0.07131,0.021083,...,0.028879,0.069666,0.154568,0.037507,0.076836,0.056451,0.265532,0.03709,0.068801,0.06064

  → Сохранена лучшая модель (mean F1=0.0791)

Epoch 6/100: 100%|██████████| 3929/3929 [00:21<00:00, 182.26it/s, loss=0.8345]

Epoch 6 | train_loss=1.1195 | val_loss=1.1131 | val_f1_mean=0.0829 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.037446,0.031261,0.063114,0.075685,0.020242,0.089612,0.0606,0.017538,0.058579,0.022025,...,0.031985,0.073678,0.161063,0.043026,0.063607,0.057938,0.273055,0.043631,0.072468,0.077574

  → Сохранена лучшая модель (mean F1=0.0829)

Epoch 7/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.86it/s, loss=1.0366]

Epoch 7 | train_loss=1.0940 | val_loss=1.1092 | val_f1_mean=0.0836 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.037895,0.033117,0.062319,0.077071,0.020262,0.097527,0.063058,0.017023,0.060569,0.020154,...,0.039254,0.079458,0.158159,0.040577,0.062207,0.060263,0.274623,0.045584,0.08209,0.084855

  → Сохранена лучшая модель (mean F1=0.0836)

Epoch 8/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.47it/s, loss=0.9488]

Epoch 8 | train_loss=1.0724 | val_loss=1.1133 | val_f1_mean=0.0886 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.03852,0.031327,0.059151,0.080305,0.020954,0.082642,0.056167,0.01738,0.066552,0.023039,...,0.041646,0.102664,0.168134,0.050623,0.072756,0.057781,0.29935,0.051081,0.101384,0.065934

  → Сохранена лучшая модель (mean F1=0.0886)

Epoch 9/100: 100%|██████████| 3929/3929 [00:21<00:00, 184.01it/s, loss=0.9545]

Epoch 9 | train_loss=1.0517 | val_loss=1.0942 | val_f1_mean=0.0899 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.038565,0.03804,0.064265,0.083624,0.019185,0.104341,0.065845,0.017406,0.064727,0.021951,...,0.046898,0.10817,0.157127,0.05476,0.067465,0.06425,0.28677,0.048516,0.119598,0.064161

  → Сохранена лучшая модель (mean F1=0.0899)

Epoch 10/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.20it/s, loss=1.1635]

Epoch 10 | train_loss=1.0285 | val_loss=1.0747 | val_f1_mean=0.0911 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.042322,0.031673,0.067512,0.082149,0.019569,0.105199,0.062983,0.018341,0.069672,0.023859,...,0.046067,0.089632,0.169221,0.041814,0.07445,0.060479,0.305911,0.047561,0.082931,0.074535

  → Сохранена лучшая модель (mean F1=0.0911)

Epoch 11/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.30it/s, loss=0.8215]

Epoch 11 | train_loss=1.0027 | val_loss=1.1074 | val_f1_mean=0.0937 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.040266,0.035935,0.06596,0.084657,0.019006,0.093174,0.062497,0.017422,0.069444,0.022153,...,0.057227,0.114903,0.166581,0.054387,0.071284,0.054537,0.3082,0.059942,0.122146,0.080806

  → Сохранена лучшая модель (mean F1=0.0937)

Epoch 12/100: 100%|██████████| 3929/3929 [00:20<00:00, 187.54it/s, loss=0.9789]

Epoch 12 | train_loss=0.9761 | val_loss=1.1249 | val_f1_mean=0.0961 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.057333,0.045933,0.066439,0.089046,0.021394,0.095546,0.060886,0.017908,0.07002,0.023888,...,0.065205,0.131795,0.168157,0.052534,0.072133,0.053812,0.312071,0.055118,0.119912,0.102376

  → Сохранена лучшая модель (mean F1=0.0961)

Epoch 13/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.71it/s, loss=1.0430]

Epoch 13 | train_loss=0.9496 | val_loss=1.1430 | val_f1_mean=0.0994 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.041973,0.041982,0.069473,0.091498,0.019827,0.096522,0.059626,0.01772,0.080922,0.0265,...,0.063593,0.134392,0.177085,0.047713,0.080539,0.055234,0.329087,0.054772,0.137623,0.120871

  → Сохранена лучшая модель (mean F1=0.0994)

Epoch 14/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.53it/s, loss=0.8802]

Epoch 14 | train_loss=0.9285 | val_loss=1.1378 | val_f1_mean=0.1011 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.04422,0.044164,0.070518,0.090577,0.02275,0.097834,0.062116,0.019649,0.072462,0.025976,...,0.061576,0.142627,0.17064,0.055878,0.07703,0.054338,0.310789,0.058204,0.14116,0.12911

  → Сохранена лучшая модель (mean F1=0.1011)

Epoch 15/100: 100%|██████████| 3929/3929 [00:20<00:00, 191.90it/s, loss=1.3143]

Epoch 15 | train_loss=0.9096 | val_loss=1.1219 | val_f1_mean=0.1006 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.038599,0.040399,0.069814,0.086166,0.021256,0.106231,0.067422,0.019986,0.075911,0.025434,...,0.063102,0.119431,0.170237,0.053936,0.08267,0.059487,0.311552,0.049451,0.12603,0.098236

Epoch 16/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.48it/s, loss=1.0153]

Epoch 16 | train_loss=0.8897 | val_loss=1.1504 | val_f1_mean=0.1028 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.062871,0.047657,0.070965,0.087819,0.025455,0.096897,0.06123,0.020012,0.079128,0.027377,...,0.058412,0.134134,0.174967,0.057831,0.085177,0.056149,0.323435,0.061864,0.128975,0.121856

  → Сохранена лучшая модель (mean F1=0.1028)

Epoch 17/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.17it/s, loss=0.6757]

Epoch 17 | train_loss=0.8665 | val_loss=1.1712 | val_f1_mean=0.1033 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.052777,0.051681,0.07011,0.090155,0.02328,0.100428,0.065515,0.020634,0.083471,0.023357,...,0.06135,0.149966,0.169683,0.056387,0.088433,0.055919,0.316433,0.05529,0.141493,0.089494

  → Сохранена лучшая модель (mean F1=0.1033)

Epoch 18/100: 100%|██████████| 3929/3929 [00:20<00:00, 191.78it/s, loss=0.8014]

Epoch 18 | train_loss=0.8506 | val_loss=1.2031 | val_f1_mean=0.1065 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.047048,0.05368,0.068366,0.09281,0.023332,0.093036,0.061801,0.018936,0.084905,0.023976,...,0.068097,0.145642,0.179315,0.05632,0.088715,0.056031,0.327551,0.060293,0.145442,0.121463

  → Сохранена лучшая модель (mean F1=0.1065)

Epoch 19/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.89it/s, loss=0.9258]

Epoch 19 | train_loss=0.8361 | val_loss=1.2072 | val_f1_mean=0.1062 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.047729,0.051282,0.072803,0.093198,0.024239,0.102091,0.074782,0.019914,0.082689,0.028361,...,0.06995,0.147687,0.175885,0.058431,0.087411,0.05823,0.327603,0.055033,0.135895,0.133834

Epoch 20/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.97it/s, loss=0.7173]

Epoch 20 | train_loss=0.8163 | val_loss=1.1630 | val_f1_mean=0.1074 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.047385,0.043921,0.072328,0.089222,0.024388,0.104919,0.070503,0.020649,0.094606,0.030294,...,0.061001,0.140668,0.181205,0.0567,0.09183,0.060223,0.329413,0.05892,0.134907,0.107183

  → Сохранена лучшая модель (mean F1=0.1074)

Epoch 21/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.43it/s, loss=0.8668]

Epoch 21 | train_loss=0.8024 | val_loss=1.2892 | val_f1_mean=0.1097 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.049054,0.060108,0.071019,0.098574,0.023784,0.096825,0.06715,0.021305,0.08571,0.027192,...,0.077232,0.15853,0.178561,0.056099,0.088332,0.059215,0.332179,0.059151,0.161737,0.126996

  → Сохранена лучшая модель (mean F1=0.1097)

Epoch 22/100: 100%|██████████| 3929/3929 [00:20<00:00, 190.32it/s, loss=0.6185]

Epoch 22 | train_loss=0.7857 | val_loss=1.2426 | val_f1_mean=0.1080 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.049743,0.058049,0.07198,0.093778,0.027415,0.102053,0.085567,0.020876,0.086242,0.028487,...,0.077737,0.164114,0.175018,0.060166,0.085775,0.067363,0.320559,0.058174,0.148161,0.12843

Epoch 23/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.20it/s, loss=0.6863]

Epoch 23 | train_loss=0.7722 | val_loss=1.2801 | val_f1_mean=0.1092 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.04877,0.057248,0.073122,0.099603,0.025501,0.105407,0.076077,0.019529,0.081145,0.027646,...,0.070148,0.16079,0.17167,0.06359,0.083816,0.068586,0.31375,0.063508,0.162459,0.133552

Epoch 24/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.45it/s, loss=0.8469]

Epoch 24 | train_loss=0.7592 | val_loss=1.2546 | val_f1_mean=0.1120 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.046997,0.058106,0.072126,0.09694,0.024815,0.105049,0.079993,0.020713,0.094282,0.027467,...,0.071035,0.154071,0.178323,0.06102,0.091464,0.079053,0.325519,0.057029,0.146037,0.131489

  → Сохранена лучшая модель (mean F1=0.1120)

Epoch 25/100: 100%|██████████| 3929/3929 [00:20<00:00, 187.81it/s, loss=0.5943]

Epoch 25 | train_loss=0.7500 | val_loss=1.2640 | val_f1_mean=0.1127 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.059771,0.056051,0.071781,0.103956,0.027962,0.104814,0.08484,0.01913,0.090498,0.03101,...,0.069799,0.141585,0.178324,0.065491,0.095269,0.079793,0.333104,0.056238,0.143248,0.125564

  → Сохранена лучшая модель (mean F1=0.1127)

Epoch 26/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.30it/s, loss=1.4945]

Epoch 26 | train_loss=0.7329 | val_loss=1.3121 | val_f1_mean=0.1117 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.060813,0.056761,0.072309,0.098712,0.031254,0.104234,0.110542,0.019367,0.086224,0.030836,...,0.074379,0.16016,0.173424,0.063355,0.088011,0.073015,0.321814,0.063778,0.143623,0.137259

Epoch 27/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.88it/s, loss=0.6059]

Epoch 27 | train_loss=0.7205 | val_loss=1.3263 | val_f1_mean=0.1150 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.061129,0.067042,0.073462,0.096941,0.030293,0.102544,0.104617,0.019348,0.087057,0.027965,...,0.07603,0.153278,0.178176,0.058408,0.088597,0.085555,0.325987,0.06444,0.153532,0.143111

  → Сохранена лучшая модель (mean F1=0.1150)

Epoch 28/100: 100%|██████████| 3929/3929 [00:21<00:00, 185.80it/s, loss=1.0758]

Epoch 28 | train_loss=0.7094 | val_loss=1.3748 | val_f1_mean=0.1170 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.061779,0.060821,0.073174,0.108826,0.031686,0.102983,0.116265,0.02179,0.091432,0.031546,...,0.076539,0.168693,0.178302,0.064552,0.090826,0.08843,0.331508,0.063759,0.168603,0.146781

  → Сохранена лучшая модель (mean F1=0.1170)

Epoch 29/100: 100%|██████████| 3929/3929 [00:20<00:00, 196.07it/s, loss=0.4906]

Epoch 29 | train_loss=0.6988 | val_loss=1.3727 | val_f1_mean=0.1169 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.057958,0.059364,0.073341,0.111244,0.032549,0.100428,0.110977,0.020047,0.092736,0.029819,...,0.077578,0.162487,0.181723,0.065085,0.094121,0.085704,0.333187,0.063578,0.169828,0.127079

Epoch 30/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.61it/s, loss=0.5737]

Epoch 30 | train_loss=0.6855 | val_loss=1.3165 | val_f1_mean=0.1147 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.062018,0.057109,0.075022,0.098394,0.03073,0.108909,0.103702,0.02134,0.097882,0.033591,...,0.070599,0.142857,0.1833,0.065072,0.103608,0.085725,0.340262,0.066917,0.151353,0.14538

Epoch 31/100: 100%|██████████| 3929/3929 [00:21<00:00, 186.60it/s, loss=0.5917]

Epoch 31 | train_loss=0.6761 | val_loss=1.3877 | val_f1_mean=0.1179 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.060744,0.061114,0.073886,0.108706,0.038828,0.10988,0.115693,0.021128,0.098682,0.034304,...,0.07944,0.15321,0.178908,0.065994,0.101784,0.1006,0.333464,0.068414,0.157749,0.134905

  → Сохранена лучшая модель (mean F1=0.1179)

Epoch 32/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.43it/s, loss=0.5617]

Epoch 32 | train_loss=0.6641 | val_loss=1.3562 | val_f1_mean=0.1171 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.057343,0.058849,0.074164,0.102922,0.03116,0.10926,0.103993,0.020806,0.105316,0.032217,...,0.072243,0.141961,0.181383,0.062908,0.10191,0.091365,0.334757,0.066331,0.137705,0.136619

Epoch 33/100: 100%|██████████| 3929/3929 [00:20<00:00, 196.40it/s, loss=0.6439]

Epoch 33 | train_loss=0.6535 | val_loss=1.4253 | val_f1_mean=0.1205 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.058687,0.070395,0.074001,0.105074,0.036776,0.108278,0.11437,0.022828,0.097274,0.037844,...,0.079248,0.15784,0.184029,0.072846,0.098437,0.115431,0.330889,0.069583,0.161012,0.137798

  → Сохранена лучшая модель (mean F1=0.1205)

Epoch 34/100: 100%|██████████| 3929/3929 [00:21<00:00, 185.84it/s, loss=0.6822]

Epoch 34 | train_loss=0.6478 | val_loss=1.4566 | val_f1_mean=0.1175 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.062147,0.061664,0.073586,0.105983,0.037722,0.108787,0.111292,0.019677,0.098559,0.032638,...,0.075386,0.171239,0.188123,0.068437,0.100258,0.08516,0.340989,0.065517,0.1648,0.158918

Epoch 35/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.86it/s, loss=0.5538]

Epoch 35 | train_loss=0.6343 | val_loss=1.4721 | val_f1_mean=0.1215 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.058722,0.0669,0.07473,0.113029,0.033446,0.110849,0.116181,0.020967,0.094129,0.031513,...,0.081633,0.176495,0.178038,0.062296,0.098937,0.102079,0.334379,0.063435,0.181374,0.135862

  → Сохранена лучшая модель (mean F1=0.1215)

Epoch 36/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.35it/s, loss=0.4942]

Epoch 36 | train_loss=0.6263 | val_loss=1.4898 | val_f1_mean=0.1212 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.060807,0.065308,0.076281,0.109462,0.036224,0.108812,0.110033,0.021855,0.105502,0.034188,...,0.076674,0.150696,0.194713,0.062965,0.108433,0.11167,0.348632,0.064783,0.162141,0.153323

Epoch 37/100: 100%|██████████| 3929/3929 [00:20<00:00, 189.05it/s, loss=0.7643]

Epoch 37 | train_loss=0.6194 | val_loss=1.4965 | val_f1_mean=0.1225 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.05871,0.070734,0.075931,0.114363,0.034233,0.107772,0.118184,0.023683,0.102161,0.032177,...,0.087137,0.174785,0.179684,0.069542,0.104423,0.105104,0.340367,0.066287,0.168224,0.149185

  → Сохранена лучшая модель (mean F1=0.1225)

Epoch 38/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.14it/s, loss=0.8559]

Epoch 38 | train_loss=0.6125 | val_loss=1.5471 | val_f1_mean=0.1235 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.07462,0.073784,0.077657,0.116819,0.038115,0.108484,0.130473,0.026347,0.102925,0.03835,...,0.081798,0.175889,0.18231,0.06363,0.102213,0.123063,0.334507,0.058844,0.156017,0.165844

  → Сохранена лучшая модель (mean F1=0.1235)

Epoch 39/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.37it/s, loss=0.4888]

Epoch 39 | train_loss=0.6026 | val_loss=1.5818 | val_f1_mean=0.1256 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.070274,0.073997,0.077887,0.119229,0.038156,0.110243,0.12466,0.025904,0.104532,0.03564,...,0.094625,0.179072,0.185242,0.068765,0.101031,0.126742,0.338018,0.068333,0.185437,0.158416

  → Сохранена лучшая модель (mean F1=0.1256)

Epoch 40/100: 100%|██████████| 3929/3929 [00:20<00:00, 191.39it/s, loss=0.5943]

Epoch 40 | train_loss=0.5942 | val_loss=1.4793 | val_f1_mean=0.1246 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.06568,0.072889,0.07906,0.120252,0.036434,0.111102,0.121751,0.0238,0.105731,0.035697,...,0.08153,0.164557,0.18512,0.065531,0.107257,0.102956,0.346984,0.064482,0.165842,0.158379

Epoch 41/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.80it/s, loss=0.5626]

Epoch 41 | train_loss=0.5889 | val_loss=1.5174 | val_f1_mean=0.1259 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.068132,0.070883,0.078329,0.110368,0.035253,0.108974,0.123524,0.024662,0.103246,0.037214,...,0.089767,0.174161,0.184203,0.06729,0.103937,0.107909,0.340107,0.071577,0.165649,0.165174

  → Сохранена лучшая модель (mean F1=0.1259)

Epoch 42/100: 100%|██████████| 3929/3929 [00:20<00:00, 196.34it/s, loss=0.5879]

Epoch 42 | train_loss=0.5817 | val_loss=1.5467 | val_f1_mean=0.1264 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.060094,0.065868,0.074625,0.115392,0.035873,0.114755,0.123373,0.025949,0.107088,0.035714,...,0.082737,0.169947,0.194467,0.066647,0.106719,0.110117,0.346907,0.067235,0.167418,0.151073

  → Сохранена лучшая модель (mean F1=0.1264)

Epoch 43/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.50it/s, loss=0.5711]

Epoch 43 | train_loss=0.5705 | val_loss=1.5765 | val_f1_mean=0.1256 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.069837,0.072905,0.078991,0.122857,0.038398,0.113307,0.125834,0.022931,0.107494,0.035885,...,0.087476,0.171878,0.185878,0.066186,0.106312,0.11115,0.343903,0.063364,0.177552,0.165503

Epoch 44/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.24it/s, loss=0.6567]

Epoch 44 | train_loss=0.5639 | val_loss=1.6155 | val_f1_mean=0.1293 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.075446,0.071487,0.07953,0.119444,0.040334,0.109126,0.133728,0.024506,0.111777,0.043369,...,0.097388,0.169724,0.195446,0.070396,0.1056,0.120416,0.349037,0.074307,0.175126,0.16156

  → Сохранена лучшая модель (mean F1=0.1293)

Epoch 45/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.67it/s, loss=0.4906]

Epoch 45 | train_loss=0.5543 | val_loss=1.6440 | val_f1_mean=0.1280 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.070617,0.082735,0.078316,0.122021,0.039209,0.112972,0.126094,0.023838,0.105212,0.042471,...,0.08969,0.182055,0.1877,0.066412,0.113231,0.125236,0.344981,0.070503,0.174171,0.161621

Epoch 46/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.24it/s, loss=0.4002]

Epoch 46 | train_loss=0.5484 | val_loss=1.6533 | val_f1_mean=0.1304 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.071475,0.072591,0.079547,0.125305,0.039504,0.112826,0.133202,0.024463,0.115318,0.039864,...,0.094677,0.177923,0.193172,0.067465,0.110855,0.119403,0.343808,0.069643,0.172421,0.161538

  → Сохранена лучшая модель (mean F1=0.1304)

Epoch 47/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.89it/s, loss=0.4973]

Epoch 47 | train_loss=0.5419 | val_loss=1.6002 | val_f1_mean=0.1293 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.066481,0.070654,0.081464,0.121451,0.037787,0.118104,0.119035,0.024995,0.119407,0.041733,...,0.083825,0.153971,0.189968,0.065836,0.117392,0.113931,0.345588,0.070683,0.160994,0.161305

Epoch 48/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.06it/s, loss=0.7146]

Epoch 48 | train_loss=0.5364 | val_loss=1.7436 | val_f1_mean=0.1331 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.078802,0.074545,0.079246,0.127357,0.04066,0.113478,0.141059,0.022309,0.104694,0.041353,...,0.091297,0.190716,0.191535,0.074257,0.101803,0.12673,0.349016,0.071636,0.198418,0.179846

  → Сохранена лучшая модель (mean F1=0.1331)

Epoch 49/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.41it/s, loss=0.4911]

Epoch 49 | train_loss=0.5297 | val_loss=1.6663 | val_f1_mean=0.1322 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.065438,0.073279,0.079239,0.120923,0.03974,0.112646,0.130978,0.021257,0.119221,0.04624,...,0.097038,0.1797,0.191569,0.068316,0.115999,0.123579,0.352563,0.069728,0.190282,0.165583

Epoch 50/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.78it/s, loss=1.0282]

Epoch 50 | train_loss=0.5255 | val_loss=1.6990 | val_f1_mean=0.1327 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.063745,0.074357,0.079013,0.124395,0.041845,0.116854,0.132653,0.019516,0.110506,0.03697,...,0.096563,0.181546,0.191096,0.065713,0.112053,0.122944,0.347283,0.069111,0.185632,0.170631

Epoch 51/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.55it/s, loss=0.7182]

Epoch 51 | train_loss=0.5162 | val_loss=1.7995 | val_f1_mean=0.1343 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.065141,0.078689,0.078589,0.126323,0.04286,0.112846,0.144273,0.021545,0.10565,0.039332,...,0.091493,0.199435,0.191479,0.066943,0.10417,0.133465,0.349753,0.069144,0.192612,0.176005

  → Сохранена лучшая модель (mean F1=0.1343)

Epoch 52/100: 100%|██████████| 3929/3929 [00:19<00:00, 202.73it/s, loss=0.4319]

Epoch 52 | train_loss=0.5096 | val_loss=1.8207 | val_f1_mean=0.1320 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.078543,0.086995,0.082855,0.12737,0.040703,0.112643,0.144892,0.023319,0.108434,0.048714,...,0.095451,0.201706,0.190389,0.063745,0.106061,0.144134,0.336659,0.06755,0.189146,0.172075

Epoch 53/100: 100%|██████████| 3929/3929 [00:21<00:00, 186.48it/s, loss=0.6092]

Epoch 53 | train_loss=0.5033 | val_loss=1.8144 | val_f1_mean=0.1333 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.073226,0.07864,0.082579,0.125698,0.041779,0.115721,0.148359,0.021372,0.117334,0.041766,...,0.086498,0.194383,0.192263,0.069869,0.11498,0.134746,0.347196,0.071409,0.190722,0.173694

Epoch 54/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.48it/s, loss=0.6751]

Epoch 54 | train_loss=0.4979 | val_loss=1.8079 | val_f1_mean=0.1351 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.077014,0.080057,0.078421,0.125944,0.04304,0.115349,0.144609,0.022517,0.114603,0.046536,...,0.092915,0.185892,0.19819,0.062277,0.11082,0.122319,0.350788,0.070517,0.184104,0.17494

  → Сохранена лучшая модель (mean F1=0.1351)

Epoch 55/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.51it/s, loss=0.5791]

Epoch 55 | train_loss=0.4915 | val_loss=1.7911 | val_f1_mean=0.1360 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.075595,0.075587,0.085135,0.126289,0.040889,0.11687,0.144772,0.023736,0.11978,0.042464,...,0.093397,0.186087,0.197488,0.06827,0.116561,0.126417,0.357121,0.066591,0.19383,0.176081

  → Сохранена лучшая модель (mean F1=0.1360)

Epoch 56/100: 100%|██████████| 3929/3929 [00:21<00:00, 186.40it/s, loss=0.4509]

Epoch 56 | train_loss=0.4874 | val_loss=1.8868 | val_f1_mean=0.1363 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.082583,0.07594,0.083182,0.130499,0.044125,0.11188,0.154383,0.021776,0.117821,0.044548,...,0.094842,0.198219,0.197481,0.068116,0.116115,0.139691,0.355473,0.070312,0.193319,0.176941

  → Сохранена лучшая модель (mean F1=0.1363)

Epoch 57/100: 100%|██████████| 3929/3929 [00:19<00:00, 200.73it/s, loss=0.2975]

Epoch 57 | train_loss=0.4819 | val_loss=1.8787 | val_f1_mean=0.1376 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.073723,0.082565,0.081456,0.1333,0.045728,0.117294,0.146314,0.024419,0.112441,0.048219,...,0.100159,0.196567,0.19906,0.066211,0.113183,0.14127,0.347731,0.073816,0.200758,0.183784

  → Сохранена лучшая модель (mean F1=0.1376)

Epoch 58/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.77it/s, loss=0.4428]

Epoch 58 | train_loss=0.4788 | val_loss=1.8318 | val_f1_mean=0.1359 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.072534,0.085769,0.084201,0.138223,0.041354,0.116899,0.145753,0.022902,0.119102,0.042325,...,0.09181,0.189765,0.189196,0.064516,0.119628,0.127669,0.350624,0.072044,0.189098,0.170745

Epoch 59/100: 100%|██████████| 3929/3929 [00:20<00:00, 188.33it/s, loss=0.3325]

Epoch 59 | train_loss=0.4745 | val_loss=1.8270 | val_f1_mean=0.1374 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.068778,0.083361,0.083303,0.128249,0.040215,0.116672,0.137346,0.026028,0.128976,0.04045,...,0.09313,0.171606,0.202669,0.067176,0.124706,0.119235,0.360451,0.068155,0.189888,0.17408

Epoch 60/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.37it/s, loss=0.3103]

Epoch 60 | train_loss=0.4661 | val_loss=1.9080 | val_f1_mean=0.1378 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.079238,0.073389,0.08709,0.125893,0.048739,0.118475,0.139593,0.024561,0.133215,0.050887,...,0.091001,0.182603,0.19733,0.066829,0.130905,0.125547,0.360992,0.072903,0.187532,0.175568

  → Сохранена лучшая модель (mean F1=0.1378)

Epoch 61/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.97it/s, loss=0.3828]

Epoch 61 | train_loss=0.4613 | val_loss=1.9448 | val_f1_mean=0.1387 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.077772,0.08374,0.081308,0.132983,0.045221,0.114011,0.141316,0.02593,0.125545,0.04973,...,0.09764,0.185877,0.202814,0.062415,0.121513,0.141156,0.362337,0.076864,0.184865,0.173816

  → Сохранена лучшая модель (mean F1=0.1387)

Epoch 62/100: 100%|██████████| 3929/3929 [00:20<00:00, 189.88it/s, loss=0.7812]

Epoch 62 | train_loss=0.4586 | val_loss=1.9404 | val_f1_mean=0.1391 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.080629,0.07585,0.080314,0.137335,0.051209,0.11112,0.14127,0.024617,0.127509,0.048142,...,0.093679,0.189088,0.209462,0.065841,0.123711,0.131171,0.360429,0.072023,0.198723,0.184884

  → Сохранена лучшая модель (mean F1=0.1391)

Epoch 63/100: 100%|██████████| 3929/3929 [00:19<00:00, 200.92it/s, loss=0.7296]

Epoch 63 | train_loss=0.4514 | val_loss=1.9068 | val_f1_mean=0.1391 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.074412,0.08969,0.082205,0.133836,0.04354,0.119968,0.156429,0.025917,0.118037,0.046797,...,0.100855,0.198918,0.191925,0.065911,0.118331,0.141439,0.349722,0.06866,0.200443,0.185446

Epoch 64/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.48it/s, loss=0.3779]

Epoch 64 | train_loss=0.4469 | val_loss=1.9813 | val_f1_mean=0.1412 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.080081,0.088943,0.083411,0.131613,0.048013,0.119642,0.146435,0.024698,0.128191,0.05,...,0.098794,0.194175,0.202607,0.070256,0.130747,0.144158,0.352466,0.075174,0.184339,0.172547

  → Сохранена лучшая модель (mean F1=0.1412)

Epoch 65/100: 100%|██████████| 3929/3929 [00:20<00:00, 192.01it/s, loss=0.3335]

Epoch 65 | train_loss=0.4453 | val_loss=1.9387 | val_f1_mean=0.1409 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.075636,0.088969,0.08216,0.133143,0.046792,0.12022,0.147876,0.026808,0.126976,0.04774,...,0.09817,0.189865,0.201667,0.064884,0.128246,0.130041,0.356134,0.072745,0.197656,0.179243

Epoch 66/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.35it/s, loss=0.7350]

Epoch 66 | train_loss=0.4385 | val_loss=2.0978 | val_f1_mean=0.1414 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.080513,0.086577,0.086864,0.142621,0.048461,0.113824,0.142392,0.02436,0.135501,0.055749,...,0.097577,0.193968,0.205012,0.069869,0.130057,0.136788,0.370087,0.078924,0.190652,0.177604

  → Сохранена лучшая модель (mean F1=0.1414)

Epoch 67/100: 100%|██████████| 3929/3929 [00:20<00:00, 196.32it/s, loss=0.5084]

Epoch 67 | train_loss=0.4362 | val_loss=1.9696 | val_f1_mean=0.1423 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.085853,0.087241,0.087268,0.135973,0.04776,0.122974,0.140811,0.02418,0.130982,0.049751,...,0.095392,0.188078,0.202356,0.063648,0.123918,0.129487,0.361113,0.072243,0.191602,0.194708

  → Сохранена лучшая модель (mean F1=0.1423)

Epoch 68/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.40it/s, loss=0.3634]

Epoch 68 | train_loss=0.4292 | val_loss=2.0702 | val_f1_mean=0.1424 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.083748,0.094306,0.088553,0.139214,0.047717,0.11623,0.149154,0.022078,0.11948,0.050526,...,0.10692,0.203453,0.201206,0.065884,0.11568,0.138137,0.355378,0.075377,0.198193,0.186788

  → Сохранена лучшая модель (mean F1=0.1424)

Epoch 69/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.95it/s, loss=0.2872]

Epoch 69 | train_loss=0.4260 | val_loss=2.0847 | val_f1_mean=0.1445 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.088439,0.091429,0.084055,0.139909,0.049551,0.112119,0.149101,0.026837,0.12313,0.050145,...,0.10828,0.200331,0.207909,0.065625,0.118534,0.142067,0.360456,0.071927,0.201613,0.19888

  → Сохранена лучшая модель (mean F1=0.1445)

Epoch 70/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.61it/s, loss=0.2818]

Epoch 70 | train_loss=0.4224 | val_loss=2.0399 | val_f1_mean=0.1429 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.084813,0.0912,0.087783,0.137744,0.04519,0.120161,0.149554,0.02472,0.117567,0.048793,...,0.101613,0.191065,0.203888,0.065402,0.117026,0.144928,0.350848,0.067925,0.198217,0.185088

Epoch 71/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.00it/s, loss=0.4136]

Epoch 71 | train_loss=0.4197 | val_loss=2.0776 | val_f1_mean=0.1441 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.092615,0.089026,0.089519,0.135875,0.049117,0.123671,0.152675,0.026657,0.132397,0.055293,...,0.09787,0.200556,0.205385,0.069749,0.13027,0.146896,0.355846,0.073929,0.199432,0.192818

Epoch 72/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.56it/s, loss=0.2450]

Epoch 72 | train_loss=0.4146 | val_loss=2.1469 | val_f1_mean=0.1448 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.098132,0.092368,0.085681,0.14494,0.049496,0.113633,0.154662,0.026174,0.116844,0.051056,...,0.108016,0.19924,0.206957,0.071133,0.114844,0.154934,0.353778,0.072193,0.205996,0.190671

  → Сохранена лучшая модель (mean F1=0.1448)

Epoch 73/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.09it/s, loss=0.3741]

Epoch 73 | train_loss=0.4112 | val_loss=2.0632 | val_f1_mean=0.1443 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.083745,0.0938,0.087208,0.140778,0.045301,0.120983,0.150382,0.023171,0.125275,0.048574,...,0.101167,0.195855,0.201949,0.067919,0.125091,0.139672,0.351816,0.074303,0.194175,0.184202

Epoch 74/100: 100%|██████████| 3929/3929 [00:19<00:00, 200.46it/s, loss=0.5901]

Epoch 74 | train_loss=0.4091 | val_loss=2.1089 | val_f1_mean=0.1449 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.084318,0.087625,0.088222,0.141949,0.04583,0.12004,0.150874,0.021965,0.133607,0.051712,...,0.101978,0.198995,0.21277,0.064804,0.132144,0.139758,0.362618,0.071868,0.200508,0.195464

  → Сохранена лучшая модель (mean F1=0.1449)

Epoch 75/100: 100%|██████████| 3929/3929 [00:20<00:00, 190.61it/s, loss=0.4190]

Epoch 75 | train_loss=0.4023 | val_loss=2.1633 | val_f1_mean=0.1450 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.088889,0.091308,0.0906,0.141978,0.046234,0.117001,0.153812,0.023229,0.130207,0.053625,...,0.106892,0.198969,0.20822,0.062558,0.127555,0.146764,0.360989,0.07604,0.197946,0.181928

  → Сохранена лучшая модель (mean F1=0.1450)

Epoch 76/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.80it/s, loss=0.3858]

Epoch 76 | train_loss=0.3988 | val_loss=2.0883 | val_f1_mean=0.1456 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.080925,0.088333,0.092448,0.141458,0.04368,0.12266,0.14314,0.02202,0.127929,0.044526,...,0.099846,0.186511,0.207218,0.068091,0.132793,0.135802,0.362852,0.073601,0.189057,0.187656

  → Сохранена лучшая модель (mean F1=0.1456)

Epoch 77/100: 100%|██████████| 3929/3929 [00:19<00:00, 202.06it/s, loss=0.2727]

Epoch 77 | train_loss=0.3988 | val_loss=2.1859 | val_f1_mean=0.1473 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.093441,0.090716,0.089491,0.146259,0.049686,0.122994,0.15747,0.025593,0.123583,0.050242,...,0.098573,0.203416,0.20646,0.06071,0.121773,0.153939,0.361254,0.078049,0.199943,0.204457

  → Сохранена лучшая модель (mean F1=0.1473)

Epoch 78/100: 100%|██████████| 3929/3929 [00:20<00:00, 189.90it/s, loss=0.2885]

Epoch 78 | train_loss=0.3946 | val_loss=2.1835 | val_f1_mean=0.1468 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.08864,0.084006,0.088746,0.1413,0.052038,0.119324,0.150229,0.023874,0.134401,0.052117,...,0.105474,0.203479,0.211152,0.066488,0.12865,0.141151,0.365066,0.07505,0.205585,0.194684

Epoch 79/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.60it/s, loss=0.3171]

Epoch 79 | train_loss=0.3915 | val_loss=2.1613 | val_f1_mean=0.1486 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.089459,0.084627,0.088423,0.143909,0.048504,0.12241,0.15235,0.025165,0.127625,0.0484,...,0.103994,0.197224,0.210442,0.067583,0.128517,0.143187,0.360662,0.072135,0.197898,0.202142

  → Сохранена лучшая модель (mean F1=0.1486)

Epoch 80/100: 100%|██████████| 3929/3929 [00:19<00:00, 204.82it/s, loss=0.3089]

Epoch 80 | train_loss=0.3892 | val_loss=2.2600 | val_f1_mean=0.1468 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.093688,0.105156,0.087111,0.146376,0.04439,0.114233,0.152338,0.024065,0.110034,0.047536,...,0.10859,0.214515,0.203818,0.061644,0.11572,0.147853,0.347997,0.075866,0.207573,0.202785

Epoch 81/100: 100%|██████████| 3929/3929 [00:20<00:00, 188.73it/s, loss=0.4081]

Epoch 81 | train_loss=0.3848 | val_loss=2.2070 | val_f1_mean=0.1479 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.087773,0.088323,0.08884,0.1444,0.051315,0.119269,0.154583,0.026377,0.132192,0.050929,...,0.102424,0.198611,0.214743,0.05934,0.130974,0.146886,0.363872,0.074972,0.203221,0.20202

Epoch 82/100: 100%|██████████| 3929/3929 [00:19<00:00, 200.76it/s, loss=0.5334]

Epoch 82 | train_loss=0.3811 | val_loss=2.2068 | val_f1_mean=0.1484 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.088762,0.088307,0.088718,0.144829,0.04834,0.12216,0.151888,0.025279,0.130182,0.048872,...,0.100172,0.199949,0.21277,0.063158,0.132532,0.139799,0.365916,0.078059,0.204545,0.199203

Epoch 83/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.94it/s, loss=0.3385]

Epoch 83 | train_loss=0.3804 | val_loss=2.2351 | val_f1_mean=0.1498 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.09967,0.087132,0.089772,0.143869,0.052559,0.119873,0.160584,0.02654,0.136787,0.05444,...,0.098826,0.198992,0.215698,0.068289,0.132088,0.141144,0.367568,0.075387,0.205585,0.206873

  → Сохранена лучшая модель (mean F1=0.1498)

Epoch 84/100: 100%|██████████| 3929/3929 [00:20<00:00, 190.15it/s, loss=0.3028]

Epoch 84 | train_loss=0.3758 | val_loss=2.2567 | val_f1_mean=0.1493 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.090961,0.093708,0.088694,0.143283,0.04675,0.118443,0.160371,0.024641,0.129874,0.054369,...,0.103861,0.209461,0.211363,0.062911,0.13033,0.142898,0.359411,0.079017,0.201978,0.203104

Epoch 85/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.49it/s, loss=0.3683]

Epoch 85 | train_loss=0.3738 | val_loss=2.2586 | val_f1_mean=0.1503 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.106383,0.089096,0.092851,0.144263,0.05017,0.122238,0.151836,0.023693,0.132704,0.056537,...,0.100846,0.204792,0.210465,0.067715,0.132274,0.140725,0.362611,0.079654,0.200842,0.212251

  → Сохранена лучшая модель (mean F1=0.1503)

Epoch 86/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.96it/s, loss=0.4882]

Epoch 86 | train_loss=0.3724 | val_loss=2.2617 | val_f1_mean=0.1502 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.107411,0.094159,0.092878,0.145692,0.052863,0.122553,0.151793,0.024233,0.129228,0.054615,...,0.100701,0.203046,0.209969,0.065448,0.133094,0.135744,0.363237,0.07996,0.204117,0.208288

Epoch 87/100: 100%|██████████| 3929/3929 [00:20<00:00, 189.20it/s, loss=0.4138]

Epoch 87 | train_loss=0.3686 | val_loss=2.2736 | val_f1_mean=0.1505 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.107843,0.093216,0.089608,0.143011,0.050796,0.122368,0.158858,0.02358,0.132743,0.053333,...,0.102082,0.205598,0.214478,0.063274,0.130792,0.140322,0.362416,0.076564,0.20726,0.207321

  → Сохранена лучшая модель (mean F1=0.1505)

Epoch 88/100: 100%|██████████| 3929/3929 [00:19<00:00, 200.72it/s, loss=0.3476]

Epoch 88 | train_loss=0.3681 | val_loss=2.2792 | val_f1_mean=0.1505 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.101948,0.096892,0.091051,0.147051,0.049617,0.12146,0.151413,0.026568,0.131947,0.052138,...,0.107465,0.210888,0.214954,0.062036,0.13113,0.150599,0.362254,0.077792,0.201223,0.204616

Epoch 89/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.39it/s, loss=0.4623]

Epoch 89 | train_loss=0.3665 | val_loss=2.2977 | val_f1_mean=0.1515 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.108742,0.092617,0.091026,0.145066,0.050409,0.121134,0.15419,0.02566,0.131548,0.058988,...,0.104909,0.205906,0.214513,0.066986,0.131966,0.146659,0.365772,0.078185,0.206024,0.208165

  → Сохранена лучшая модель (mean F1=0.1515)

Epoch 90/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.01it/s, loss=0.3570]

Epoch 90 | train_loss=0.3654 | val_loss=2.3695 | val_f1_mean=0.1514 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.103389,0.090523,0.091891,0.14665,0.053454,0.116881,0.155485,0.02389,0.141797,0.05498,...,0.105227,0.205231,0.216703,0.062246,0.138303,0.146999,0.372405,0.080636,0.19697,0.202594

Epoch 91/100: 100%|██████████| 3929/3929 [00:19<00:00, 202.18it/s, loss=0.5662]

Epoch 91 | train_loss=0.3625 | val_loss=2.3107 | val_f1_mean=0.1510 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.098226,0.096975,0.090596,0.147583,0.05167,0.124848,0.153003,0.025181,0.133353,0.055219,...,0.105688,0.200457,0.21271,0.062123,0.130747,0.147374,0.360229,0.078628,0.201891,0.204685

Epoch 92/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.58it/s, loss=0.2231]

Epoch 92 | train_loss=0.3608 | val_loss=2.3062 | val_f1_mean=0.1513 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.10421,0.095112,0.088238,0.14467,0.051637,0.122343,0.155914,0.023117,0.130624,0.050993,...,0.104152,0.20805,0.215774,0.062813,0.134787,0.147849,0.3642,0.080083,0.200059,0.208868

Epoch 93/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.60it/s, loss=0.2369]

Epoch 93 | train_loss=0.3579 | val_loss=2.3250 | val_f1_mean=0.1519 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.105335,0.091071,0.090909,0.147604,0.053376,0.122915,0.157883,0.025526,0.137166,0.053449,...,0.105556,0.202786,0.215686,0.060554,0.136497,0.145902,0.368686,0.077894,0.206607,0.205861

  → Сохранена лучшая модель (mean F1=0.1519)

Epoch 94/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.86it/s, loss=0.3414]

Epoch 94 | train_loss=0.3568 | val_loss=2.3018 | val_f1_mean=0.1513 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.097179,0.09379,0.09182,0.145464,0.052045,0.124063,0.15197,0.022904,0.136701,0.052725,...,0.101509,0.201349,0.215584,0.05978,0.13971,0.142082,0.366345,0.077227,0.201243,0.202869

Epoch 95/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.77it/s, loss=0.3240]

Epoch 95 | train_loss=0.3541 | val_loss=2.3430 | val_f1_mean=0.1525 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.107335,0.093259,0.091878,0.146308,0.056338,0.124547,0.154276,0.025641,0.138943,0.059455,...,0.102737,0.20675,0.216307,0.062139,0.138528,0.149944,0.36858,0.078994,0.201932,0.207418

  → Сохранена лучшая модель (mean F1=0.1525)

Epoch 96/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.46it/s, loss=0.2966]

Epoch 96 | train_loss=0.3539 | val_loss=2.3315 | val_f1_mean=0.1523 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.104635,0.09167,0.091079,0.146348,0.052684,0.123486,0.156871,0.023791,0.137734,0.056383,...,0.102668,0.202928,0.217822,0.064884,0.139407,0.146395,0.368035,0.079844,0.200176,0.208046

Epoch 97/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.56it/s, loss=0.2842]

Epoch 97 | train_loss=0.3539 | val_loss=2.3363 | val_f1_mean=0.1520 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.09879,0.097978,0.09128,0.146948,0.052136,0.121304,0.15712,0.021946,0.133233,0.052478,...,0.106608,0.210868,0.216121,0.063492,0.135143,0.144791,0.364033,0.08071,0.199814,0.208966

Epoch 98/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.40it/s, loss=0.2562]

Epoch 98 | train_loss=0.3536 | val_loss=2.3250 | val_f1_mean=0.1521 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.101249,0.093085,0.091896,0.1465,0.052976,0.123575,0.153947,0.022857,0.135123,0.054484,...,0.104752,0.205729,0.21689,0.06286,0.135769,0.144009,0.36661,0.079253,0.201569,0.20874

Epoch 99/100: 100%|██████████| 3929/3929 [00:19<00:00, 203.02it/s, loss=0.2736]

Epoch 99 | train_loss=0.3516 | val_loss=2.3463 | val_f1_mean=0.1524 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.104131,0.095413,0.092678,0.14726,0.054795,0.122018,0.157108,0.023059,0.132417,0.055194,...,0.106744,0.205969,0.215652,0.061846,0.135493,0.145816,0.3652,0.080245,0.199507,0.212344

Epoch 100/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.12it/s, loss=0.3046]

Epoch 100 | train_loss=0.3514 | val_loss=2.3460 | val_f1_mean=0.1527 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.105189,0.094096,0.09191,0.148685,0.055405,0.122301,0.156801,0.023121,0.133233,0.055491,...,0.106055,0.206915,0.215204,0.060909,0.135058,0.147186,0.365173,0.080461,0.203287,0.211867

  → Сохранена лучшая модель (mean F1=0.1527)

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.105189,0.094096,0.09191,0.148685,0.055405,0.122301,0.156801,0.023121,0.133233,0.055491,...,0.106055,0.206915,0.215204,0.060909,0.135058,0.147186,0.365173,0.080461,0.203287,0.211867

In [44]:
from huggingface_hub import snapshot_download

print("📥 Скачивание модели...")
model_path = snapshot_download(
    repo_id=MODEL_NAME,
    local_dir=MODEL_DIR,
)

📥 Скачивание модели...

Fetching 13 files: 100%|██████████| 13/13 [00:00<00:00, 777.98it/s]

In [15]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR, num_labels=len(le.categories_[0]), local_files_only=True)
model.to(DEVICE)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 6722.68it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: models/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=42, bias=True)
  )
)

In [16]:
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = AdamW(model.parameters(), lr=LR, weight_decay=0.01)
model.to(DEVICE)

training(
    model=model,
    train_data_loader=train_dl,
    val_data_loader=val_dl,
    optimizer=optimizer,
    epoches=EPOCHS,
    criterion=criterion,
    tokenizator=le,
    accum_steps=ACCUM_STEPS,
    warmup_frac=WARMUP_FRAC,
    device=DEVICE,
    save_path=SAVE_PATH,
    )

Epoch 1/100: 100%|██████████| 3929/3929 [18:37<00:00,  3.52it/s, loss=0.9710]

Epoch 1 | train_loss=1.2783 | val_loss=0.9641 | val_f1_mean=0.1310 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.080034,0.04,0.084998,0.211969,0.031055,0.110793,0.10535,0.063382,0.092299,0.043188,...,0.07318,0.118584,0.304443,0.030357,0.110103,0.096288,0.399952,0.080255,0.095917,0.069435

  → Сохранена лучшая модель (mean F1=0.1310)

Epoch 2/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.7052]

Epoch 2 | train_loss=0.8219 | val_loss=0.6629 | val_f1_mean=0.2311 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.161605,0.075773,0.13642,0.270937,0.119068,0.163903,0.279406,0.11623,0.271117,0.114662,...,0.13804,0.305347,0.46135,0.059483,0.263761,0.135342,0.584459,0.108892,0.2444,0.181176

  → Сохранена лучшая модель (mean F1=0.2311)

Epoch 3/100: 100%|██████████| 3929/3929 [18:24<00:00,  3.56it/s, loss=0.3660]

Epoch 3 | train_loss=0.5985 | val_loss=0.4900 | val_f1_mean=0.3463 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.273504,0.220355,0.194107,0.427619,0.159099,0.299824,0.331041,0.22963,0.430769,0.190178,...,0.355301,0.319505,0.728451,0.096841,0.520176,0.213626,0.669071,0.185836,0.27489,0.211375

  → Сохранена лучшая модель (mean F1=0.3463)

Epoch 4/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.5434]

Epoch 4 | train_loss=0.4427 | val_loss=0.3784 | val_f1_mean=0.3959 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.210108,0.175966,0.322224,0.422462,0.233795,0.418729,0.385405,0.214483,0.474866,0.20921,...,0.427548,0.324586,0.778535,0.115385,0.547977,0.311097,0.757438,0.249179,0.276572,0.209758

  → Сохранена лучшая модель (mean F1=0.3959)

Epoch 5/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.56it/s, loss=0.2966]

Epoch 5 | train_loss=0.3388 | val_loss=0.3138 | val_f1_mean=0.4746 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.336232,0.260733,0.39349,0.466814,0.343399,0.488783,0.456612,0.308905,0.525316,0.308355,...,0.496173,0.385448,0.849139,0.146452,0.615117,0.368681,0.814534,0.296481,0.342857,0.335956

  → Сохранена лучшая модель (mean F1=0.4746)

Epoch 6/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.1732]

Epoch 6 | train_loss=0.2702 | val_loss=0.2727 | val_f1_mean=0.4728 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.220163,0.314465,0.345119,0.465166,0.285519,0.443996,0.450714,0.318361,0.507985,0.21729,...,0.386254,0.453263,0.829439,0.173884,0.670113,0.34188,0.807889,0.31481,0.407697,0.38435

Epoch 7/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.2293]

Epoch 7 | train_loss=0.2186 | val_loss=0.2575 | val_f1_mean=0.5332 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.422619,0.498969,0.43099,0.455598,0.334668,0.514623,0.448993,0.551524,0.583736,0.291959,...,0.484848,0.505519,0.856948,0.196108,0.662953,0.338502,0.850277,0.352846,0.45192,0.509474

  → Сохранена лучшая модель (mean F1=0.5332)

Epoch 8/100: 100%|██████████| 3929/3929 [18:24<00:00,  3.56it/s, loss=0.0748]

Epoch 8 | train_loss=0.1806 | val_loss=0.2735 | val_f1_mean=0.5734 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.595469,0.601523,0.551994,0.579629,0.375345,0.508823,0.53843,0.692737,0.550082,0.35796,...,0.575322,0.470667,0.865699,0.231429,0.754255,0.460418,0.828029,0.33681,0.407348,0.456807

  → Сохранена лучшая модель (mean F1=0.5734)

Epoch 9/100: 100%|██████████| 3929/3929 [18:24<00:00,  3.56it/s, loss=0.2143]

Epoch 9 | train_loss=0.1513 | val_loss=0.2749 | val_f1_mean=0.5914 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.62,0.665698,0.545144,0.560827,0.430571,0.60283,0.515314,0.705179,0.771446,0.323607,...,0.515831,0.461941,0.85624,0.235014,0.753871,0.467327,0.875048,0.414997,0.407097,0.520127

  → Сохранена лучшая модель (mean F1=0.5914)

Epoch 10/100: 100%|██████████| 3929/3929 [18:24<00:00,  3.56it/s, loss=0.4881]

Epoch 10 | train_loss=0.1285 | val_loss=0.2757 | val_f1_mean=0.5879 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.536965,0.522388,0.481132,0.47721,0.370714,0.508977,0.475381,0.667904,0.654382,0.352227,...,0.4884,0.514474,0.878745,0.220376,0.767316,0.419341,0.850343,0.38264,0.453131,0.524987

Epoch 11/100: 100%|██████████| 3929/3929 [18:24<00:00,  3.56it/s, loss=0.0604]

Epoch 11 | train_loss=0.1097 | val_loss=0.3124 | val_f1_mean=0.6283 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.60793,0.619608,0.542201,0.59596,0.478203,0.56854,0.508692,0.58805,0.592593,0.472879,...,0.674677,0.528,0.845848,0.29368,0.795493,0.475198,0.83702,0.473988,0.470904,0.564761

  → Сохранена лучшая модель (mean F1=0.6283)

Epoch 12/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0784]

Epoch 12 | train_loss=0.0922 | val_loss=0.3520 | val_f1_mean=0.6442 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.691517,0.662808,0.564789,0.56245,0.478431,0.655667,0.557876,0.694444,0.739741,0.439898,...,0.610169,0.508919,0.887211,0.31451,0.822628,0.515873,0.82483,0.526267,0.460288,0.588024

  → Сохранена лучшая модель (mean F1=0.6442)

Epoch 13/100: 100%|██████████| 3929/3929 [18:24<00:00,  3.56it/s, loss=0.0247]

Epoch 13 | train_loss=0.0782 | val_loss=0.3745 | val_f1_mean=0.6642 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.636051,0.579462,0.602167,0.597537,0.565149,0.636578,0.5884,0.650264,0.780073,0.49635,...,0.703527,0.537601,0.896783,0.403902,0.832038,0.506596,0.848236,0.494098,0.466767,0.606023

  → Сохранена лучшая модель (mean F1=0.6642)

Epoch 14/100: 100%|██████████| 3929/3929 [18:26<00:00,  3.55it/s, loss=0.0118]

Epoch 14 | train_loss=0.0665 | val_loss=0.4112 | val_f1_mean=0.6726 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.699482,0.723748,0.605942,0.624211,0.424173,0.653479,0.613949,0.742597,0.8,0.488827,...,0.696824,0.527757,0.862469,0.362563,0.843197,0.55121,0.885974,0.458919,0.460725,0.566569

  → Сохранена лучшая модель (mean F1=0.6726)

Epoch 15/100: 100%|██████████| 3929/3929 [18:24<00:00,  3.56it/s, loss=0.0485]

Epoch 15 | train_loss=0.0579 | val_loss=0.4519 | val_f1_mean=0.6873 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.652015,0.576923,0.63744,0.625767,0.496552,0.59125,0.604993,0.624374,0.845593,0.579041,...,0.677036,0.548195,0.882339,0.377325,0.825547,0.572554,0.872538,0.521277,0.474187,0.667147

  → Сохранена лучшая модель (mean F1=0.6873)

Epoch 16/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.3978]

Epoch 16 | train_loss=0.0513 | val_loss=0.5366 | val_f1_mean=0.7001 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.70235,0.658892,0.57122,0.628173,0.511834,0.648763,0.643703,0.689524,0.815094,0.598485,...,0.685767,0.583878,0.898783,0.472303,0.831923,0.536131,0.893363,0.537799,0.512129,0.65269

  → Сохранена лучшая модель (mean F1=0.7001)

Epoch 17/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0356]

Epoch 17 | train_loss=0.0452 | val_loss=0.5405 | val_f1_mean=0.7079 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.720222,0.696594,0.635443,0.642969,0.58843,0.665696,0.639745,0.75594,0.860622,0.578947,...,0.693107,0.555556,0.899854,0.433107,0.86087,0.594183,0.901484,0.569064,0.506394,0.619446

  → Сохранена лучшая модель (mean F1=0.7079)

Epoch 18/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0182]

Epoch 18 | train_loss=0.0408 | val_loss=0.5676 | val_f1_mean=0.7118 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.729805,0.726351,0.624438,0.660697,0.623188,0.673754,0.649619,0.745614,0.851092,0.560847,...,0.726702,0.599643,0.897274,0.34434,0.882623,0.581152,0.884051,0.530521,0.500423,0.671033

  → Сохранена лучшая модель (mean F1=0.7118)

Epoch 19/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0271]

Epoch 19 | train_loss=0.0352 | val_loss=0.6495 | val_f1_mean=0.7206 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.732673,0.731707,0.592871,0.630911,0.570962,0.710092,0.668643,0.789082,0.851035,0.592445,...,0.720632,0.59684,0.881119,0.476712,0.865519,0.606432,0.892608,0.572911,0.530688,0.711891

  → Сохранена лучшая модель (mean F1=0.7206)

Epoch 20/100: 100%|██████████| 3929/3929 [18:26<00:00,  3.55it/s, loss=0.0460]

Epoch 20 | train_loss=0.0319 | val_loss=0.6748 | val_f1_mean=0.7246 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.747126,0.714514,0.689196,0.660278,0.595978,0.686556,0.648407,0.773148,0.848363,0.637931,...,0.722493,0.604738,0.901825,0.452037,0.846344,0.625664,0.897738,0.58209,0.534754,0.693414

  → Сохранена лучшая модель (mean F1=0.7246)

Epoch 21/100: 100%|██████████| 3929/3929 [18:24<00:00,  3.56it/s, loss=0.0099]

Epoch 21 | train_loss=0.0288 | val_loss=0.7413 | val_f1_mean=0.7305 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.76176,0.741768,0.633221,0.688406,0.613027,0.714226,0.688654,0.783654,0.898019,0.651786,...,0.750266,0.606339,0.903528,0.423453,0.831231,0.593391,0.899329,0.605153,0.522686,0.704025

  → Сохранена лучшая модель (mean F1=0.7305)

Epoch 22/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0156]

Epoch 22 | train_loss=0.0262 | val_loss=0.7864 | val_f1_mean=0.7285 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.711409,0.730703,0.646655,0.696738,0.602687,0.721779,0.684243,0.754545,0.869684,0.647059,...,0.747845,0.610009,0.904399,0.412766,0.861558,0.592262,0.896653,0.601896,0.526171,0.702916

Epoch 23/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0595]

Epoch 23 | train_loss=0.0247 | val_loss=0.8239 | val_f1_mean=0.7330 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.761468,0.714754,0.676555,0.68996,0.616438,0.706407,0.629532,0.769953,0.858696,0.616,...,0.712438,0.628544,0.912157,0.383858,0.876066,0.622575,0.895902,0.615749,0.516667,0.697638

  → Сохранена лучшая модель (mean F1=0.7330)

Epoch 24/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0095]

Epoch 24 | train_loss=0.0211 | val_loss=0.8551 | val_f1_mean=0.7364 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.731034,0.723051,0.680135,0.675279,0.585567,0.732382,0.671605,0.769585,0.870702,0.590291,...,0.734952,0.662735,0.899078,0.400826,0.861871,0.613151,0.888196,0.60435,0.550197,0.708636

  → Сохранена лучшая модель (mean F1=0.7364)

Epoch 25/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0139]

Epoch 25 | train_loss=0.0196 | val_loss=0.8879 | val_f1_mean=0.7390 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.715909,0.751304,0.674893,0.707909,0.590038,0.707593,0.642111,0.771499,0.864534,0.685851,...,0.767606,0.655225,0.907966,0.45273,0.865104,0.608626,0.899083,0.598089,0.555275,0.70757

  → Сохранена лучшая модель (mean F1=0.7390)

Epoch 26/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0052]

Epoch 26 | train_loss=0.0180 | val_loss=0.9329 | val_f1_mean=0.7409 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.776545,0.731219,0.674125,0.691204,0.596195,0.70938,0.678593,0.767059,0.876731,0.666667,...,0.738298,0.678571,0.910042,0.445783,0.886945,0.585399,0.898408,0.577972,0.561949,0.703383

  → Сохранена лучшая модель (mean F1=0.7409)

Epoch 27/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0010]

Epoch 27 | train_loss=0.0168 | val_loss=0.9861 | val_f1_mean=0.7441 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.755418,0.746377,0.669492,0.698929,0.59127,0.733845,0.66875,0.768116,0.888727,0.603113,...,0.740107,0.648073,0.900997,0.45392,0.872843,0.619161,0.90672,0.615691,0.594659,0.711431

  → Сохранена лучшая модель (mean F1=0.7441)

Epoch 28/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0007]

Epoch 28 | train_loss=0.0153 | val_loss=1.0234 | val_f1_mean=0.7449 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.777049,0.75226,0.675522,0.70229,0.618257,0.732817,0.65313,0.755556,0.886494,0.61157,...,0.710711,0.656135,0.909136,0.472393,0.884897,0.612177,0.907283,0.628793,0.601073,0.715152

  → Сохранена лучшая модель (mean F1=0.7449)

Epoch 29/100: 100%|██████████| 3929/3929 [18:26<00:00,  3.55it/s, loss=0.0009]

Epoch 29 | train_loss=0.0152 | val_loss=1.0456 | val_f1_mean=0.7438 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.7648,0.754647,0.686465,0.682798,0.63786,0.687843,0.679394,0.778626,0.868027,0.614379,...,0.712,0.683878,0.905305,0.47648,0.882704,0.622394,0.891484,0.621838,0.590217,0.715232

Epoch 30/100: 100%|██████████| 3929/3929 [18:26<00:00,  3.55it/s, loss=0.0028]

Epoch 30 | train_loss=0.0134 | val_loss=1.0214 | val_f1_mean=0.7415 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.739195,0.745167,0.652155,0.705984,0.591304,0.724376,0.68259,0.767123,0.88654,0.629787,...,0.753986,0.630058,0.911868,0.448378,0.877012,0.622642,0.910923,0.602438,0.561975,0.69042

Epoch 31/100: 100%|██████████| 3929/3929 [18:26<00:00,  3.55it/s, loss=0.0005]

Epoch 31 | train_loss=0.0135 | val_loss=1.1400 | val_f1_mean=0.7444 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.76129,0.738574,0.704167,0.697413,0.603376,0.738162,0.659612,0.762626,0.88223,0.626609,...,0.712385,0.688822,0.90566,0.434783,0.87492,0.624793,0.896789,0.60928,0.590856,0.719651

Epoch 32/100: 100%|██████████| 3929/3929 [18:26<00:00,  3.55it/s, loss=0.0003]

Epoch 32 | train_loss=0.0119 | val_loss=1.1296 | val_f1_mean=0.7454 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.767036,0.75442,0.678658,0.664566,0.613226,0.734787,0.670792,0.751843,0.895011,0.600806,...,0.760722,0.670448,0.904645,0.458213,0.878334,0.610982,0.898068,0.617301,0.588303,0.699357

  → Сохранена лучшая модель (mean F1=0.7454)

Epoch 33/100: 100%|██████████| 3929/3929 [18:26<00:00,  3.55it/s, loss=0.0013]

Epoch 33 | train_loss=0.0108 | val_loss=1.0857 | val_f1_mean=0.7442 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.707941,0.701754,0.66948,0.692278,0.613497,0.737315,0.657483,0.747204,0.888256,0.611227,...,0.730022,0.678121,0.901265,0.465839,0.885772,0.621644,0.904421,0.611905,0.595953,0.70678

Epoch 34/100: 100%|██████████| 3929/3929 [18:24<00:00,  3.56it/s, loss=0.0008]

Epoch 34 | train_loss=0.0094 | val_loss=1.1487 | val_f1_mean=0.7437 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.769231,0.74216,0.698332,0.690838,0.608889,0.735866,0.67201,0.72807,0.882603,0.675862,...,0.746961,0.669913,0.909869,0.465409,0.871071,0.600291,0.899867,0.58775,0.587234,0.72117

Epoch 35/100: 100%|██████████| 3929/3929 [18:26<00:00,  3.55it/s, loss=0.0023]

Epoch 35 | train_loss=0.0107 | val_loss=1.1728 | val_f1_mean=0.7487 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.754098,0.764398,0.674988,0.68323,0.61851,0.731173,0.681586,0.769976,0.898317,0.627706,...,0.757848,0.687109,0.910095,0.454802,0.884944,0.623462,0.904781,0.604623,0.612063,0.712971

  → Сохранена лучшая модель (mean F1=0.7487)

Epoch 36/100: 100%|██████████| 3929/3929 [18:26<00:00,  3.55it/s, loss=0.0002]

Epoch 36 | train_loss=0.0088 | val_loss=1.2473 | val_f1_mean=0.7464 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.728307,0.730909,0.693252,0.691958,0.6125,0.715728,0.680073,0.76259,0.888567,0.653753,...,0.744589,0.683444,0.908414,0.428198,0.887139,0.6,0.907568,0.621769,0.594562,0.706181

Epoch 37/100: 100%|██████████| 3929/3929 [18:24<00:00,  3.56it/s, loss=0.0003]

Epoch 37 | train_loss=0.0091 | val_loss=1.2905 | val_f1_mean=0.7484 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.781726,0.769231,0.678016,0.698619,0.599138,0.717863,0.680593,0.755102,0.865385,0.676056,...,0.746432,0.676351,0.904356,0.434137,0.890801,0.607796,0.903365,0.636652,0.590206,0.707384

Epoch 38/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0015]

Epoch 38 | train_loss=0.0079 | val_loss=1.2125 | val_f1_mean=0.7435 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.736364,0.728873,0.690464,0.661302,0.595745,0.731146,0.650617,0.777494,0.888107,0.605042,...,0.736156,0.691542,0.902829,0.450533,0.881467,0.605111,0.906275,0.590686,0.609305,0.70529

Epoch 39/100: 100%|██████████| 3929/3929 [18:24<00:00,  3.56it/s, loss=0.0018]

Epoch 39 | train_loss=0.0079 | val_loss=1.3837 | val_f1_mean=0.7482 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.780069,0.757812,0.687841,0.696754,0.596112,0.737993,0.678832,0.780105,0.895803,0.645833,...,0.739035,0.689172,0.905799,0.439425,0.889807,0.600173,0.894966,0.612323,0.614047,0.713222

Epoch 40/100: 100%|██████████| 3929/3929 [18:24<00:00,  3.56it/s, loss=0.0007]

Epoch 40 | train_loss=0.0077 | val_loss=1.3314 | val_f1_mean=0.7504 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.769231,0.768939,0.711012,0.696673,0.624146,0.714406,0.671926,0.772727,0.885106,0.642534,...,0.755716,0.683938,0.895594,0.473773,0.876535,0.615142,0.907778,0.632638,0.601679,0.723013

  → Сохранена лучшая модель (mean F1=0.7504)

Epoch 41/100: 100%|██████████| 3929/3929 [18:39<00:00,  3.51it/s, loss=0.8032]

Epoch 41 | train_loss=0.0076 | val_loss=1.2949 | val_f1_mean=0.7500 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.757252,0.768089,0.679707,0.695954,0.610101,0.730871,0.674293,0.774026,0.896452,0.640351,...,0.764411,0.69691,0.907575,0.469178,0.891838,0.591716,0.905701,0.628989,0.617766,0.722603

Epoch 42/100: 100%|██████████| 3929/3929 [18:38<00:00,  3.51it/s, loss=0.0030]

Epoch 42 | train_loss=0.0070 | val_loss=1.3397 | val_f1_mean=0.7519 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.785714,0.764595,0.698446,0.689346,0.627049,0.73505,0.691406,0.756098,0.887176,0.617886,...,0.737095,0.700637,0.905047,0.444043,0.890699,0.627927,0.906305,0.642424,0.611224,0.718039

  → Сохранена лучшая модель (mean F1=0.7519)

Epoch 43/100: 100%|██████████| 3929/3929 [18:32<00:00,  3.53it/s, loss=0.0001]

Epoch 43 | train_loss=0.0071 | val_loss=1.3119 | val_f1_mean=0.7481 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.725111,0.764706,0.688238,0.67894,0.64,0.723164,0.665357,0.765957,0.889685,0.641256,...,0.739477,0.689882,0.899632,0.438061,0.883782,0.593912,0.895949,0.639788,0.605605,0.71777

Epoch 44/100: 100%|██████████| 3929/3929 [18:35<00:00,  3.52it/s, loss=0.0002]

Epoch 44 | train_loss=0.0065 | val_loss=1.4069 | val_f1_mean=0.7508 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.788591,0.751445,0.69838,0.705036,0.615385,0.724674,0.673548,0.756219,0.898195,0.645022,...,0.727848,0.691233,0.892507,0.447863,0.879265,0.610376,0.900589,0.625,0.611749,0.700429

Epoch 45/100: 100%|██████████| 3929/3929 [18:35<00:00,  3.52it/s, loss=0.0001]

Epoch 45 | train_loss=0.0061 | val_loss=1.3932 | val_f1_mean=0.7546 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.76699,0.767568,0.684814,0.702492,0.605381,0.738297,0.686973,0.767059,0.892465,0.646512,...,0.757396,0.682212,0.909542,0.458399,0.890789,0.616462,0.908296,0.620644,0.609436,0.710988

  → Сохранена лучшая модель (mean F1=0.7546)

Epoch 46/100: 100%|██████████| 3929/3929 [18:19<00:00,  3.57it/s, loss=0.0002]

Epoch 46 | train_loss=0.0052 | val_loss=1.4434 | val_f1_mean=0.7511 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.797364,0.767396,0.67036,0.700896,0.617391,0.728972,0.67302,0.765432,0.888107,0.650831,...,0.721144,0.665718,0.911027,0.441935,0.894452,0.617754,0.89917,0.592045,0.60441,0.715462

Epoch 47/100: 100%|██████████| 3929/3929 [18:11<00:00,  3.60it/s, loss=0.0002]

Epoch 47 | train_loss=0.0053 | val_loss=1.4011 | val_f1_mean=0.7516 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.781609,0.762923,0.692938,0.695484,0.613687,0.739421,0.672542,0.756381,0.894891,0.654628,...,0.739785,0.697823,0.909136,0.433775,0.888446,0.609306,0.899405,0.594286,0.613108,0.710924

Epoch 48/100: 100%|██████████| 3929/3929 [18:11<00:00,  3.60it/s, loss=0.0002]

Epoch 48 | train_loss=0.0061 | val_loss=1.4368 | val_f1_mean=0.7530 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.753846,0.762452,0.687341,0.712681,0.607219,0.732407,0.65905,0.76259,0.886347,0.632075,...,0.768133,0.674699,0.906443,0.467005,0.881443,0.625954,0.904845,0.620818,0.596203,0.693709

Epoch 49/100: 100%|██████████| 3929/3929 [18:38<00:00,  3.51it/s, loss=0.0001]

Epoch 49 | train_loss=0.0044 | val_loss=1.4857 | val_f1_mean=0.7531 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.741985,0.769841,0.689031,0.703218,0.613445,0.747568,0.673988,0.74463,0.880057,0.622727,...,0.754366,0.692737,0.908408,0.46461,0.883934,0.613793,0.907834,0.622222,0.60212,0.712855

Epoch 50/100: 100%|██████████| 3929/3929 [18:39<00:00,  3.51it/s, loss=0.0001]

Epoch 50 | train_loss=0.0054 | val_loss=1.4334 | val_f1_mean=0.7496 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.762951,0.72449,0.694389,0.704444,0.609113,0.736417,0.679822,0.742729,0.897626,0.62203,...,0.745614,0.683122,0.907618,0.45409,0.882431,0.619254,0.911829,0.613095,0.611734,0.702359

Epoch 51/100: 100%|██████████| 3929/3929 [18:26<00:00,  3.55it/s, loss=0.0001]

Epoch 51 | train_loss=0.0052 | val_loss=1.4276 | val_f1_mean=0.7508 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.784,0.768089,0.70298,0.692396,0.597849,0.730045,0.644783,0.768041,0.892025,0.615063,...,0.759434,0.672188,0.907347,0.445194,0.88505,0.594075,0.906484,0.63601,0.608254,0.72679

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.784,0.768089,0.70298,0.692396,0.597849,0.730045,0.644783,0.768041,0.892025,0.615063,...,0.759434,0.672188,0.907347,0.445194,0.88505,0.594075,0.906484,0.63601,0.608254,0.72679

In [17]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR, num_labels=len(le.categories_[0]), local_files_only=True)
model.load_state_dict(torch.load('news_classifier_roberta-base_best.pt', weights_only=True))
model.to(DEVICE)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 9172.20it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: models/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=42, bias=True)
  )
)

In [21]:
model.eval()

pred_labels, mask_labels = [], []

val_bar = tqdm(val_dl, total=len(val_dl), desc="testing")
with torch.no_grad():
    for batch in val_bar:
        log = model(batch['input_ids'].to(DEVICE), batch['attention_mask'].to(DEVICE)).logits
        pred_labels.append((torch.sigmoid(log) > 0.5).to('cpu').numpy())
        mask_labels.append(batch['labels'].numpy())
    
    pred_labels = np.vstack(pred_labels)
    mask_labels = np.vstack(mask_labels)
    
    print(classification_report(mask_labels, pred_labels, target_names=le.categories_[0]))

testing: 100%|██████████| 1310/1310 [05:02<00:00,  4.34it/s]

                precision    recall  f1-score   support

          ARTS       0.75      0.78      0.77       302
ARTS & CULTURE       0.74      0.79      0.77       268
  BLACK VOICES       0.61      0.78      0.68       917
      BUSINESS       0.66      0.75      0.70      1198
       COLLEGE       0.62      0.59      0.61       229
        COMEDY       0.71      0.77      0.74      1080
         CRIME       0.64      0.74      0.69       713
CULTURE & ARTS       0.77      0.76      0.77       214
       DIVORCE       0.89      0.89      0.89       685
     EDUCATION       0.61      0.69      0.65       202
 ENTERTAINMENT       0.83      0.86      0.84      3473
   ENVIRONMENT       0.64      0.77      0.70       288
         FIFTY       0.83      0.72      0.77       280
  FOOD & DRINK       0.90      0.93      0.92      1268
     GOOD NEWS       0.66      0.71      0.69       280
         GREEN       0.59      0.73      0.65       524
HEALTHY LIVING       0.73      0.84      0.78      1339
 HOME & LIVING       0.86      0.92      0.89       864
        IMPACT       0.50      0.68      0.58       697
 LATINO VOICES       0.67      0.79      0.73       226
         MEDIA       0.72      0.69      0.70       589
         MONEY       0.67      0.80      0.73       351
     PARENTING       0.85      0.91      0.87      1758
       PARENTS       0.71      0.87      0.78       791
      POLITICS       0.84      0.90      0.87      7120
  QUEER VOICES       0.81      0.89      0.85      1269
      RELIGION       0.72      0.76      0.74       516
       SCIENCE       0.72      0.72      0.72       441
        SPORTS       0.81      0.88      0.84      1016
         STYLE       0.82      0.87      0.85       451
STYLE & BEAUTY       0.93      0.94      0.94      1962
         TASTE       0.80      0.86      0.83       419
          TECH       0.75      0.76      0.76       420
 THE WORLDPOST       0.67      0.70      0.68       733
        TRAVEL       0.89      0.93      0.91      1980
     U.S. NEWS       0.40      0.53      0.46       275
      WEDDINGS       0.86      0.93      0.89       731
    WEIRD NEWS       0.60      0.63      0.62       556
      WELLNESS       0.89      0.93      0.91      3588
         WOMEN       0.58      0.66      0.62       714
    WORLD NEWS       0.54      0.70      0.61       660
     WORLDPOST       0.68      0.75      0.71       516

     micro avg       0.78      0.84      0.81     41903
     macro avg       0.73      0.79      0.75     41903
  weighted avg       0.79      0.84      0.81     41903
   samples avg       0.81      0.84      0.82     41903

d:\Python\Learning\NLP_Classification\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [20]:
test_ids, test_masks = batch_tokenization(tokenizer=tokenizer, texts=test_X.to_list())
test_labels = le.transform(test_y).toarray()

test_ds = TextDataset(test_ids, test_masks, test_labels)
test_dl = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True)

model.eval()

pred_labels, mask_labels = [], []

test_bar = tqdm(test_dl, total=len(test_dl), desc="testing")

with torch.no_grad():
    for batch in test_bar:
        log = model(batch['input_ids'].to(DEVICE), batch['attention_mask'].to(DEVICE)).logits
        pred_labels.append((torch.sigmoid(log) > 0.5).to('cpu').numpy())
        mask_labels.append(batch['labels'].numpy())
    
    pred_labels = np.vstack(pred_labels)
    mask_labels = np.vstack(mask_labels)
    
    print(classification_report(mask_labels, pred_labels, target_names=le.categories_[0]))

Токенизация: 100%|██████████| 9/9 [00:06<00:00,  1.38it/s]
testing: 100%|██████████| 1310/1310 [05:00<00:00,  4.36it/s]

                precision    recall  f1-score   support

          ARTS       0.78      0.81      0.80       302
ARTS & CULTURE       0.71      0.79      0.75       268
  BLACK VOICES       0.61      0.76      0.68       916
      BUSINESS       0.66      0.79      0.71      1199
       COLLEGE       0.62      0.69      0.65       229
        COMEDY       0.73      0.80      0.77      1080
         CRIME       0.67      0.73      0.70       712
CULTURE & ARTS       0.77      0.77      0.77       215
       DIVORCE       0.88      0.86      0.87       685
     EDUCATION       0.60      0.69      0.64       203
 ENTERTAINMENT       0.84      0.87      0.85      3472
   ENVIRONMENT       0.64      0.80      0.71       289
         FIFTY       0.87      0.76      0.81       280
  FOOD & DRINK       0.90      0.94      0.92      1268
     GOOD NEWS       0.61      0.67      0.64       279
         GREEN       0.58      0.69      0.63       525
HEALTHY LIVING       0.72      0.81      0.76      1339
 HOME & LIVING       0.88      0.90      0.89       864
        IMPACT       0.50      0.67      0.57       697
 LATINO VOICES       0.66      0.77      0.71       226
         MEDIA       0.71      0.69      0.70       589
         MONEY       0.69      0.77      0.72       351
     PARENTING       0.84      0.90      0.87      1758
       PARENTS       0.73      0.87      0.80       791
      POLITICS       0.84      0.91      0.87      7120
  QUEER VOICES       0.79      0.89      0.84      1270
      RELIGION       0.73      0.75      0.74       515
       SCIENCE       0.74      0.73      0.73       441
        SPORTS       0.83      0.89      0.86      1015
         STYLE       0.79      0.87      0.83       451
STYLE & BEAUTY       0.93      0.94      0.94      1962
         TASTE       0.80      0.86      0.83       419
          TECH       0.71      0.73      0.72       420
 THE WORLDPOST       0.66      0.68      0.67       733
        TRAVEL       0.90      0.93      0.91      1980
     U.S. NEWS       0.41      0.55      0.47       276
      WEDDINGS       0.86      0.92      0.89       730
    WEIRD NEWS       0.62      0.64      0.63       555
      WELLNESS       0.89      0.93      0.91      3589
         WOMEN       0.56      0.65      0.60       714
    WORLD NEWS       0.55      0.73      0.63       660
     WORLDPOST       0.74      0.77      0.75       516

     micro avg       0.78      0.85      0.81     41903
     macro avg       0.73      0.79      0.76     41903
  weighted avg       0.79      0.85      0.81     41903
   samples avg       0.82      0.85      0.83     41903

d:\Python\Learning\NLP_Classification\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])