In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import random
from pathlib import Path
import sys
import json


from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from tqdm import tqdm
from torch.optim import AdamW
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import f1_score, classification_report

import torch.nn as nn
import torch

d:\Python\Learning\NLP_Classification\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
project_root = Path().resolve().parent

# добавляем в sys.path
sys.path.append(str(project_root))

from core.graf import *
from core.func import *
from core.nn_models import *

In [4]:
# ── Конфиг ──────────────────────────────────────────────────────────────────
DATA_PATH           = '../data/News_Category_Dataset_v3.json'
MODEL_NAME          = 'roberta-base' # 'cointegrated/rubert-tiny2'
MODEL_DIR           = f'models/{MODEL_NAME.split("/")[-1]}' 
SAVE_PATH           = f'news_classifier_{MODEL_NAME.split("/")[-1]}'
MAX_LEN             = 500
BATCH_SIZE          = 32
EPOCHS              = 100
ACCUM_STEPS         = 4
WARMUP_FRAC         = 0.1
LR                  = 2e-5
SEED                = 42
DEVICE              = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if torch.cuda.is_available():
    print("GPU: ", torch.cuda.get_device_name())
    print("VRAM:", round(torch.cuda.get_device_properties().total_memory / 1e9, 1),  'Gb')

random.seed(SEED)
torch.manual_seed(SEED)
np.random.seed(SEED)

GPU:  NVIDIA GeForce RTX 5070
VRAM: 12.8 Gb

In [5]:
with open(DATA_PATH, 'r') as file:
    data = pd.DataFrame([json.loads(line) for line in file])

data.sample(5)

,link,headline,category,short_description,authors,date
128310,https://www.huffingtonpost.com/entry/what-if-w...,What If We Were All Family Generation Changers?,IMPACT,"What if, in doing so, we won't just create new...","Matt Murrie, ContributorEdupreneur, Cofounder/...",2014-06-20
139983,https://www.huffingtonpost.comhttp://www.washi...,Firestorm At AOL Over Employee Benefit Cuts,BUSINESS,It should have been a glorious week for AOL ch...,,2014-02-08
42339,https://www.huffingtonpost.com/entry/time-runs...,Dakota Access Protesters Arrested As Deadline ...,POLITICS,A few protesters who refused to leave remained...,"Michael McLaughlin & Josh Morgan, The Huffingt...",2017-02-22
131494,https://www.huffingtonpost.com/entry/one-glimp...,One Glimpse Of These Baby Kit Foxes And You'll...,GREEN,,,2014-05-14
163649,https://www.huffingtonpost.com/entry/mens-swea...,"Mens' Sweat Pheromone, Androstadienone, Influe...",SCIENCE,Scientists didn't know if humans played that g...,Melissa Cronin,2013-06-02

In [6]:
preprocesed_data = data.copy()
preprocesed_data.drop_duplicates(inplace=True)
preprocesed_data["headline"] = preprocesed_data["headline"].str.replace("’", "'")
preprocesed_data["short_description"] = preprocesed_data["short_description"].str.replace("’", "'")
preprocesed_data["input_text"] = preprocesed_data["headline"] + " [SEP] " + preprocesed_data["authors"] + " [SEP] " + preprocesed_data["short_description"]
y = preprocesed_data[["category"]]
X = preprocesed_data["input_text"]

In [7]:
train_X, val_X, train_y, val_y = train_test_split(X, y, test_size=0.4, random_state=SEED, shuffle=True, stratify=y)
val_X, test_X, val_y, test_y = train_test_split(val_X, val_y, test_size=0.5, random_state=SEED, shuffle=True, stratify=val_y)

In [8]:
# ── Dataset с претокенизацией ─────────────────────────────────────────────────
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
le = OneHotEncoder() # LabelEncoder()

def batch_tokenization(tokenizer, texts, desc: str = "Токенизация", batch_size: int = 5000):
    all_ids, all_masks = [], []
    for i in tqdm(range(0, len(texts), batch_size), desc=desc):
        tokens = tokenizer(
            texts[i : i+batch_size],
            max_length=MAX_LEN,
            padding="max_length",
            truncation=True,
            return_tensors='pt'
        )
        all_ids.append(tokens["input_ids"])
        all_masks.append(tokens["attention_mask"])
    return torch.cat(all_ids), torch.cat(all_masks)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [9]:
train_ids, train_masks = batch_tokenization(tokenizer=tokenizer, texts=train_X.to_list())
train_labels = le.fit_transform(train_y).toarray()
train_labels

Токенизация: 100%|██████████| 26/26 [00:19<00:00,  1.30it/s]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(125708, 42))

In [10]:
counts = train_labels.sum(axis=0)

pos_weight = torch.tensor([(len(train_labels) - c) / c for c in counts], dtype=torch.float).to(DEVICE)
print('pos_weight:', pos_weight)

pos_weight: tensor([137.9039, 155.5479,  44.7120,  33.9675, 182.2478,  37.7988,  57.8245,
        193.8961,  60.1420, 205.4171,  11.0676, 144.1593, 148.4744,  32.0463,
        148.8307,  78.9161,  30.3018,  47.4985,  59.1474, 184.4100,  70.1823,
        118.2676,  22.8309,  51.9743,   4.8849,  32.0116,  80.3118,  93.9456,
         40.2699,  91.9793,  20.3535,  98.9269,  98.7683,  56.1920,  20.1630,
        151.1889,  56.3485,  74.4550,  10.6775,  57.6598,  62.5210,  80.2592],
       device='cuda:0')

In [11]:
train_ds = TextDataset(train_ids, train_masks, train_labels)
train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True)

In [12]:
val_ids, val_masks = batch_tokenization(tokenizer=tokenizer, texts=val_X.to_list())
val_labels = le.transform(val_y).toarray()

val_ds = TextDataset(val_ids, val_masks, val_labels)
val_dl = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True)

Токенизация: 100%|██████████| 9/9 [00:06<00:00,  1.36it/s]

In [13]:
lstm_model = LSTM_Classifier(num_classes=len(le.categories_[0]),
                             vocab_size=len(tokenizer.get_vocab()),
                             embedding_dim=256,
                             lstm_units=64,
                             num_layers=1,
                             )

In [ ]:
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = AdamW(lstm_model.parameters(), lr=0.001, weight_decay=0.01)
lstm_model.to(DEVICE)

training(
    model=lstm_model,
    train_data_loader=train_dl,
    val_data_loader=val_dl,
    optimizer=optimizer,
    epoches=EPOCHS,
    criterion=criterion,
    tokenizator=le,
    accum_steps=ACCUM_STEPS,
    warmup_frac=WARMUP_FRAC,
    device=DEVICE,
    save_path="LSTM_news_classifier"
    )

Epoch 1/100: 100%|██████████| 3929/3929 [00:27<00:00, 144.96it/s, loss=0.9198]

Epoch 1 | train_loss=0.8182 | val_loss=0.8262 | val_f1_mean=0.1263 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.069712,0.054299,0.0765,0.116769,0.036239,0.151257,0.088747,0.028227,0.099049,0.052889,...,0.04929,0.1293,0.195194,0.060027,0.105036,0.080088,0.448853,0.089077,0.120475,0.13425

  → Сохранена лучшая модель (mean F1=0.1263)

Epoch 2/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.90it/s, loss=0.6490]

Epoch 2 | train_loss=0.7854 | val_loss=0.7867 | val_f1_mean=0.1350 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.07754,0.068976,0.089782,0.125055,0.039464,0.149631,0.10364,0.03048,0.10573,0.05313,...,0.05593,0.153081,0.204258,0.07526,0.108743,0.088048,0.462204,0.091855,0.140412,0.162696

  → Сохранена лучшая модель (mean F1=0.1350)

Epoch 3/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.05it/s, loss=0.6398]

Epoch 3 | train_loss=0.7337 | val_loss=0.7362 | val_f1_mean=0.1454 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.077939,0.067811,0.092028,0.135133,0.04172,0.171533,0.119815,0.042094,0.115929,0.055286,...,0.064697,0.150111,0.221483,0.069938,0.122804,0.106897,0.485893,0.095483,0.157798,0.160705

  → Сохранена лучшая модель (mean F1=0.1454)

Epoch 4/100: 100%|██████████| 3929/3929 [00:26<00:00, 146.67it/s, loss=0.5210]

Epoch 4 | train_loss=0.6734 | val_loss=0.6916 | val_f1_mean=0.1554 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.082501,0.077809,0.107049,0.150686,0.039368,0.200822,0.124376,0.071155,0.14012,0.058573,...,0.076153,0.143658,0.210885,0.089378,0.128555,0.123478,0.491978,0.100346,0.140924,0.181173

  → Сохранена лучшая модель (mean F1=0.1554)

Epoch 5/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.39it/s, loss=0.5257]

Epoch 5 | train_loss=0.6088 | val_loss=0.6475 | val_f1_mean=0.1755 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.098219,0.108372,0.130706,0.160034,0.045752,0.195769,0.118691,0.078423,0.158381,0.068519,...,0.08996,0.164981,0.23188,0.074262,0.150756,0.135407,0.507034,0.136516,0.160114,0.180619

  → Сохранена лучшая модель (mean F1=0.1755)

Epoch 6/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.91it/s, loss=0.5718]

Epoch 6 | train_loss=0.5473 | val_loss=0.6243 | val_f1_mean=0.1981 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.106692,0.134021,0.155572,0.180593,0.069266,0.226556,0.174627,0.107465,0.192043,0.08611,...,0.111449,0.188258,0.32185,0.11083,0.184474,0.196183,0.514202,0.137994,0.193738,0.220605

  → Сохранена лучшая модель (mean F1=0.1981)

Epoch 7/100: 100%|██████████| 3929/3929 [00:26<00:00, 145.93it/s, loss=0.4474]

Epoch 7 | train_loss=0.4898 | val_loss=0.5844 | val_f1_mean=0.2070 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.107823,0.121702,0.165103,0.163501,0.057562,0.23989,0.154563,0.117647,0.230491,0.0889,...,0.104898,0.23353,0.326384,0.12817,0.27878,0.168343,0.532894,0.138936,0.195978,0.241686

  → Сохранена лучшая модель (mean F1=0.2070)

Epoch 8/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.59it/s, loss=0.3668]

Epoch 8 | train_loss=0.4377 | val_loss=0.5738 | val_f1_mean=0.2229 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.127394,0.119442,0.159763,0.205635,0.082807,0.244148,0.172339,0.132916,0.27346,0.095511,...,0.13033,0.25058,0.358658,0.107159,0.25088,0.197496,0.556231,0.146073,0.229109,0.244784

  → Сохранена лучшая модель (mean F1=0.2229)

Epoch 9/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.32it/s, loss=0.3512]

Epoch 9 | train_loss=0.3896 | val_loss=0.5676 | val_f1_mean=0.2445 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.199689,0.201681,0.201926,0.191228,0.085544,0.223388,0.181818,0.146465,0.256635,0.10096,...,0.125973,0.230916,0.408182,0.125099,0.312471,0.214592,0.592613,0.168232,0.247396,0.261651

  → Сохранена лучшая модель (mean F1=0.2445)

Epoch 10/100: 100%|██████████| 3929/3929 [00:27<00:00, 145.48it/s, loss=0.3703]

Epoch 10 | train_loss=0.3438 | val_loss=0.5648 | val_f1_mean=0.2631 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.174346,0.152189,0.207836,0.244812,0.121598,0.237417,0.205345,0.140365,0.365656,0.126023,...,0.141515,0.295128,0.44326,0.133758,0.369813,0.209823,0.604361,0.166327,0.274213,0.275278

  → Сохранена лучшая модель (mean F1=0.2631)

Epoch 11/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.81it/s, loss=0.3467]

Epoch 11 | train_loss=0.3024 | val_loss=0.5727 | val_f1_mean=0.2896 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.243693,0.212931,0.205811,0.228162,0.094631,0.330906,0.247119,0.217182,0.357997,0.121315,...,0.169565,0.295978,0.501298,0.145467,0.427715,0.21954,0.62416,0.193129,0.277587,0.287114

  → Сохранена лучшая модель (mean F1=0.2896)

Epoch 12/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.12it/s, loss=0.2213]

Epoch 12 | train_loss=0.2642 | val_loss=0.5767 | val_f1_mean=0.3065 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.215336,0.170373,0.198796,0.259762,0.115933,0.327179,0.2198,0.204005,0.395577,0.137134,...,0.210317,0.265113,0.559203,0.133565,0.412256,0.248242,0.651982,0.180945,0.263417,0.332368

  → Сохранена лучшая модель (mean F1=0.3065)

Epoch 13/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.46it/s, loss=0.4634]

Epoch 13 | train_loss=0.2312 | val_loss=0.6335 | val_f1_mean=0.3414 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.294985,0.258528,0.248026,0.264651,0.208333,0.356627,0.229508,0.241486,0.459369,0.197638,...,0.225694,0.283585,0.543816,0.146789,0.431208,0.244017,0.658183,0.221791,0.278001,0.328198

  → Сохранена лучшая модель (mean F1=0.3414)

Epoch 14/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.84it/s, loss=0.1454]

Epoch 14 | train_loss=0.2049 | val_loss=0.6571 | val_f1_mean=0.3542 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.280869,0.217667,0.249788,0.318934,0.21224,0.346852,0.246575,0.260204,0.457885,0.226443,...,0.220483,0.378279,0.597322,0.187763,0.490826,0.287019,0.672279,0.208034,0.33448,0.37215

  → Сохранена лучшая модель (mean F1=0.3542)

Epoch 15/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.50it/s, loss=0.2042]

Epoch 15 | train_loss=0.1827 | val_loss=0.7214 | val_f1_mean=0.3774 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.320413,0.305036,0.289434,0.303777,0.242236,0.367568,0.310297,0.287139,0.473423,0.234303,...,0.24029,0.374626,0.658617,0.237086,0.490637,0.292994,0.718255,0.244789,0.347769,0.408125

  → Сохранена лучшая модель (mean F1=0.3774)

Epoch 16/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.18it/s, loss=0.1536]

Epoch 16 | train_loss=0.1635 | val_loss=0.7771 | val_f1_mean=0.3941 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.403556,0.370161,0.314828,0.330055,0.233307,0.368189,0.304654,0.400598,0.524946,0.255875,...,0.238249,0.361103,0.631445,0.205784,0.502536,0.259585,0.748133,0.259647,0.332527,0.413726

  → Сохранена лучшая модель (mean F1=0.3941)

Epoch 17/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.82it/s, loss=0.1376]

Epoch 17 | train_loss=0.1476 | val_loss=0.8256 | val_f1_mean=0.4202 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.376987,0.413493,0.332347,0.339794,0.308252,0.395506,0.348882,0.363178,0.508251,0.312217,...,0.255823,0.406678,0.632013,0.208609,0.517886,0.299647,0.749306,0.274325,0.359903,0.399817

  → Сохранена лучшая модель (mean F1=0.4202)

Epoch 18/100: 100%|██████████| 3929/3929 [00:26<00:00, 151.09it/s, loss=0.2737]

Epoch 18 | train_loss=0.1317 | val_loss=0.8098 | val_f1_mean=0.4170 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.424746,0.266169,0.343476,0.368847,0.214667,0.418177,0.367556,0.34629,0.565299,0.289421,...,0.287224,0.393027,0.701732,0.23544,0.492481,0.292501,0.761431,0.256259,0.344893,0.459634

Epoch 19/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.14it/s, loss=0.1498]

Epoch 19 | train_loss=0.1216 | val_loss=0.8836 | val_f1_mean=0.4379 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.383604,0.406406,0.365609,0.38743,0.301339,0.444914,0.388989,0.272811,0.552065,0.317972,...,0.361217,0.429083,0.736606,0.233896,0.513189,0.312915,0.759325,0.259111,0.358663,0.431527

  → Сохранена лучшая модель (mean F1=0.4379)

Epoch 20/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.64it/s, loss=0.0599]

Epoch 20 | train_loss=0.1089 | val_loss=0.9066 | val_f1_mean=0.4470 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.401024,0.405767,0.353907,0.390583,0.252444,0.424317,0.365862,0.36751,0.628541,0.339578,...,0.31134,0.464111,0.700876,0.227568,0.535492,0.304,0.735039,0.302511,0.371398,0.461454

  → Сохранена лучшая модель (mean F1=0.4470)

Epoch 21/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.58it/s, loss=0.1976]

Epoch 21 | train_loss=0.0993 | val_loss=0.9344 | val_f1_mean=0.4556 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.414634,0.393379,0.394994,0.404096,0.293023,0.447195,0.378045,0.396947,0.566805,0.302083,...,0.299674,0.442379,0.682241,0.234234,0.529291,0.312796,0.75919,0.323975,0.332634,0.44697

  → Сохранена лучшая модель (mean F1=0.4556)

Epoch 22/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.93it/s, loss=0.1044]

Epoch 22 | train_loss=0.0895 | val_loss=1.0379 | val_f1_mean=0.4751 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.399667,0.412762,0.417369,0.439566,0.305656,0.483702,0.424416,0.409861,0.586641,0.316129,...,0.356643,0.453249,0.729647,0.28109,0.646906,0.338205,0.783864,0.29883,0.388978,0.475271

  → Сохранена лучшая модель (mean F1=0.4751)

Epoch 23/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.23it/s, loss=0.1010]

Epoch 23 | train_loss=0.0830 | val_loss=1.0328 | val_f1_mean=0.4741 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.46988,0.435449,0.416694,0.43111,0.288382,0.502037,0.398966,0.437288,0.614108,0.371274,...,0.383344,0.440832,0.70196,0.267918,0.569238,0.333871,0.788095,0.286797,0.378438,0.443272

Epoch 24/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.83it/s, loss=0.0430]

Epoch 24 | train_loss=0.0768 | val_loss=1.0859 | val_f1_mean=0.4912 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.471562,0.472681,0.379222,0.433359,0.284889,0.496705,0.402638,0.410876,0.603906,0.361111,...,0.393465,0.451389,0.716555,0.274443,0.601338,0.3618,0.770505,0.325974,0.411791,0.478441

  → Сохранена лучшая модель (mean F1=0.4912)

Epoch 25/100: 100%|██████████| 3929/3929 [00:26<00:00, 146.93it/s, loss=0.1017]

Epoch 25 | train_loss=0.0710 | val_loss=1.1948 | val_f1_mean=0.5049 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.55,0.472637,0.412772,0.434449,0.338255,0.503727,0.411812,0.373016,0.653888,0.388571,...,0.392262,0.485628,0.740527,0.26577,0.578735,0.362278,0.778678,0.343584,0.418059,0.496552

  → Сохранена лучшая модель (mean F1=0.5049)

Epoch 26/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.61it/s, loss=0.0674]

Epoch 26 | train_loss=0.0641 | val_loss=1.2052 | val_f1_mean=0.5082 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.48125,0.523529,0.453393,0.445691,0.298795,0.537627,0.406479,0.377254,0.677324,0.357424,...,0.406689,0.456625,0.732455,0.291871,0.642336,0.364427,0.782353,0.33843,0.406681,0.53564

  → Сохранена лучшая модель (mean F1=0.5082)

Epoch 27/100: 100%|██████████| 3929/3929 [00:27<00:00, 144.11it/s, loss=0.0869]

Epoch 27 | train_loss=0.0589 | val_loss=1.3287 | val_f1_mean=0.5266 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.506667,0.556414,0.465511,0.472478,0.36875,0.495319,0.439895,0.457746,0.691124,0.411856,...,0.437141,0.497312,0.728686,0.262264,0.627354,0.393634,0.794176,0.383502,0.417279,0.497525

  → Сохранена лучшая модель (mean F1=0.5266)

Epoch 28/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.52it/s, loss=0.0496]

Epoch 28 | train_loss=0.0535 | val_loss=1.2753 | val_f1_mean=0.5141 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.507135,0.445509,0.435952,0.451332,0.311927,0.519237,0.381625,0.411585,0.675878,0.339332,...,0.4,0.442524,0.76164,0.27381,0.67604,0.37728,0.786514,0.324238,0.403045,0.531488

Epoch 29/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.43it/s, loss=0.0402]

Epoch 29 | train_loss=0.0507 | val_loss=1.3028 | val_f1_mean=0.5194 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.561358,0.555735,0.451905,0.45779,0.283333,0.539606,0.433817,0.457658,0.624158,0.356589,...,0.430421,0.448342,0.764842,0.257851,0.588725,0.35069,0.79905,0.304824,0.405147,0.516213

Epoch 30/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.38it/s, loss=0.0412]

Epoch 30 | train_loss=0.0473 | val_loss=1.3808 | val_f1_mean=0.5329 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.553846,0.467662,0.4643,0.484302,0.327731,0.551873,0.420886,0.444444,0.678845,0.409449,...,0.439418,0.492702,0.726425,0.277666,0.685102,0.396135,0.807619,0.348014,0.417098,0.532955

  → Сохранена лучшая модель (mean F1=0.5329)

Epoch 31/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.29it/s, loss=0.0473]

Epoch 31 | train_loss=0.0428 | val_loss=1.4137 | val_f1_mean=0.5313 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.537143,0.48248,0.46189,0.485413,0.343704,0.548864,0.44952,0.463602,0.675029,0.428571,...,0.445957,0.49886,0.752645,0.267361,0.648392,0.40157,0.803922,0.361045,0.43115,0.530938

Epoch 32/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.24it/s, loss=0.0243]

Epoch 32 | train_loss=0.0406 | val_loss=1.5095 | val_f1_mean=0.5417 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.575597,0.595601,0.484381,0.484867,0.341463,0.530762,0.437282,0.491429,0.719702,0.396011,...,0.481836,0.486772,0.768284,0.291878,0.668139,0.385281,0.803689,0.361573,0.425881,0.534518

  → Сохранена лучшая модель (mean F1=0.5417)

Epoch 33/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.33it/s, loss=0.0154]

Epoch 33 | train_loss=0.0365 | val_loss=1.6018 | val_f1_mean=0.5530 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.611594,0.576105,0.489727,0.505787,0.370618,0.563148,0.455896,0.527523,0.746405,0.426494,...,0.454073,0.510597,0.766963,0.282587,0.705471,0.39356,0.800651,0.368222,0.426386,0.517264

  → Сохранена лучшая модель (mean F1=0.5530)

Epoch 34/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.13it/s, loss=0.0535]

Epoch 34 | train_loss=0.0336 | val_loss=1.6071 | val_f1_mean=0.5477 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.505028,0.373938,0.491152,0.522117,0.35,0.542857,0.479748,0.471513,0.727856,0.386067,...,0.462214,0.52,0.770599,0.277707,0.704706,0.3955,0.813932,0.379163,0.434071,0.540059

Epoch 35/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.64it/s, loss=0.0645]

Epoch 35 | train_loss=0.0324 | val_loss=1.5957 | val_f1_mean=0.5553 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.52111,0.468354,0.467125,0.506,0.383607,0.550735,0.473237,0.453237,0.733464,0.428346,...,0.476274,0.515137,0.758872,0.282472,0.694847,0.394768,0.819942,0.36675,0.445344,0.550265

  → Сохранена лучшая модель (mean F1=0.5553)

Epoch 36/100: 100%|██████████| 3929/3929 [00:27<00:00, 145.29it/s, loss=0.0334]

Epoch 36 | train_loss=0.0296 | val_loss=1.6158 | val_f1_mean=0.5577 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.588235,0.566775,0.497692,0.509041,0.362438,0.572157,0.479,0.472325,0.683529,0.458904,...,0.4514,0.519959,0.757388,0.261818,0.705746,0.407862,0.817599,0.384447,0.442591,0.557091

  → Сохранена лучшая модель (mean F1=0.5577)

Epoch 37/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.10it/s, loss=0.0534]

Epoch 37 | train_loss=0.0274 | val_loss=1.7272 | val_f1_mean=0.5647 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.562341,0.562401,0.516307,0.504348,0.385841,0.574756,0.48877,0.473077,0.744993,0.433613,...,0.472469,0.522541,0.756956,0.270677,0.709602,0.411552,0.821222,0.399807,0.443588,0.557966

  → Сохранена лучшая модель (mean F1=0.5647)

Epoch 38/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.74it/s, loss=0.0054]

Epoch 38 | train_loss=0.0251 | val_loss=1.7580 | val_f1_mean=0.5646 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.585831,0.564516,0.521133,0.523681,0.36953,0.560169,0.48399,0.434211,0.700483,0.458182,...,0.495274,0.51142,0.7788,0.276228,0.727052,0.410188,0.821443,0.392873,0.440524,0.561265

Epoch 39/100: 100%|██████████| 3929/3929 [00:26<00:00, 145.60it/s, loss=0.0192]

Epoch 39 | train_loss=0.0242 | val_loss=1.7756 | val_f1_mean=0.5671 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.587106,0.603509,0.506505,0.524504,0.415534,0.560639,0.49026,0.513158,0.71873,0.437607,...,0.490706,0.518703,0.783121,0.274359,0.701754,0.405437,0.800849,0.394737,0.448588,0.561538

  → Сохранена лучшая модель (mean F1=0.5671)

Epoch 40/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.23it/s, loss=0.0205]

Epoch 40 | train_loss=0.0223 | val_loss=1.8591 | val_f1_mean=0.5750 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.584239,0.559618,0.508671,0.532166,0.392015,0.564122,0.50954,0.497942,0.734987,0.486166,...,0.5,0.515768,0.773527,0.287234,0.706927,0.415446,0.81522,0.385093,0.447267,0.583199

  → Сохранена лучшая модель (mean F1=0.5750)

Epoch 41/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.45it/s, loss=0.0308]

Epoch 41 | train_loss=0.0207 | val_loss=1.8860 | val_f1_mean=0.5748 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.609929,0.59589,0.519165,0.531858,0.381982,0.575769,0.503695,0.444037,0.732468,0.474265,...,0.509341,0.518157,0.776965,0.280757,0.716777,0.421434,0.818337,0.385809,0.431197,0.558824

Epoch 42/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.04it/s, loss=0.0123]

Epoch 42 | train_loss=0.0193 | val_loss=1.8389 | val_f1_mean=0.5696 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.609418,0.584459,0.531462,0.516036,0.3766,0.555676,0.476476,0.492126,0.736772,0.486056,...,0.475089,0.531401,0.775821,0.27013,0.696107,0.4,0.809653,0.393693,0.449383,0.587081

Epoch 43/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.44it/s, loss=0.0300]

Epoch 43 | train_loss=0.0172 | val_loss=1.9654 | val_f1_mean=0.5782 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.625551,0.562092,0.524927,0.517473,0.344538,0.579332,0.490239,0.49676,0.750681,0.427457,...,0.517799,0.528343,0.754121,0.262794,0.719277,0.413223,0.812998,0.409951,0.449095,0.559043

  → Сохранена лучшая модель (mean F1=0.5782)

Epoch 44/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.96it/s, loss=0.0104]

Epoch 44 | train_loss=0.0168 | val_loss=1.8863 | val_f1_mean=0.5694 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.567807,0.581281,0.532592,0.524257,0.372694,0.567737,0.491024,0.497942,0.70303,0.483559,...,0.48942,0.528162,0.776989,0.264507,0.703943,0.413299,0.817693,0.417391,0.443016,0.568582

Epoch 45/100: 100%|██████████| 3929/3929 [00:27<00:00, 144.82it/s, loss=0.0061]

Epoch 45 | train_loss=0.0161 | val_loss=1.9757 | val_f1_mean=0.5767 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.564232,0.591837,0.510049,0.525962,0.363328,0.581307,0.524764,0.493671,0.729783,0.441331,...,0.505219,0.52283,0.782777,0.294944,0.730864,0.408805,0.818423,0.410104,0.447829,0.561934

Epoch 46/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.21it/s, loss=0.0094]

Epoch 46 | train_loss=0.0139 | val_loss=2.0619 | val_f1_mean=0.5814 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.574772,0.57377,0.542268,0.524641,0.391919,0.590507,0.517007,0.506438,0.760779,0.472795,...,0.483475,0.526801,0.794771,0.277439,0.728288,0.420896,0.808934,0.427141,0.441543,0.551158

  → Сохранена лучшая модель (mean F1=0.5814)

Epoch 47/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.91it/s, loss=0.0161]

Epoch 47 | train_loss=0.0136 | val_loss=2.0507 | val_f1_mean=0.5825 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.634731,0.605634,0.523284,0.529458,0.404,0.608046,0.50028,0.515419,0.733675,0.458484,...,0.489758,0.52765,0.760279,0.284264,0.725944,0.42341,0.817751,0.414867,0.442308,0.571192

  → Сохранена лучшая модель (mean F1=0.5825)

Epoch 48/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.29it/s, loss=0.0043]

Epoch 48 | train_loss=0.0125 | val_loss=2.1169 | val_f1_mean=0.5861 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.609551,0.607018,0.518899,0.528533,0.394477,0.57,0.515513,0.518359,0.770099,0.487603,...,0.538126,0.50303,0.783361,0.283439,0.727498,0.424752,0.817715,0.424047,0.439854,0.559451

  → Сохранена лучшая модель (mean F1=0.5861)

Epoch 49/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.64it/s, loss=0.0033]

Epoch 49 | train_loss=0.0109 | val_loss=2.1492 | val_f1_mean=0.5870 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.606993,0.608696,0.533532,0.531832,0.400818,0.60423,0.5183,0.481553,0.750835,0.469925,...,0.520357,0.526374,0.783954,0.284519,0.720049,0.418103,0.816618,0.439879,0.44232,0.578991

  → Сохранена лучшая модель (mean F1=0.5870)

Epoch 50/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.92it/s, loss=0.0024]

Epoch 50 | train_loss=0.0108 | val_loss=2.2384 | val_f1_mean=0.5906 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.649624,0.605166,0.539493,0.532096,0.404715,0.591449,0.50291,0.497908,0.750337,0.471774,...,0.51298,0.531966,0.790002,0.279778,0.735705,0.419152,0.813969,0.427419,0.448485,0.580479

  → Сохранена лучшая модель (mean F1=0.5906)

Epoch 51/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.96it/s, loss=0.0174]

Epoch 51 | train_loss=0.0105 | val_loss=2.1630 | val_f1_mean=0.5834 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.667674,0.626374,0.545455,0.509153,0.313397,0.596082,0.512464,0.50108,0.764706,0.469602,...,0.497984,0.510851,0.787116,0.276968,0.725466,0.405063,0.816702,0.418502,0.43594,0.572607

Epoch 52/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.27it/s, loss=0.0077]

Epoch 52 | train_loss=0.0098 | val_loss=2.2443 | val_f1_mean=0.5902 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.649469,0.596315,0.528265,0.541935,0.413386,0.589549,0.512998,0.501071,0.76257,0.468165,...,0.535714,0.522196,0.794372,0.279001,0.743083,0.430206,0.819503,0.411545,0.452212,0.582192

Epoch 53/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.64it/s, loss=0.0106]

Epoch 53 | train_loss=0.0096 | val_loss=2.2842 | val_f1_mean=0.5860 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.637016,0.601019,0.544421,0.535421,0.40568,0.593725,0.511002,0.473282,0.769899,0.477551,...,0.523109,0.523699,0.762966,0.267606,0.745939,0.428468,0.817291,0.433234,0.463542,0.584588

Epoch 54/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.03it/s, loss=0.0025]

Epoch 54 | train_loss=0.0087 | val_loss=2.2486 | val_f1_mean=0.5902 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.646972,0.581583,0.540596,0.52924,0.393638,0.615186,0.515134,0.489879,0.754508,0.473881,...,0.447224,0.520442,0.791176,0.277143,0.747436,0.431751,0.818885,0.434884,0.453247,0.591426

Epoch 55/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.64it/s, loss=0.0025]

Epoch 55 | train_loss=0.0078 | val_loss=2.3307 | val_f1_mean=0.5948 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.660633,0.629295,0.52554,0.541481,0.421053,0.595228,0.505896,0.497797,0.748634,0.488798,...,0.534043,0.516166,0.792731,0.268657,0.741772,0.428887,0.817287,0.427586,0.451971,0.580065

  → Сохранена лучшая модель (mean F1=0.5948)

Epoch 56/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.75it/s, loss=0.0240]

Epoch 56 | train_loss=0.0072 | val_loss=2.3231 | val_f1_mean=0.5931 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.646109,0.611307,0.539747,0.540016,0.416834,0.605634,0.505166,0.5,0.759336,0.479371,...,0.493578,0.518694,0.792471,0.277228,0.739869,0.42236,0.82045,0.426727,0.465028,0.574501

Epoch 57/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.18it/s, loss=0.0039]

Epoch 57 | train_loss=0.0070 | val_loss=2.3458 | val_f1_mean=0.5926 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.642045,0.61825,0.538541,0.538113,0.407921,0.602831,0.510563,0.42953,0.775362,0.491525,...,0.531672,0.53598,0.787908,0.278057,0.735849,0.418871,0.815276,0.439053,0.461133,0.591216

Epoch 58/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.99it/s, loss=0.0060]

Epoch 58 | train_loss=0.0068 | val_loss=2.3793 | val_f1_mean=0.5940 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.633094,0.626151,0.52356,0.543348,0.398482,0.615519,0.498584,0.473118,0.764912,0.495575,...,0.539446,0.518473,0.798015,0.272859,0.737113,0.415638,0.821294,0.419318,0.461935,0.569195

Epoch 59/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.58it/s, loss=0.0057]

Epoch 59 | train_loss=0.0063 | val_loss=2.3762 | val_f1_mean=0.5919 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.640118,0.617424,0.52984,0.54052,0.391791,0.586396,0.501421,0.472477,0.775801,0.498943,...,0.538883,0.529855,0.788392,0.272873,0.731156,0.421622,0.815293,0.440122,0.453537,0.574324

Epoch 60/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.87it/s, loss=0.0015]

Epoch 60 | train_loss=0.0056 | val_loss=2.4339 | val_f1_mean=0.5934 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.646707,0.605405,0.546197,0.543024,0.412955,0.594305,0.515038,0.448637,0.76257,0.472795,...,0.553531,0.525265,0.79646,0.267091,0.744611,0.423106,0.817549,0.424485,0.468468,0.591716

Epoch 61/100: 100%|██████████| 3929/3929 [00:26<00:00, 146.77it/s, loss=0.0014]

Epoch 61 | train_loss=0.0052 | val_loss=2.4814 | val_f1_mean=0.5968 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.651719,0.61825,0.548438,0.536773,0.420601,0.604493,0.508432,0.454728,0.751199,0.466926,...,0.537155,0.53,0.790539,0.251724,0.7426,0.430599,0.819422,0.431145,0.449541,0.600522

  → Сохранена лучшая модель (mean F1=0.5968)

Epoch 62/100: 100%|██████████| 3929/3929 [00:28<00:00, 138.34it/s, loss=0.0011]

Epoch 62 | train_loss=0.0050 | val_loss=2.5091 | val_f1_mean=0.5999 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.665625,0.630975,0.54469,0.54112,0.4,0.619007,0.499408,0.486726,0.727621,0.492632,...,0.537217,0.53222,0.795726,0.265176,0.743887,0.43407,0.818218,0.437227,0.460362,0.579853

  → Сохранена лучшая модель (mean F1=0.5999)

Epoch 63/100: 100%|██████████| 3929/3929 [00:26<00:00, 146.19it/s, loss=0.0081]

Epoch 63 | train_loss=0.0047 | val_loss=2.4608 | val_f1_mean=0.5950 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.634424,0.62963,0.506655,0.542811,0.399202,0.601084,0.489578,0.466926,0.767104,0.480916,...,0.528571,0.526444,0.792026,0.288372,0.754293,0.415828,0.82126,0.433862,0.465772,0.586919

Epoch 64/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.16it/s, loss=0.0006]

Epoch 64 | train_loss=0.0043 | val_loss=2.6140 | val_f1_mean=0.6032 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.661367,0.640159,0.54738,0.53288,0.439716,0.619556,0.513531,0.5,0.767409,0.495935,...,0.534521,0.529769,0.76647,0.272131,0.737516,0.433931,0.814129,0.445055,0.461747,0.579882

  → Сохранена лучшая модель (mean F1=0.6032)

Epoch 65/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.62it/s, loss=0.0007]

Epoch 65 | train_loss=0.0043 | val_loss=2.5146 | val_f1_mean=0.6001 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.662461,0.619926,0.524952,0.53967,0.407484,0.624314,0.514251,0.491228,0.756014,0.470817,...,0.522199,0.523442,0.798811,0.283439,0.744488,0.440033,0.82032,0.439716,0.450231,0.605146

Epoch 66/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.98it/s, loss=0.0038]

Epoch 66 | train_loss=0.0042 | val_loss=2.5552 | val_f1_mean=0.5996 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.653784,0.619926,0.537624,0.53533,0.393162,0.612722,0.510268,0.518349,0.76105,0.465385,...,0.546697,0.516775,0.802567,0.283361,0.743855,0.420624,0.81729,0.425799,0.464387,0.601597

Epoch 67/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.36it/s, loss=0.0113]

Epoch 67 | train_loss=0.0040 | val_loss=2.5565 | val_f1_mean=0.5984 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.597333,0.6098,0.555556,0.544728,0.408353,0.580467,0.515666,0.466063,0.759754,0.509259,...,0.518299,0.521315,0.791992,0.296407,0.703878,0.444965,0.81996,0.440299,0.468689,0.601876

Epoch 68/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.26it/s, loss=0.0009]

Epoch 68 | train_loss=0.0036 | val_loss=2.6722 | val_f1_mean=0.6054 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.651235,0.621622,0.54739,0.542399,0.39916,0.61525,0.522727,0.496703,0.766017,0.477178,...,0.554133,0.520717,0.79271,0.289157,0.754271,0.439432,0.824487,0.44086,0.467153,0.604203

  → Сохранена лучшая модель (mean F1=0.6054)

Epoch 69/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.44it/s, loss=0.0010]

Epoch 69 | train_loss=0.0034 | val_loss=2.6261 | val_f1_mean=0.6011 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.669856,0.625954,0.547532,0.532766,0.404211,0.611476,0.521581,0.5,0.75,0.47561,...,0.537217,0.527171,0.796447,0.28972,0.754817,0.418745,0.820188,0.443062,0.461318,0.600177

Epoch 70/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.57it/s, loss=0.0013]

Epoch 70 | train_loss=0.0031 | val_loss=2.6736 | val_f1_mean=0.6043 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.643713,0.620038,0.553283,0.538527,0.405345,0.62167,0.508453,0.479657,0.755431,0.513889,...,0.556725,0.520703,0.794446,0.287129,0.725926,0.43252,0.823065,0.444025,0.45633,0.576078

Epoch 71/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.01it/s, loss=0.0015]

Epoch 71 | train_loss=0.0031 | val_loss=2.6436 | val_f1_mean=0.6045 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.654762,0.625,0.555855,0.543136,0.416667,0.625664,0.524841,0.497778,0.765778,0.501109,...,0.549153,0.527207,0.800201,0.298742,0.730889,0.4494,0.822771,0.421444,0.462277,0.588841

Epoch 72/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.22it/s, loss=0.0031]

Epoch 72 | train_loss=0.0026 | val_loss=2.7154 | val_f1_mean=0.6075 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.691152,0.633663,0.556044,0.526955,0.429501,0.62069,0.513897,0.495413,0.763736,0.503226,...,0.552119,0.523353,0.795832,0.272873,0.754077,0.437075,0.820109,0.438048,0.464088,0.597188

  → Сохранена лучшая модель (mean F1=0.6075)

Epoch 73/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.23it/s, loss=0.0008]

Epoch 73 | train_loss=0.0028 | val_loss=2.7162 | val_f1_mean=0.6030 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.622348,0.614801,0.546189,0.541839,0.432314,0.623454,0.52548,0.483333,0.762369,0.518349,...,0.551804,0.529639,0.798209,0.272566,0.755968,0.440035,0.818709,0.441943,0.46987,0.585446

Epoch 74/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.51it/s, loss=0.0006]

Epoch 74 | train_loss=0.0028 | val_loss=2.6590 | val_f1_mean=0.6028 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.651095,0.623574,0.537267,0.541667,0.427948,0.624297,0.517748,0.49453,0.733247,0.489362,...,0.553809,0.528169,0.798803,0.271186,0.697322,0.433871,0.823768,0.444308,0.469837,0.60312

Epoch 75/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.24it/s, loss=0.0004]

Epoch 75 | train_loss=0.0023 | val_loss=2.7862 | val_f1_mean=0.6090 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.661342,0.619231,0.555556,0.535106,0.428246,0.632945,0.51462,0.497585,0.769231,0.482759,...,0.543405,0.518129,0.801707,0.270364,0.753094,0.42926,0.815625,0.437005,0.460383,0.588629

  → Сохранена лучшая модель (mean F1=0.6090)

Epoch 76/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.95it/s, loss=0.0024]

Epoch 76 | train_loss=0.0026 | val_loss=2.7832 | val_f1_mean=0.6068 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.643815,0.628906,0.556399,0.533822,0.43318,0.631719,0.516336,0.466513,0.773784,0.511111,...,0.550276,0.522699,0.795973,0.268041,0.74903,0.437968,0.821862,0.439241,0.466356,0.61302

Epoch 77/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.62it/s, loss=0.0008]

Epoch 77 | train_loss=0.0025 | val_loss=2.7356 | val_f1_mean=0.6073 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.651719,0.61426,0.552341,0.536195,0.417021,0.626378,0.501263,0.484444,0.762102,0.506383,...,0.569378,0.534238,0.799695,0.265385,0.762097,0.439863,0.824118,0.445283,0.479839,0.595259

Epoch 78/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.50it/s, loss=0.0003]

Epoch 78 | train_loss=0.0023 | val_loss=2.7564 | val_f1_mean=0.6080 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.671924,0.636893,0.545551,0.536627,0.431965,0.626984,0.511194,0.489083,0.755198,0.503226,...,0.552863,0.53088,0.800708,0.281506,0.754271,0.436275,0.821231,0.441975,0.468859,0.591065

Epoch 79/100: 100%|██████████| 3929/3929 [00:25<00:00, 154.30it/s, loss=0.0010]

Epoch 79 | train_loss=0.0017 | val_loss=2.8246 | val_f1_mean=0.6080 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.664634,0.620038,0.557143,0.536952,0.43662,0.628774,0.511229,0.49345,0.769986,0.511737,...,0.547461,0.534025,0.790891,0.266898,0.75,0.432872,0.82554,0.446281,0.465578,0.59823

Epoch 80/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.84it/s, loss=0.0006]

Epoch 80 | train_loss=0.0018 | val_loss=2.8398 | val_f1_mean=0.6107 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.660688,0.590106,0.561873,0.542241,0.434389,0.6134,0.513109,0.506977,0.772954,0.51073,...,0.54928,0.531973,0.801309,0.283662,0.749839,0.429156,0.823132,0.439625,0.471063,0.603978

  → Сохранена лучшая модель (mean F1=0.6107)

Epoch 81/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.41it/s, loss=0.0007]

Epoch 81 | train_loss=0.0017 | val_loss=2.8687 | val_f1_mean=0.6106 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.66875,0.622391,0.558347,0.541087,0.436681,0.630112,0.513055,0.486364,0.735219,0.533958,...,0.550725,0.524695,0.806936,0.28436,0.750983,0.437194,0.825154,0.441762,0.470839,0.601093

Epoch 82/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.68it/s, loss=0.0003]

Epoch 82 | train_loss=0.0017 | val_loss=2.8782 | val_f1_mean=0.6116 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.681388,0.636542,0.561983,0.544033,0.429864,0.615648,0.515424,0.502203,0.764585,0.523364,...,0.539851,0.528904,0.796434,0.284229,0.746957,0.438287,0.823482,0.443627,0.46087,0.603774

  → Сохранена лучшая модель (mean F1=0.6116)

Epoch 83/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.98it/s, loss=0.0017]

Epoch 83 | train_loss=0.0014 | val_loss=2.9170 | val_f1_mean=0.6128 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.667692,0.62572,0.556207,0.540225,0.423963,0.630237,0.51733,0.49217,0.773015,0.534279,...,0.565774,0.518706,0.801506,0.277592,0.76451,0.43686,0.822557,0.443084,0.461103,0.604224

  → Сохранена лучшая модель (mean F1=0.6128)

Epoch 84/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.11it/s, loss=0.0016]

Epoch 84 | train_loss=0.0015 | val_loss=2.8618 | val_f1_mean=0.6127 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.681182,0.623077,0.558966,0.54165,0.431655,0.621517,0.520548,0.486022,0.766368,0.528889,...,0.566474,0.521964,0.803449,0.266867,0.76032,0.447257,0.822518,0.442574,0.461752,0.607664

Epoch 85/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.13it/s, loss=0.0018]

Epoch 85 | train_loss=0.0014 | val_loss=2.9371 | val_f1_mean=0.6136 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.672986,0.629559,0.559047,0.539212,0.429561,0.632809,0.521008,0.492239,0.774929,0.52381,...,0.548673,0.516173,0.800603,0.281407,0.765449,0.450928,0.825633,0.442739,0.467384,0.599474

  → Сохранена лучшая модель (mean F1=0.6136)

Epoch 86/100: 100%|██████████| 3929/3929 [00:26<00:00, 147.18it/s, loss=0.0003]

Epoch 86 | train_loss=0.0015 | val_loss=2.8973 | val_f1_mean=0.6122 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.675039,0.61597,0.554705,0.538922,0.420131,0.63628,0.518706,0.497696,0.749177,0.527716,...,0.563246,0.510949,0.801703,0.27451,0.729167,0.451049,0.825517,0.445954,0.462882,0.590109

Epoch 87/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.19it/s, loss=0.0005]

Epoch 87 | train_loss=0.0012 | val_loss=2.9522 | val_f1_mean=0.6139 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.696817,0.620424,0.547903,0.533444,0.431555,0.629464,0.517949,0.495455,0.763485,0.508264,...,0.565321,0.530105,0.80468,0.277966,0.756652,0.448805,0.82502,0.452854,0.457778,0.600713

  → Сохранена лучшая модель (mean F1=0.6139)

Epoch 88/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.60it/s, loss=0.0004]

Epoch 88 | train_loss=0.0013 | val_loss=2.9391 | val_f1_mean=0.6139 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.693419,0.620155,0.555739,0.532218,0.423326,0.632379,0.521849,0.497696,0.770965,0.518681,...,0.570755,0.526803,0.800605,0.270364,0.754183,0.441472,0.824854,0.455148,0.465909,0.604733

Epoch 89/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.60it/s, loss=0.0005]

Epoch 89 | train_loss=0.0011 | val_loss=2.9797 | val_f1_mean=0.6139 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.674961,0.617761,0.55,0.537616,0.422727,0.636281,0.518615,0.49537,0.771731,0.508475,...,0.563084,0.532183,0.803522,0.258652,0.757497,0.441125,0.824689,0.454159,0.466568,0.610507

Epoch 90/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.98it/s, loss=0.0004]

Epoch 90 | train_loss=0.0011 | val_loss=2.9623 | val_f1_mean=0.6141 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.669782,0.61657,0.555014,0.537653,0.433962,0.625387,0.520079,0.496583,0.773145,0.537246,...,0.551339,0.534185,0.803213,0.277193,0.759344,0.441251,0.823578,0.445264,0.465654,0.598628

  → Сохранена лучшая модель (mean F1=0.6141)

Epoch 91/100: 100%|██████████| 3929/3929 [00:25<00:00, 153.70it/s, loss=0.0016]

Epoch 91 | train_loss=0.0011 | val_loss=3.0076 | val_f1_mean=0.6157 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.68543,0.619608,0.560264,0.538017,0.440758,0.630435,0.517986,0.508009,0.766135,0.538462,...,0.564868,0.533069,0.803026,0.268293,0.757319,0.438521,0.825534,0.454027,0.467164,0.60241

  → Сохранена лучшая модель (mean F1=0.6157)

Epoch 92/100: 100%|██████████| 3929/3929 [00:26<00:00, 149.69it/s, loss=0.0000]

Epoch 92 | train_loss=0.0011 | val_loss=3.0271 | val_f1_mean=0.6164 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.6752,0.622047,0.561071,0.539289,0.440191,0.630915,0.514826,0.505695,0.77551,0.536817,...,0.559622,0.534853,0.798908,0.277087,0.765056,0.439655,0.823832,0.451288,0.469778,0.605336

  → Сохранена лучшая модель (mean F1=0.6164)

Epoch 93/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.63it/s, loss=0.0002]

Epoch 93 | train_loss=0.0010 | val_loss=3.0167 | val_f1_mean=0.6164 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.677165,0.621881,0.559608,0.538658,0.43578,0.633726,0.51541,0.504673,0.779928,0.528889,...,0.568075,0.534506,0.802302,0.282569,0.765844,0.439195,0.823482,0.459016,0.463768,0.606061

Epoch 94/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.81it/s, loss=0.0003]

Epoch 94 | train_loss=0.0010 | val_loss=2.9948 | val_f1_mean=0.6156 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.68239,0.629126,0.554768,0.536585,0.427617,0.633394,0.514789,0.484988,0.779221,0.519362,...,0.561321,0.534667,0.801696,0.284746,0.756335,0.444444,0.824552,0.460256,0.464873,0.608219

Epoch 95/100: 100%|██████████| 3929/3929 [00:26<00:00, 148.96it/s, loss=0.0001]

Epoch 95 | train_loss=0.0009 | val_loss=3.0611 | val_f1_mean=0.6160 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.684887,0.623529,0.560935,0.539589,0.431461,0.624021,0.515584,0.483721,0.778177,0.522353,...,0.562945,0.53406,0.806452,0.271914,0.763228,0.440305,0.823577,0.456958,0.463704,0.612282

Epoch 96/100: 100%|██████████| 3929/3929 [00:25<00:00, 151.49it/s, loss=0.0021]

Epoch 96 | train_loss=0.0009 | val_loss=3.0264 | val_f1_mean=0.6158 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.684887,0.623782,0.562814,0.540977,0.435597,0.629579,0.51332,0.494172,0.775972,0.52506,...,0.557078,0.532,0.802602,0.262295,0.761155,0.437981,0.824427,0.45625,0.464945,0.610449

Epoch 97/100: 100%|██████████| 3929/3929 [00:25<00:00, 152.78it/s, loss=0.0007]

Epoch 97 | train_loss=0.0008 | val_loss=3.0305 | val_f1_mean=0.6159 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.681672,0.629126,0.561305,0.540426,0.428894,0.63234,0.513016,0.497674,0.776224,0.517483,...,0.569412,0.531561,0.805241,0.27,0.762155,0.438144,0.825384,0.458228,0.468795,0.604525

Epoch 98/100: 100%|██████████| 3929/3929 [00:26<00:00, 150.02it/s, loss=0.0001]

Epoch 98 | train_loss=0.0009 | val_loss=3.0467 | val_f1_mean=0.6160 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.684628,0.629126,0.558398,0.540609,0.431461,0.62995,0.513583,0.5,0.77707,0.523585,...,0.571765,0.529015,0.804005,0.272414,0.762409,0.437554,0.825259,0.459057,0.462342,0.610701

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.684628,0.629126,0.558398,0.540609,0.431461,0.62995,0.513583,0.5,0.77707,0.523585,...,0.571765,0.529015,0.804005,0.272414,0.762409,0.437554,0.825259,0.459057,0.462342,0.610701

In [ ]:
rnn_model = RNN_Text_Classifier(
    num_classes=len(le.categories_[0]),
    vocab_size=len(tokenizer.get_vocab()),
    embedding_dim=256,
    hidden_size=64,
)

In [ ]:
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = AdamW(rnn_model.parameters(), lr=0.001, weight_decay=0.01)
rnn_model.to(DEVICE)

training(
    model=rnn_model,
    train_data_loader=train_dl,
    val_data_loader=val_dl,
    optimizer=optimizer,
    epoches=EPOCHS,
    criterion=criterion,
    tokenizator=le,
    accum_steps=ACCUM_STEPS,
    warmup_frac=WARMUP_FRAC,
    device=DEVICE,
    save_path="RNN_news_classifier"
    )

Epoch 1/100: 100%|██████████| 3929/3929 [00:20<00:00, 191.61it/s, loss=1.0024]

Epoch 1 | train_loss=1.3570 | val_loss=1.3269 | val_f1_mean=0.0573 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.052103,0.017836,0.043781,0.057645,0.019585,0.061354,0.046257,0.019593,0.046925,0.009441,...,0.028508,0.042915,0.080482,0.022516,0.05595,0.028506,0.198272,0.034512,0.041638,0.117872

  → Сохранена лучшая модель (mean F1=0.0573)

Epoch 2/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.97it/s, loss=1.1704]

Epoch 2 | train_loss=1.3025 | val_loss=1.2759 | val_f1_mean=0.0647 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.040181,0.017625,0.040752,0.058185,0.013375,0.07864,0.055243,0.019334,0.063131,0.0,...,0.022055,0.042975,0.099358,0.022946,0.075064,0.03065,0.209654,0.036573,0.045472,0.120461

  → Сохранена лучшая модель (mean F1=0.0647)

Epoch 3/100: 100%|██████████| 3929/3929 [00:20<00:00, 188.92it/s, loss=0.9198]

Epoch 3 | train_loss=1.2702 | val_loss=1.2613 | val_f1_mean=0.0678 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.025324,0.01784,0.043777,0.0641,0.014105,0.087619,0.055021,0.021556,0.066189,0.011514,...,0.028457,0.04359,0.103068,0.022946,0.07841,0.030447,0.2138,0.03715,0.044162,0.121027

  → Сохранена лучшая модель (mean F1=0.0678)

Epoch 4/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.94it/s, loss=0.8162]

Epoch 4 | train_loss=1.2279 | val_loss=1.1708 | val_f1_mean=0.0760 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.036596,0.028024,0.0546,0.06977,0.017996,0.06946,0.053933,0.017955,0.062838,0.024313,...,0.027546,0.068392,0.161366,0.036289,0.070577,0.049023,0.286198,0.038839,0.067045,0.064892

  → Сохранена лучшая модель (mean F1=0.0760)

Epoch 5/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.80it/s, loss=1.6975]

Epoch 5 | train_loss=1.1545 | val_loss=1.1374 | val_f1_mean=0.0791 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.035538,0.032027,0.057419,0.075211,0.019157,0.07516,0.05792,0.020061,0.07131,0.021083,...,0.028879,0.069666,0.154568,0.037507,0.076836,0.056451,0.265532,0.03709,0.068801,0.06064

  → Сохранена лучшая модель (mean F1=0.0791)

Epoch 6/100: 100%|██████████| 3929/3929 [00:21<00:00, 182.26it/s, loss=0.8345]

Epoch 6 | train_loss=1.1195 | val_loss=1.1131 | val_f1_mean=0.0829 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.037446,0.031261,0.063114,0.075685,0.020242,0.089612,0.0606,0.017538,0.058579,0.022025,...,0.031985,0.073678,0.161063,0.043026,0.063607,0.057938,0.273055,0.043631,0.072468,0.077574

  → Сохранена лучшая модель (mean F1=0.0829)

Epoch 7/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.86it/s, loss=1.0366]

Epoch 7 | train_loss=1.0940 | val_loss=1.1092 | val_f1_mean=0.0836 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.037895,0.033117,0.062319,0.077071,0.020262,0.097527,0.063058,0.017023,0.060569,0.020154,...,0.039254,0.079458,0.158159,0.040577,0.062207,0.060263,0.274623,0.045584,0.08209,0.084855

  → Сохранена лучшая модель (mean F1=0.0836)

Epoch 8/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.47it/s, loss=0.9488]

Epoch 8 | train_loss=1.0724 | val_loss=1.1133 | val_f1_mean=0.0886 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.03852,0.031327,0.059151,0.080305,0.020954,0.082642,0.056167,0.01738,0.066552,0.023039,...,0.041646,0.102664,0.168134,0.050623,0.072756,0.057781,0.29935,0.051081,0.101384,0.065934

  → Сохранена лучшая модель (mean F1=0.0886)

Epoch 9/100: 100%|██████████| 3929/3929 [00:21<00:00, 184.01it/s, loss=0.9545]

Epoch 9 | train_loss=1.0517 | val_loss=1.0942 | val_f1_mean=0.0899 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.038565,0.03804,0.064265,0.083624,0.019185,0.104341,0.065845,0.017406,0.064727,0.021951,...,0.046898,0.10817,0.157127,0.05476,0.067465,0.06425,0.28677,0.048516,0.119598,0.064161

  → Сохранена лучшая модель (mean F1=0.0899)

Epoch 10/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.20it/s, loss=1.1635]

Epoch 10 | train_loss=1.0285 | val_loss=1.0747 | val_f1_mean=0.0911 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.042322,0.031673,0.067512,0.082149,0.019569,0.105199,0.062983,0.018341,0.069672,0.023859,...,0.046067,0.089632,0.169221,0.041814,0.07445,0.060479,0.305911,0.047561,0.082931,0.074535

  → Сохранена лучшая модель (mean F1=0.0911)

Epoch 11/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.30it/s, loss=0.8215]

Epoch 11 | train_loss=1.0027 | val_loss=1.1074 | val_f1_mean=0.0937 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.040266,0.035935,0.06596,0.084657,0.019006,0.093174,0.062497,0.017422,0.069444,0.022153,...,0.057227,0.114903,0.166581,0.054387,0.071284,0.054537,0.3082,0.059942,0.122146,0.080806

  → Сохранена лучшая модель (mean F1=0.0937)

Epoch 12/100: 100%|██████████| 3929/3929 [00:20<00:00, 187.54it/s, loss=0.9789]

Epoch 12 | train_loss=0.9761 | val_loss=1.1249 | val_f1_mean=0.0961 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.057333,0.045933,0.066439,0.089046,0.021394,0.095546,0.060886,0.017908,0.07002,0.023888,...,0.065205,0.131795,0.168157,0.052534,0.072133,0.053812,0.312071,0.055118,0.119912,0.102376

  → Сохранена лучшая модель (mean F1=0.0961)

Epoch 13/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.71it/s, loss=1.0430]

Epoch 13 | train_loss=0.9496 | val_loss=1.1430 | val_f1_mean=0.0994 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.041973,0.041982,0.069473,0.091498,0.019827,0.096522,0.059626,0.01772,0.080922,0.0265,...,0.063593,0.134392,0.177085,0.047713,0.080539,0.055234,0.329087,0.054772,0.137623,0.120871

  → Сохранена лучшая модель (mean F1=0.0994)

Epoch 14/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.53it/s, loss=0.8802]

Epoch 14 | train_loss=0.9285 | val_loss=1.1378 | val_f1_mean=0.1011 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.04422,0.044164,0.070518,0.090577,0.02275,0.097834,0.062116,0.019649,0.072462,0.025976,...,0.061576,0.142627,0.17064,0.055878,0.07703,0.054338,0.310789,0.058204,0.14116,0.12911

  → Сохранена лучшая модель (mean F1=0.1011)

Epoch 15/100: 100%|██████████| 3929/3929 [00:20<00:00, 191.90it/s, loss=1.3143]

Epoch 15 | train_loss=0.9096 | val_loss=1.1219 | val_f1_mean=0.1006 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.038599,0.040399,0.069814,0.086166,0.021256,0.106231,0.067422,0.019986,0.075911,0.025434,...,0.063102,0.119431,0.170237,0.053936,0.08267,0.059487,0.311552,0.049451,0.12603,0.098236

Epoch 16/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.48it/s, loss=1.0153]

Epoch 16 | train_loss=0.8897 | val_loss=1.1504 | val_f1_mean=0.1028 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.062871,0.047657,0.070965,0.087819,0.025455,0.096897,0.06123,0.020012,0.079128,0.027377,...,0.058412,0.134134,0.174967,0.057831,0.085177,0.056149,0.323435,0.061864,0.128975,0.121856

  → Сохранена лучшая модель (mean F1=0.1028)

Epoch 17/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.17it/s, loss=0.6757]

Epoch 17 | train_loss=0.8665 | val_loss=1.1712 | val_f1_mean=0.1033 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.052777,0.051681,0.07011,0.090155,0.02328,0.100428,0.065515,0.020634,0.083471,0.023357,...,0.06135,0.149966,0.169683,0.056387,0.088433,0.055919,0.316433,0.05529,0.141493,0.089494

  → Сохранена лучшая модель (mean F1=0.1033)

Epoch 18/100: 100%|██████████| 3929/3929 [00:20<00:00, 191.78it/s, loss=0.8014]

Epoch 18 | train_loss=0.8506 | val_loss=1.2031 | val_f1_mean=0.1065 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.047048,0.05368,0.068366,0.09281,0.023332,0.093036,0.061801,0.018936,0.084905,0.023976,...,0.068097,0.145642,0.179315,0.05632,0.088715,0.056031,0.327551,0.060293,0.145442,0.121463

  → Сохранена лучшая модель (mean F1=0.1065)

Epoch 19/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.89it/s, loss=0.9258]

Epoch 19 | train_loss=0.8361 | val_loss=1.2072 | val_f1_mean=0.1062 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.047729,0.051282,0.072803,0.093198,0.024239,0.102091,0.074782,0.019914,0.082689,0.028361,...,0.06995,0.147687,0.175885,0.058431,0.087411,0.05823,0.327603,0.055033,0.135895,0.133834

Epoch 20/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.97it/s, loss=0.7173]

Epoch 20 | train_loss=0.8163 | val_loss=1.1630 | val_f1_mean=0.1074 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.047385,0.043921,0.072328,0.089222,0.024388,0.104919,0.070503,0.020649,0.094606,0.030294,...,0.061001,0.140668,0.181205,0.0567,0.09183,0.060223,0.329413,0.05892,0.134907,0.107183

  → Сохранена лучшая модель (mean F1=0.1074)

Epoch 21/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.43it/s, loss=0.8668]

Epoch 21 | train_loss=0.8024 | val_loss=1.2892 | val_f1_mean=0.1097 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.049054,0.060108,0.071019,0.098574,0.023784,0.096825,0.06715,0.021305,0.08571,0.027192,...,0.077232,0.15853,0.178561,0.056099,0.088332,0.059215,0.332179,0.059151,0.161737,0.126996

  → Сохранена лучшая модель (mean F1=0.1097)

Epoch 22/100: 100%|██████████| 3929/3929 [00:20<00:00, 190.32it/s, loss=0.6185]

Epoch 22 | train_loss=0.7857 | val_loss=1.2426 | val_f1_mean=0.1080 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.049743,0.058049,0.07198,0.093778,0.027415,0.102053,0.085567,0.020876,0.086242,0.028487,...,0.077737,0.164114,0.175018,0.060166,0.085775,0.067363,0.320559,0.058174,0.148161,0.12843

Epoch 23/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.20it/s, loss=0.6863]

Epoch 23 | train_loss=0.7722 | val_loss=1.2801 | val_f1_mean=0.1092 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.04877,0.057248,0.073122,0.099603,0.025501,0.105407,0.076077,0.019529,0.081145,0.027646,...,0.070148,0.16079,0.17167,0.06359,0.083816,0.068586,0.31375,0.063508,0.162459,0.133552

Epoch 24/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.45it/s, loss=0.8469]

Epoch 24 | train_loss=0.7592 | val_loss=1.2546 | val_f1_mean=0.1120 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.046997,0.058106,0.072126,0.09694,0.024815,0.105049,0.079993,0.020713,0.094282,0.027467,...,0.071035,0.154071,0.178323,0.06102,0.091464,0.079053,0.325519,0.057029,0.146037,0.131489

  → Сохранена лучшая модель (mean F1=0.1120)

Epoch 25/100: 100%|██████████| 3929/3929 [00:20<00:00, 187.81it/s, loss=0.5943]

Epoch 25 | train_loss=0.7500 | val_loss=1.2640 | val_f1_mean=0.1127 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.059771,0.056051,0.071781,0.103956,0.027962,0.104814,0.08484,0.01913,0.090498,0.03101,...,0.069799,0.141585,0.178324,0.065491,0.095269,0.079793,0.333104,0.056238,0.143248,0.125564

  → Сохранена лучшая модель (mean F1=0.1127)

Epoch 26/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.30it/s, loss=1.4945]

Epoch 26 | train_loss=0.7329 | val_loss=1.3121 | val_f1_mean=0.1117 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.060813,0.056761,0.072309,0.098712,0.031254,0.104234,0.110542,0.019367,0.086224,0.030836,...,0.074379,0.16016,0.173424,0.063355,0.088011,0.073015,0.321814,0.063778,0.143623,0.137259

Epoch 27/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.88it/s, loss=0.6059]

Epoch 27 | train_loss=0.7205 | val_loss=1.3263 | val_f1_mean=0.1150 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.061129,0.067042,0.073462,0.096941,0.030293,0.102544,0.104617,0.019348,0.087057,0.027965,...,0.07603,0.153278,0.178176,0.058408,0.088597,0.085555,0.325987,0.06444,0.153532,0.143111

  → Сохранена лучшая модель (mean F1=0.1150)

Epoch 28/100: 100%|██████████| 3929/3929 [00:21<00:00, 185.80it/s, loss=1.0758]

Epoch 28 | train_loss=0.7094 | val_loss=1.3748 | val_f1_mean=0.1170 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.061779,0.060821,0.073174,0.108826,0.031686,0.102983,0.116265,0.02179,0.091432,0.031546,...,0.076539,0.168693,0.178302,0.064552,0.090826,0.08843,0.331508,0.063759,0.168603,0.146781

  → Сохранена лучшая модель (mean F1=0.1170)

Epoch 29/100: 100%|██████████| 3929/3929 [00:20<00:00, 196.07it/s, loss=0.4906]

Epoch 29 | train_loss=0.6988 | val_loss=1.3727 | val_f1_mean=0.1169 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.057958,0.059364,0.073341,0.111244,0.032549,0.100428,0.110977,0.020047,0.092736,0.029819,...,0.077578,0.162487,0.181723,0.065085,0.094121,0.085704,0.333187,0.063578,0.169828,0.127079

Epoch 30/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.61it/s, loss=0.5737]

Epoch 30 | train_loss=0.6855 | val_loss=1.3165 | val_f1_mean=0.1147 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.062018,0.057109,0.075022,0.098394,0.03073,0.108909,0.103702,0.02134,0.097882,0.033591,...,0.070599,0.142857,0.1833,0.065072,0.103608,0.085725,0.340262,0.066917,0.151353,0.14538

Epoch 31/100: 100%|██████████| 3929/3929 [00:21<00:00, 186.60it/s, loss=0.5917]

Epoch 31 | train_loss=0.6761 | val_loss=1.3877 | val_f1_mean=0.1179 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.060744,0.061114,0.073886,0.108706,0.038828,0.10988,0.115693,0.021128,0.098682,0.034304,...,0.07944,0.15321,0.178908,0.065994,0.101784,0.1006,0.333464,0.068414,0.157749,0.134905

  → Сохранена лучшая модель (mean F1=0.1179)

Epoch 32/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.43it/s, loss=0.5617]

Epoch 32 | train_loss=0.6641 | val_loss=1.3562 | val_f1_mean=0.1171 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.057343,0.058849,0.074164,0.102922,0.03116,0.10926,0.103993,0.020806,0.105316,0.032217,...,0.072243,0.141961,0.181383,0.062908,0.10191,0.091365,0.334757,0.066331,0.137705,0.136619

Epoch 33/100: 100%|██████████| 3929/3929 [00:20<00:00, 196.40it/s, loss=0.6439]

Epoch 33 | train_loss=0.6535 | val_loss=1.4253 | val_f1_mean=0.1205 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.058687,0.070395,0.074001,0.105074,0.036776,0.108278,0.11437,0.022828,0.097274,0.037844,...,0.079248,0.15784,0.184029,0.072846,0.098437,0.115431,0.330889,0.069583,0.161012,0.137798

  → Сохранена лучшая модель (mean F1=0.1205)

Epoch 34/100: 100%|██████████| 3929/3929 [00:21<00:00, 185.84it/s, loss=0.6822]

Epoch 34 | train_loss=0.6478 | val_loss=1.4566 | val_f1_mean=0.1175 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.062147,0.061664,0.073586,0.105983,0.037722,0.108787,0.111292,0.019677,0.098559,0.032638,...,0.075386,0.171239,0.188123,0.068437,0.100258,0.08516,0.340989,0.065517,0.1648,0.158918

Epoch 35/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.86it/s, loss=0.5538]

Epoch 35 | train_loss=0.6343 | val_loss=1.4721 | val_f1_mean=0.1215 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.058722,0.0669,0.07473,0.113029,0.033446,0.110849,0.116181,0.020967,0.094129,0.031513,...,0.081633,0.176495,0.178038,0.062296,0.098937,0.102079,0.334379,0.063435,0.181374,0.135862

  → Сохранена лучшая модель (mean F1=0.1215)

Epoch 36/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.35it/s, loss=0.4942]

Epoch 36 | train_loss=0.6263 | val_loss=1.4898 | val_f1_mean=0.1212 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.060807,0.065308,0.076281,0.109462,0.036224,0.108812,0.110033,0.021855,0.105502,0.034188,...,0.076674,0.150696,0.194713,0.062965,0.108433,0.11167,0.348632,0.064783,0.162141,0.153323

Epoch 37/100: 100%|██████████| 3929/3929 [00:20<00:00, 189.05it/s, loss=0.7643]

Epoch 37 | train_loss=0.6194 | val_loss=1.4965 | val_f1_mean=0.1225 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.05871,0.070734,0.075931,0.114363,0.034233,0.107772,0.118184,0.023683,0.102161,0.032177,...,0.087137,0.174785,0.179684,0.069542,0.104423,0.105104,0.340367,0.066287,0.168224,0.149185

  → Сохранена лучшая модель (mean F1=0.1225)

Epoch 38/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.14it/s, loss=0.8559]

Epoch 38 | train_loss=0.6125 | val_loss=1.5471 | val_f1_mean=0.1235 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.07462,0.073784,0.077657,0.116819,0.038115,0.108484,0.130473,0.026347,0.102925,0.03835,...,0.081798,0.175889,0.18231,0.06363,0.102213,0.123063,0.334507,0.058844,0.156017,0.165844

  → Сохранена лучшая модель (mean F1=0.1235)

Epoch 39/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.37it/s, loss=0.4888]

Epoch 39 | train_loss=0.6026 | val_loss=1.5818 | val_f1_mean=0.1256 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.070274,0.073997,0.077887,0.119229,0.038156,0.110243,0.12466,0.025904,0.104532,0.03564,...,0.094625,0.179072,0.185242,0.068765,0.101031,0.126742,0.338018,0.068333,0.185437,0.158416

  → Сохранена лучшая модель (mean F1=0.1256)

Epoch 40/100: 100%|██████████| 3929/3929 [00:20<00:00, 191.39it/s, loss=0.5943]

Epoch 40 | train_loss=0.5942 | val_loss=1.4793 | val_f1_mean=0.1246 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.06568,0.072889,0.07906,0.120252,0.036434,0.111102,0.121751,0.0238,0.105731,0.035697,...,0.08153,0.164557,0.18512,0.065531,0.107257,0.102956,0.346984,0.064482,0.165842,0.158379

Epoch 41/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.80it/s, loss=0.5626]

Epoch 41 | train_loss=0.5889 | val_loss=1.5174 | val_f1_mean=0.1259 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.068132,0.070883,0.078329,0.110368,0.035253,0.108974,0.123524,0.024662,0.103246,0.037214,...,0.089767,0.174161,0.184203,0.06729,0.103937,0.107909,0.340107,0.071577,0.165649,0.165174

  → Сохранена лучшая модель (mean F1=0.1259)

Epoch 42/100: 100%|██████████| 3929/3929 [00:20<00:00, 196.34it/s, loss=0.5879]

Epoch 42 | train_loss=0.5817 | val_loss=1.5467 | val_f1_mean=0.1264 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.060094,0.065868,0.074625,0.115392,0.035873,0.114755,0.123373,0.025949,0.107088,0.035714,...,0.082737,0.169947,0.194467,0.066647,0.106719,0.110117,0.346907,0.067235,0.167418,0.151073

  → Сохранена лучшая модель (mean F1=0.1264)

Epoch 43/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.50it/s, loss=0.5711]

Epoch 43 | train_loss=0.5705 | val_loss=1.5765 | val_f1_mean=0.1256 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.069837,0.072905,0.078991,0.122857,0.038398,0.113307,0.125834,0.022931,0.107494,0.035885,...,0.087476,0.171878,0.185878,0.066186,0.106312,0.11115,0.343903,0.063364,0.177552,0.165503

Epoch 44/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.24it/s, loss=0.6567]

Epoch 44 | train_loss=0.5639 | val_loss=1.6155 | val_f1_mean=0.1293 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.075446,0.071487,0.07953,0.119444,0.040334,0.109126,0.133728,0.024506,0.111777,0.043369,...,0.097388,0.169724,0.195446,0.070396,0.1056,0.120416,0.349037,0.074307,0.175126,0.16156

  → Сохранена лучшая модель (mean F1=0.1293)

Epoch 45/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.67it/s, loss=0.4906]

Epoch 45 | train_loss=0.5543 | val_loss=1.6440 | val_f1_mean=0.1280 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.070617,0.082735,0.078316,0.122021,0.039209,0.112972,0.126094,0.023838,0.105212,0.042471,...,0.08969,0.182055,0.1877,0.066412,0.113231,0.125236,0.344981,0.070503,0.174171,0.161621

Epoch 46/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.24it/s, loss=0.4002]

Epoch 46 | train_loss=0.5484 | val_loss=1.6533 | val_f1_mean=0.1304 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.071475,0.072591,0.079547,0.125305,0.039504,0.112826,0.133202,0.024463,0.115318,0.039864,...,0.094677,0.177923,0.193172,0.067465,0.110855,0.119403,0.343808,0.069643,0.172421,0.161538

  → Сохранена лучшая модель (mean F1=0.1304)

Epoch 47/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.89it/s, loss=0.4973]

Epoch 47 | train_loss=0.5419 | val_loss=1.6002 | val_f1_mean=0.1293 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.066481,0.070654,0.081464,0.121451,0.037787,0.118104,0.119035,0.024995,0.119407,0.041733,...,0.083825,0.153971,0.189968,0.065836,0.117392,0.113931,0.345588,0.070683,0.160994,0.161305

Epoch 48/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.06it/s, loss=0.7146]

Epoch 48 | train_loss=0.5364 | val_loss=1.7436 | val_f1_mean=0.1331 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.078802,0.074545,0.079246,0.127357,0.04066,0.113478,0.141059,0.022309,0.104694,0.041353,...,0.091297,0.190716,0.191535,0.074257,0.101803,0.12673,0.349016,0.071636,0.198418,0.179846

  → Сохранена лучшая модель (mean F1=0.1331)

Epoch 49/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.41it/s, loss=0.4911]

Epoch 49 | train_loss=0.5297 | val_loss=1.6663 | val_f1_mean=0.1322 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.065438,0.073279,0.079239,0.120923,0.03974,0.112646,0.130978,0.021257,0.119221,0.04624,...,0.097038,0.1797,0.191569,0.068316,0.115999,0.123579,0.352563,0.069728,0.190282,0.165583

Epoch 50/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.78it/s, loss=1.0282]

Epoch 50 | train_loss=0.5255 | val_loss=1.6990 | val_f1_mean=0.1327 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.063745,0.074357,0.079013,0.124395,0.041845,0.116854,0.132653,0.019516,0.110506,0.03697,...,0.096563,0.181546,0.191096,0.065713,0.112053,0.122944,0.347283,0.069111,0.185632,0.170631

Epoch 51/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.55it/s, loss=0.7182]

Epoch 51 | train_loss=0.5162 | val_loss=1.7995 | val_f1_mean=0.1343 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.065141,0.078689,0.078589,0.126323,0.04286,0.112846,0.144273,0.021545,0.10565,0.039332,...,0.091493,0.199435,0.191479,0.066943,0.10417,0.133465,0.349753,0.069144,0.192612,0.176005

  → Сохранена лучшая модель (mean F1=0.1343)

Epoch 52/100: 100%|██████████| 3929/3929 [00:19<00:00, 202.73it/s, loss=0.4319]

Epoch 52 | train_loss=0.5096 | val_loss=1.8207 | val_f1_mean=0.1320 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.078543,0.086995,0.082855,0.12737,0.040703,0.112643,0.144892,0.023319,0.108434,0.048714,...,0.095451,0.201706,0.190389,0.063745,0.106061,0.144134,0.336659,0.06755,0.189146,0.172075

Epoch 53/100: 100%|██████████| 3929/3929 [00:21<00:00, 186.48it/s, loss=0.6092]

Epoch 53 | train_loss=0.5033 | val_loss=1.8144 | val_f1_mean=0.1333 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.073226,0.07864,0.082579,0.125698,0.041779,0.115721,0.148359,0.021372,0.117334,0.041766,...,0.086498,0.194383,0.192263,0.069869,0.11498,0.134746,0.347196,0.071409,0.190722,0.173694

Epoch 54/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.48it/s, loss=0.6751]

Epoch 54 | train_loss=0.4979 | val_loss=1.8079 | val_f1_mean=0.1351 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.077014,0.080057,0.078421,0.125944,0.04304,0.115349,0.144609,0.022517,0.114603,0.046536,...,0.092915,0.185892,0.19819,0.062277,0.11082,0.122319,0.350788,0.070517,0.184104,0.17494

  → Сохранена лучшая модель (mean F1=0.1351)

Epoch 55/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.51it/s, loss=0.5791]

Epoch 55 | train_loss=0.4915 | val_loss=1.7911 | val_f1_mean=0.1360 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.075595,0.075587,0.085135,0.126289,0.040889,0.11687,0.144772,0.023736,0.11978,0.042464,...,0.093397,0.186087,0.197488,0.06827,0.116561,0.126417,0.357121,0.066591,0.19383,0.176081

  → Сохранена лучшая модель (mean F1=0.1360)

Epoch 56/100: 100%|██████████| 3929/3929 [00:21<00:00, 186.40it/s, loss=0.4509]

Epoch 56 | train_loss=0.4874 | val_loss=1.8868 | val_f1_mean=0.1363 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.082583,0.07594,0.083182,0.130499,0.044125,0.11188,0.154383,0.021776,0.117821,0.044548,...,0.094842,0.198219,0.197481,0.068116,0.116115,0.139691,0.355473,0.070312,0.193319,0.176941

  → Сохранена лучшая модель (mean F1=0.1363)

Epoch 57/100: 100%|██████████| 3929/3929 [00:19<00:00, 200.73it/s, loss=0.2975]

Epoch 57 | train_loss=0.4819 | val_loss=1.8787 | val_f1_mean=0.1376 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.073723,0.082565,0.081456,0.1333,0.045728,0.117294,0.146314,0.024419,0.112441,0.048219,...,0.100159,0.196567,0.19906,0.066211,0.113183,0.14127,0.347731,0.073816,0.200758,0.183784

  → Сохранена лучшая модель (mean F1=0.1376)

Epoch 58/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.77it/s, loss=0.4428]

Epoch 58 | train_loss=0.4788 | val_loss=1.8318 | val_f1_mean=0.1359 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.072534,0.085769,0.084201,0.138223,0.041354,0.116899,0.145753,0.022902,0.119102,0.042325,...,0.09181,0.189765,0.189196,0.064516,0.119628,0.127669,0.350624,0.072044,0.189098,0.170745

Epoch 59/100: 100%|██████████| 3929/3929 [00:20<00:00, 188.33it/s, loss=0.3325]

Epoch 59 | train_loss=0.4745 | val_loss=1.8270 | val_f1_mean=0.1374 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.068778,0.083361,0.083303,0.128249,0.040215,0.116672,0.137346,0.026028,0.128976,0.04045,...,0.09313,0.171606,0.202669,0.067176,0.124706,0.119235,0.360451,0.068155,0.189888,0.17408

Epoch 60/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.37it/s, loss=0.3103]

Epoch 60 | train_loss=0.4661 | val_loss=1.9080 | val_f1_mean=0.1378 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.079238,0.073389,0.08709,0.125893,0.048739,0.118475,0.139593,0.024561,0.133215,0.050887,...,0.091001,0.182603,0.19733,0.066829,0.130905,0.125547,0.360992,0.072903,0.187532,0.175568

  → Сохранена лучшая модель (mean F1=0.1378)

Epoch 61/100: 100%|██████████| 3929/3929 [00:19<00:00, 201.97it/s, loss=0.3828]

Epoch 61 | train_loss=0.4613 | val_loss=1.9448 | val_f1_mean=0.1387 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.077772,0.08374,0.081308,0.132983,0.045221,0.114011,0.141316,0.02593,0.125545,0.04973,...,0.09764,0.185877,0.202814,0.062415,0.121513,0.141156,0.362337,0.076864,0.184865,0.173816

  → Сохранена лучшая модель (mean F1=0.1387)

Epoch 62/100: 100%|██████████| 3929/3929 [00:20<00:00, 189.88it/s, loss=0.7812]

Epoch 62 | train_loss=0.4586 | val_loss=1.9404 | val_f1_mean=0.1391 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.080629,0.07585,0.080314,0.137335,0.051209,0.11112,0.14127,0.024617,0.127509,0.048142,...,0.093679,0.189088,0.209462,0.065841,0.123711,0.131171,0.360429,0.072023,0.198723,0.184884

  → Сохранена лучшая модель (mean F1=0.1391)

Epoch 63/100: 100%|██████████| 3929/3929 [00:19<00:00, 200.92it/s, loss=0.7296]

Epoch 63 | train_loss=0.4514 | val_loss=1.9068 | val_f1_mean=0.1391 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.074412,0.08969,0.082205,0.133836,0.04354,0.119968,0.156429,0.025917,0.118037,0.046797,...,0.100855,0.198918,0.191925,0.065911,0.118331,0.141439,0.349722,0.06866,0.200443,0.185446

Epoch 64/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.48it/s, loss=0.3779]

Epoch 64 | train_loss=0.4469 | val_loss=1.9813 | val_f1_mean=0.1412 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.080081,0.088943,0.083411,0.131613,0.048013,0.119642,0.146435,0.024698,0.128191,0.05,...,0.098794,0.194175,0.202607,0.070256,0.130747,0.144158,0.352466,0.075174,0.184339,0.172547

  → Сохранена лучшая модель (mean F1=0.1412)

Epoch 65/100: 100%|██████████| 3929/3929 [00:20<00:00, 192.01it/s, loss=0.3335]

Epoch 65 | train_loss=0.4453 | val_loss=1.9387 | val_f1_mean=0.1409 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.075636,0.088969,0.08216,0.133143,0.046792,0.12022,0.147876,0.026808,0.126976,0.04774,...,0.09817,0.189865,0.201667,0.064884,0.128246,0.130041,0.356134,0.072745,0.197656,0.179243

Epoch 66/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.35it/s, loss=0.7350]

Epoch 66 | train_loss=0.4385 | val_loss=2.0978 | val_f1_mean=0.1414 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.080513,0.086577,0.086864,0.142621,0.048461,0.113824,0.142392,0.02436,0.135501,0.055749,...,0.097577,0.193968,0.205012,0.069869,0.130057,0.136788,0.370087,0.078924,0.190652,0.177604

  → Сохранена лучшая модель (mean F1=0.1414)

Epoch 67/100: 100%|██████████| 3929/3929 [00:20<00:00, 196.32it/s, loss=0.5084]

Epoch 67 | train_loss=0.4362 | val_loss=1.9696 | val_f1_mean=0.1423 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.085853,0.087241,0.087268,0.135973,0.04776,0.122974,0.140811,0.02418,0.130982,0.049751,...,0.095392,0.188078,0.202356,0.063648,0.123918,0.129487,0.361113,0.072243,0.191602,0.194708

  → Сохранена лучшая модель (mean F1=0.1423)

Epoch 68/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.40it/s, loss=0.3634]

Epoch 68 | train_loss=0.4292 | val_loss=2.0702 | val_f1_mean=0.1424 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.083748,0.094306,0.088553,0.139214,0.047717,0.11623,0.149154,0.022078,0.11948,0.050526,...,0.10692,0.203453,0.201206,0.065884,0.11568,0.138137,0.355378,0.075377,0.198193,0.186788

  → Сохранена лучшая модель (mean F1=0.1424)

Epoch 69/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.95it/s, loss=0.2872]

Epoch 69 | train_loss=0.4260 | val_loss=2.0847 | val_f1_mean=0.1445 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.088439,0.091429,0.084055,0.139909,0.049551,0.112119,0.149101,0.026837,0.12313,0.050145,...,0.10828,0.200331,0.207909,0.065625,0.118534,0.142067,0.360456,0.071927,0.201613,0.19888

  → Сохранена лучшая модель (mean F1=0.1445)

Epoch 70/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.61it/s, loss=0.2818]

Epoch 70 | train_loss=0.4224 | val_loss=2.0399 | val_f1_mean=0.1429 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.084813,0.0912,0.087783,0.137744,0.04519,0.120161,0.149554,0.02472,0.117567,0.048793,...,0.101613,0.191065,0.203888,0.065402,0.117026,0.144928,0.350848,0.067925,0.198217,0.185088

Epoch 71/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.00it/s, loss=0.4136]

Epoch 71 | train_loss=0.4197 | val_loss=2.0776 | val_f1_mean=0.1441 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.092615,0.089026,0.089519,0.135875,0.049117,0.123671,0.152675,0.026657,0.132397,0.055293,...,0.09787,0.200556,0.205385,0.069749,0.13027,0.146896,0.355846,0.073929,0.199432,0.192818

Epoch 72/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.56it/s, loss=0.2450]

Epoch 72 | train_loss=0.4146 | val_loss=2.1469 | val_f1_mean=0.1448 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.098132,0.092368,0.085681,0.14494,0.049496,0.113633,0.154662,0.026174,0.116844,0.051056,...,0.108016,0.19924,0.206957,0.071133,0.114844,0.154934,0.353778,0.072193,0.205996,0.190671

  → Сохранена лучшая модель (mean F1=0.1448)

Epoch 73/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.09it/s, loss=0.3741]

Epoch 73 | train_loss=0.4112 | val_loss=2.0632 | val_f1_mean=0.1443 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.083745,0.0938,0.087208,0.140778,0.045301,0.120983,0.150382,0.023171,0.125275,0.048574,...,0.101167,0.195855,0.201949,0.067919,0.125091,0.139672,0.351816,0.074303,0.194175,0.184202

Epoch 74/100: 100%|██████████| 3929/3929 [00:19<00:00, 200.46it/s, loss=0.5901]

Epoch 74 | train_loss=0.4091 | val_loss=2.1089 | val_f1_mean=0.1449 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.084318,0.087625,0.088222,0.141949,0.04583,0.12004,0.150874,0.021965,0.133607,0.051712,...,0.101978,0.198995,0.21277,0.064804,0.132144,0.139758,0.362618,0.071868,0.200508,0.195464

  → Сохранена лучшая модель (mean F1=0.1449)

Epoch 75/100: 100%|██████████| 3929/3929 [00:20<00:00, 190.61it/s, loss=0.4190]

Epoch 75 | train_loss=0.4023 | val_loss=2.1633 | val_f1_mean=0.1450 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.088889,0.091308,0.0906,0.141978,0.046234,0.117001,0.153812,0.023229,0.130207,0.053625,...,0.106892,0.198969,0.20822,0.062558,0.127555,0.146764,0.360989,0.07604,0.197946,0.181928

  → Сохранена лучшая модель (mean F1=0.1450)

Epoch 76/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.80it/s, loss=0.3858]

Epoch 76 | train_loss=0.3988 | val_loss=2.0883 | val_f1_mean=0.1456 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.080925,0.088333,0.092448,0.141458,0.04368,0.12266,0.14314,0.02202,0.127929,0.044526,...,0.099846,0.186511,0.207218,0.068091,0.132793,0.135802,0.362852,0.073601,0.189057,0.187656

  → Сохранена лучшая модель (mean F1=0.1456)

Epoch 77/100: 100%|██████████| 3929/3929 [00:19<00:00, 202.06it/s, loss=0.2727]

Epoch 77 | train_loss=0.3988 | val_loss=2.1859 | val_f1_mean=0.1473 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.093441,0.090716,0.089491,0.146259,0.049686,0.122994,0.15747,0.025593,0.123583,0.050242,...,0.098573,0.203416,0.20646,0.06071,0.121773,0.153939,0.361254,0.078049,0.199943,0.204457

  → Сохранена лучшая модель (mean F1=0.1473)

Epoch 78/100: 100%|██████████| 3929/3929 [00:20<00:00, 189.90it/s, loss=0.2885]

Epoch 78 | train_loss=0.3946 | val_loss=2.1835 | val_f1_mean=0.1468 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.08864,0.084006,0.088746,0.1413,0.052038,0.119324,0.150229,0.023874,0.134401,0.052117,...,0.105474,0.203479,0.211152,0.066488,0.12865,0.141151,0.365066,0.07505,0.205585,0.194684

Epoch 79/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.60it/s, loss=0.3171]

Epoch 79 | train_loss=0.3915 | val_loss=2.1613 | val_f1_mean=0.1486 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.089459,0.084627,0.088423,0.143909,0.048504,0.12241,0.15235,0.025165,0.127625,0.0484,...,0.103994,0.197224,0.210442,0.067583,0.128517,0.143187,0.360662,0.072135,0.197898,0.202142

  → Сохранена лучшая модель (mean F1=0.1486)

Epoch 80/100: 100%|██████████| 3929/3929 [00:19<00:00, 204.82it/s, loss=0.3089]

Epoch 80 | train_loss=0.3892 | val_loss=2.2600 | val_f1_mean=0.1468 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.093688,0.105156,0.087111,0.146376,0.04439,0.114233,0.152338,0.024065,0.110034,0.047536,...,0.10859,0.214515,0.203818,0.061644,0.11572,0.147853,0.347997,0.075866,0.207573,0.202785

Epoch 81/100: 100%|██████████| 3929/3929 [00:20<00:00, 188.73it/s, loss=0.4081]

Epoch 81 | train_loss=0.3848 | val_loss=2.2070 | val_f1_mean=0.1479 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.087773,0.088323,0.08884,0.1444,0.051315,0.119269,0.154583,0.026377,0.132192,0.050929,...,0.102424,0.198611,0.214743,0.05934,0.130974,0.146886,0.363872,0.074972,0.203221,0.20202

Epoch 82/100: 100%|██████████| 3929/3929 [00:19<00:00, 200.76it/s, loss=0.5334]

Epoch 82 | train_loss=0.3811 | val_loss=2.2068 | val_f1_mean=0.1484 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.088762,0.088307,0.088718,0.144829,0.04834,0.12216,0.151888,0.025279,0.130182,0.048872,...,0.100172,0.199949,0.21277,0.063158,0.132532,0.139799,0.365916,0.078059,0.204545,0.199203

Epoch 83/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.94it/s, loss=0.3385]

Epoch 83 | train_loss=0.3804 | val_loss=2.2351 | val_f1_mean=0.1498 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.09967,0.087132,0.089772,0.143869,0.052559,0.119873,0.160584,0.02654,0.136787,0.05444,...,0.098826,0.198992,0.215698,0.068289,0.132088,0.141144,0.367568,0.075387,0.205585,0.206873

  → Сохранена лучшая модель (mean F1=0.1498)

Epoch 84/100: 100%|██████████| 3929/3929 [00:20<00:00, 190.15it/s, loss=0.3028]

Epoch 84 | train_loss=0.3758 | val_loss=2.2567 | val_f1_mean=0.1493 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.090961,0.093708,0.088694,0.143283,0.04675,0.118443,0.160371,0.024641,0.129874,0.054369,...,0.103861,0.209461,0.211363,0.062911,0.13033,0.142898,0.359411,0.079017,0.201978,0.203104

Epoch 85/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.49it/s, loss=0.3683]

Epoch 85 | train_loss=0.3738 | val_loss=2.2586 | val_f1_mean=0.1503 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.106383,0.089096,0.092851,0.144263,0.05017,0.122238,0.151836,0.023693,0.132704,0.056537,...,0.100846,0.204792,0.210465,0.067715,0.132274,0.140725,0.362611,0.079654,0.200842,0.212251

  → Сохранена лучшая модель (mean F1=0.1503)

Epoch 86/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.96it/s, loss=0.4882]

Epoch 86 | train_loss=0.3724 | val_loss=2.2617 | val_f1_mean=0.1502 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.107411,0.094159,0.092878,0.145692,0.052863,0.122553,0.151793,0.024233,0.129228,0.054615,...,0.100701,0.203046,0.209969,0.065448,0.133094,0.135744,0.363237,0.07996,0.204117,0.208288

Epoch 87/100: 100%|██████████| 3929/3929 [00:20<00:00, 189.20it/s, loss=0.4138]

Epoch 87 | train_loss=0.3686 | val_loss=2.2736 | val_f1_mean=0.1505 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.107843,0.093216,0.089608,0.143011,0.050796,0.122368,0.158858,0.02358,0.132743,0.053333,...,0.102082,0.205598,0.214478,0.063274,0.130792,0.140322,0.362416,0.076564,0.20726,0.207321

  → Сохранена лучшая модель (mean F1=0.1505)

Epoch 88/100: 100%|██████████| 3929/3929 [00:19<00:00, 200.72it/s, loss=0.3476]

Epoch 88 | train_loss=0.3681 | val_loss=2.2792 | val_f1_mean=0.1505 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.101948,0.096892,0.091051,0.147051,0.049617,0.12146,0.151413,0.026568,0.131947,0.052138,...,0.107465,0.210888,0.214954,0.062036,0.13113,0.150599,0.362254,0.077792,0.201223,0.204616

Epoch 89/100: 100%|██████████| 3929/3929 [00:19<00:00, 198.39it/s, loss=0.4623]

Epoch 89 | train_loss=0.3665 | val_loss=2.2977 | val_f1_mean=0.1515 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.108742,0.092617,0.091026,0.145066,0.050409,0.121134,0.15419,0.02566,0.131548,0.058988,...,0.104909,0.205906,0.214513,0.066986,0.131966,0.146659,0.365772,0.078185,0.206024,0.208165

  → Сохранена лучшая модель (mean F1=0.1515)

Epoch 90/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.01it/s, loss=0.3570]

Epoch 90 | train_loss=0.3654 | val_loss=2.3695 | val_f1_mean=0.1514 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.103389,0.090523,0.091891,0.14665,0.053454,0.116881,0.155485,0.02389,0.141797,0.05498,...,0.105227,0.205231,0.216703,0.062246,0.138303,0.146999,0.372405,0.080636,0.19697,0.202594

Epoch 91/100: 100%|██████████| 3929/3929 [00:19<00:00, 202.18it/s, loss=0.5662]

Epoch 91 | train_loss=0.3625 | val_loss=2.3107 | val_f1_mean=0.1510 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.098226,0.096975,0.090596,0.147583,0.05167,0.124848,0.153003,0.025181,0.133353,0.055219,...,0.105688,0.200457,0.21271,0.062123,0.130747,0.147374,0.360229,0.078628,0.201891,0.204685

Epoch 92/100: 100%|██████████| 3929/3929 [00:19<00:00, 199.58it/s, loss=0.2231]

Epoch 92 | train_loss=0.3608 | val_loss=2.3062 | val_f1_mean=0.1513 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.10421,0.095112,0.088238,0.14467,0.051637,0.122343,0.155914,0.023117,0.130624,0.050993,...,0.104152,0.20805,0.215774,0.062813,0.134787,0.147849,0.3642,0.080083,0.200059,0.208868

Epoch 93/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.60it/s, loss=0.2369]

Epoch 93 | train_loss=0.3579 | val_loss=2.3250 | val_f1_mean=0.1519 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.105335,0.091071,0.090909,0.147604,0.053376,0.122915,0.157883,0.025526,0.137166,0.053449,...,0.105556,0.202786,0.215686,0.060554,0.136497,0.145902,0.368686,0.077894,0.206607,0.205861

  → Сохранена лучшая модель (mean F1=0.1519)

Epoch 94/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.86it/s, loss=0.3414]

Epoch 94 | train_loss=0.3568 | val_loss=2.3018 | val_f1_mean=0.1513 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.097179,0.09379,0.09182,0.145464,0.052045,0.124063,0.15197,0.022904,0.136701,0.052725,...,0.101509,0.201349,0.215584,0.05978,0.13971,0.142082,0.366345,0.077227,0.201243,0.202869

Epoch 95/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.77it/s, loss=0.3240]

Epoch 95 | train_loss=0.3541 | val_loss=2.3430 | val_f1_mean=0.1525 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.107335,0.093259,0.091878,0.146308,0.056338,0.124547,0.154276,0.025641,0.138943,0.059455,...,0.102737,0.20675,0.216307,0.062139,0.138528,0.149944,0.36858,0.078994,0.201932,0.207418

  → Сохранена лучшая модель (mean F1=0.1525)

Epoch 96/100: 100%|██████████| 3929/3929 [00:19<00:00, 196.46it/s, loss=0.2966]

Epoch 96 | train_loss=0.3539 | val_loss=2.3315 | val_f1_mean=0.1523 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.104635,0.09167,0.091079,0.146348,0.052684,0.123486,0.156871,0.023791,0.137734,0.056383,...,0.102668,0.202928,0.217822,0.064884,0.139407,0.146395,0.368035,0.079844,0.200176,0.208046

Epoch 97/100: 100%|██████████| 3929/3929 [00:20<00:00, 195.56it/s, loss=0.2842]

Epoch 97 | train_loss=0.3539 | val_loss=2.3363 | val_f1_mean=0.1520 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.09879,0.097978,0.09128,0.146948,0.052136,0.121304,0.15712,0.021946,0.133233,0.052478,...,0.106608,0.210868,0.216121,0.063492,0.135143,0.144791,0.364033,0.08071,0.199814,0.208966

Epoch 98/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.40it/s, loss=0.2562]

Epoch 98 | train_loss=0.3536 | val_loss=2.3250 | val_f1_mean=0.1521 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.101249,0.093085,0.091896,0.1465,0.052976,0.123575,0.153947,0.022857,0.135123,0.054484,...,0.104752,0.205729,0.21689,0.06286,0.135769,0.144009,0.36661,0.079253,0.201569,0.20874

Epoch 99/100: 100%|██████████| 3929/3929 [00:19<00:00, 203.02it/s, loss=0.2736]

Epoch 99 | train_loss=0.3516 | val_loss=2.3463 | val_f1_mean=0.1524 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.104131,0.095413,0.092678,0.14726,0.054795,0.122018,0.157108,0.023059,0.132417,0.055194,...,0.106744,0.205969,0.215652,0.061846,0.135493,0.145816,0.3652,0.080245,0.199507,0.212344

Epoch 100/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.12it/s, loss=0.3046]

Epoch 100 | train_loss=0.3514 | val_loss=2.3460 | val_f1_mean=0.1527 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.105189,0.094096,0.09191,0.148685,0.055405,0.122301,0.156801,0.023121,0.133233,0.055491,...,0.106055,0.206915,0.215204,0.060909,0.135058,0.147186,0.365173,0.080461,0.203287,0.211867

  → Сохранена лучшая модель (mean F1=0.1527)

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.105189,0.094096,0.09191,0.148685,0.055405,0.122301,0.156801,0.023121,0.133233,0.055491,...,0.106055,0.206915,0.215204,0.060909,0.135058,0.147186,0.365173,0.080461,0.203287,0.211867

In [44]:
from huggingface_hub import snapshot_download

print("📥 Скачивание модели...")
model_path = snapshot_download(
    repo_id=MODEL_NAME,
    local_dir=MODEL_DIR,
)

📥 Скачивание модели...

Fetching 13 files: 100%|██████████| 13/13 [00:00<00:00, 777.98it/s]

In [45]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR, num_labels=len(le.categories_[0]), local_files_only=True)
model.to(DEVICE)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 9983.18it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: models/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=42, bias=True)
  )
)

In [47]:
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = AdamW(model.parameters(), lr=LR, weight_decay=0.01)
model.to(DEVICE)

training(
    model=model,
    train_data_loader=train_dl,
    val_data_loader=val_dl,
    optimizer=optimizer,
    epoches=EPOCHS,
    criterion=criterion,
    tokenizator=le,
    accum_steps=ACCUM_STEPS,
    warmup_frac=WARMUP_FRAC,
    device=DEVICE,
    save_path=SAVE_PATH,
    )

Epoch 1/100: 100%|██████████| 3929/3929 [18:31<00:00,  3.54it/s, loss=0.8248]

Epoch 1 | train_loss=1.2622 | val_loss=0.9502 | val_f1_mean=0.1363 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.077277,0.040941,0.0826,0.164804,0.054297,0.107239,0.111209,0.080032,0.126306,0.029454,...,0.063844,0.164963,0.315234,0.031488,0.157666,0.048974,0.38517,0.084747,0.160403,0.112924

  → Сохранена лучшая модель (mean F1=0.1363)

Epoch 2/100: 100%|██████████| 3929/3929 [18:38<00:00,  3.51it/s, loss=0.5479]

Epoch 2 | train_loss=0.8181 | val_loss=0.6656 | val_f1_mean=0.2305 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.13674,0.096061,0.131881,0.318536,0.089458,0.210967,0.271674,0.1072,0.249811,0.077849,...,0.157074,0.276371,0.410251,0.065883,0.404624,0.132207,0.504477,0.098958,0.249289,0.179717

  → Сохранена лучшая модель (mean F1=0.2305)

Epoch 3/100: 100%|██████████| 3929/3929 [18:14<00:00,  3.59it/s, loss=0.5391]

Epoch 3 | train_loss=0.6053 | val_loss=0.5047 | val_f1_mean=0.3555 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.334917,0.244456,0.205545,0.427471,0.276334,0.362093,0.35558,0.25229,0.38076,0.204404,...,0.276085,0.306611,0.608225,0.093182,0.525531,0.26094,0.648783,0.16893,0.275,0.230603

  → Сохранена лучшая модель (mean F1=0.3555)

Epoch 4/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.2609]

Epoch 4 | train_loss=0.4510 | val_loss=0.3833 | val_f1_mean=0.4042 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.301486,0.248491,0.288142,0.456611,0.268886,0.40017,0.350116,0.253199,0.467799,0.269578,...,0.337596,0.35315,0.771375,0.10488,0.560128,0.270096,0.720711,0.218599,0.307125,0.246138

  → Сохранена лучшая модель (mean F1=0.4042)

Epoch 5/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.3381]

Epoch 5 | train_loss=0.3440 | val_loss=0.3122 | val_f1_mean=0.4256 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.282524,0.231054,0.250467,0.460543,0.271718,0.432962,0.399173,0.213531,0.508812,0.275915,...,0.4,0.387852,0.845192,0.139995,0.572584,0.283288,0.787335,0.270957,0.353305,0.277793

  → Сохранена лучшая модель (mean F1=0.4256)

Epoch 6/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.1480]

Epoch 6 | train_loss=0.2706 | val_loss=0.2737 | val_f1_mean=0.4860 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.352,0.262552,0.440107,0.470692,0.302496,0.44951,0.46807,0.381783,0.620301,0.277317,...,0.435256,0.42592,0.807782,0.191538,0.652912,0.292599,0.83893,0.309453,0.402184,0.386792

  → Сохранена лучшая модель (mean F1=0.4860)

Epoch 7/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.1458]

Epoch 7 | train_loss=0.2194 | val_loss=0.2699 | val_f1_mean=0.5407 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.504007,0.387443,0.428979,0.47322,0.385496,0.552028,0.476568,0.467312,0.66599,0.28046,...,0.43483,0.473361,0.849078,0.176351,0.752155,0.443815,0.83209,0.416329,0.426319,0.449256

  → Сохранена лучшая модель (mean F1=0.5407)

Epoch 8/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.1324]

Epoch 8 | train_loss=0.1814 | val_loss=0.2557 | val_f1_mean=0.5507 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.544031,0.486486,0.5,0.500906,0.390873,0.510818,0.460047,0.428078,0.677669,0.311847,...,0.505718,0.517857,0.870067,0.18624,0.742464,0.401266,0.868538,0.391239,0.452844,0.412909

  → Сохранена лучшая модель (mean F1=0.5507)

Epoch 9/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.0840]

Epoch 9 | train_loss=0.1519 | val_loss=0.2856 | val_f1_mean=0.5916 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.609784,0.69219,0.460066,0.53493,0.430131,0.601557,0.486875,0.649057,0.706906,0.365931,...,0.500317,0.488534,0.84398,0.208065,0.714214,0.428137,0.868288,0.40236,0.42582,0.550986

  → Сохранена лучшая модель (mean F1=0.5916)

Epoch 10/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.2026]

Epoch 10 | train_loss=0.1289 | val_loss=0.3028 | val_f1_mean=0.6246 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.596983,0.587224,0.48158,0.597879,0.512821,0.542004,0.494938,0.641711,0.808917,0.379421,...,0.616006,0.533589,0.850278,0.244839,0.810215,0.44575,0.855976,0.431454,0.463735,0.590629

  → Сохранена лучшая модель (mean F1=0.6246)

Epoch 11/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.0847]

Epoch 11 | train_loss=0.1098 | val_loss=0.3088 | val_f1_mean=0.6210 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.557214,0.5975,0.511969,0.559688,0.479275,0.598184,0.528497,0.560976,0.688285,0.395951,...,0.63837,0.509358,0.857143,0.28691,0.779436,0.48722,0.871405,0.517241,0.461767,0.608807

Epoch 12/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.1206]

Epoch 12 | train_loss=0.0918 | val_loss=0.3588 | val_f1_mean=0.6476 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.715673,0.559524,0.530626,0.637899,0.466916,0.643719,0.588951,0.699411,0.752018,0.3878,...,0.694073,0.543384,0.892578,0.306804,0.818824,0.500549,0.858274,0.458396,0.467148,0.643759

  → Сохранена лучшая модель (mean F1=0.6476)

Epoch 13/100: 100%|██████████| 3929/3929 [18:27<00:00,  3.55it/s, loss=0.0406]

Epoch 13 | train_loss=0.0784 | val_loss=0.3942 | val_f1_mean=0.6653 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.690217,0.697389,0.57816,0.583446,0.521008,0.641289,0.561602,0.698413,0.767878,0.446475,...,0.645602,0.535427,0.890905,0.373832,0.774973,0.535671,0.879918,0.500835,0.474011,0.632639

  → Сохранена лучшая модель (mean F1=0.6653)

Epoch 14/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0550]

Epoch 14 | train_loss=0.0681 | val_loss=0.4147 | val_f1_mean=0.6766 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.685185,0.647462,0.619662,0.586754,0.58194,0.609003,0.588563,0.729167,0.827586,0.57193,...,0.6787,0.557785,0.900749,0.326132,0.839685,0.580818,0.87726,0.500208,0.484051,0.64969

  → Сохранена лучшая модель (mean F1=0.6766)

Epoch 15/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0382]

Epoch 15 | train_loss=0.0583 | val_loss=0.4909 | val_f1_mean=0.6901 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.647783,0.716418,0.565156,0.632834,0.601942,0.627152,0.613715,0.664165,0.829457,0.515432,...,0.757642,0.604801,0.896154,0.407231,0.852704,0.577252,0.878888,0.594566,0.520499,0.68393

  → Сохранена лучшая модель (mean F1=0.6901)

Epoch 16/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0224]

Epoch 16 | train_loss=0.0505 | val_loss=0.5152 | val_f1_mean=0.6990 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.733997,0.67356,0.636364,0.672935,0.619137,0.605305,0.658797,0.759825,0.749283,0.566102,...,0.681199,0.574655,0.896602,0.395732,0.830918,0.57262,0.904431,0.593632,0.50187,0.611959

  → Сохранена лучшая модель (mean F1=0.6990)

Epoch 17/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0454]

Epoch 17 | train_loss=0.0444 | val_loss=0.5465 | val_f1_mean=0.6989 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.703956,0.715421,0.642762,0.632982,0.593573,0.653003,0.605946,0.714876,0.845797,0.585821,...,0.721022,0.572996,0.903447,0.45145,0.846154,0.587222,0.890066,0.56189,0.519859,0.672527

Epoch 18/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0219]

Epoch 18 | train_loss=0.0397 | val_loss=0.5915 | val_f1_mean=0.7062 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.745562,0.742475,0.641656,0.653784,0.56314,0.684431,0.629261,0.754098,0.828701,0.518072,...,0.747845,0.600994,0.895573,0.413574,0.860902,0.55375,0.899933,0.549685,0.521895,0.687596

  → Сохранена лучшая модель (mean F1=0.7062)

Epoch 19/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0159]

Epoch 19 | train_loss=0.0343 | val_loss=0.6655 | val_f1_mean=0.7220 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.761146,0.714055,0.648697,0.665991,0.595194,0.657133,0.675245,0.772834,0.822335,0.554007,...,0.739459,0.613508,0.902256,0.419936,0.877238,0.600295,0.881596,0.558396,0.522321,0.704293

  → Сохранена лучшая модель (mean F1=0.7220)

Epoch 20/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0103]

Epoch 20 | train_loss=0.0314 | val_loss=0.6978 | val_f1_mean=0.7236 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.753049,0.707006,0.665069,0.667368,0.588679,0.655391,0.679223,0.775056,0.798503,0.635983,...,0.724761,0.620336,0.892432,0.403226,0.890402,0.594828,0.899933,0.554985,0.521267,0.719611

  → Сохранена лучшая модель (mean F1=0.7236)

Epoch 21/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0044]

Epoch 21 | train_loss=0.0290 | val_loss=0.7204 | val_f1_mean=0.7234 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.712843,0.736111,0.632378,0.680912,0.61477,0.7194,0.647242,0.747788,0.868659,0.585455,...,0.760596,0.620133,0.90651,0.416,0.882431,0.601455,0.869031,0.597701,0.532251,0.673529

Epoch 22/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0295]

Epoch 22 | train_loss=0.0259 | val_loss=0.7053 | val_f1_mean=0.7228 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.623853,0.643258,0.668582,0.672286,0.602837,0.704747,0.638111,0.720648,0.857334,0.592734,...,0.743644,0.63057,0.91214,0.411701,0.877193,0.62342,0.899893,0.571885,0.535797,0.673396

Epoch 23/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0165]

Epoch 23 | train_loss=0.0228 | val_loss=0.8798 | val_f1_mean=0.7363 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.753532,0.713816,0.690625,0.684932,0.604128,0.731665,0.63707,0.788599,0.866941,0.591006,...,0.697765,0.64008,0.906021,0.431871,0.872449,0.594075,0.889265,0.61857,0.528801,0.727273

  → Сохранена лучшая модель (mean F1=0.7363)

Epoch 24/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0097]

Epoch 24 | train_loss=0.0214 | val_loss=0.8657 | val_f1_mean=0.7389 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.75,0.737828,0.665405,0.717586,0.616,0.708333,0.645485,0.77619,0.866988,0.614481,...,0.715578,0.636408,0.906811,0.445813,0.871795,0.571238,0.905429,0.601719,0.558676,0.716443

  → Сохранена лучшая модель (mean F1=0.7389)

Epoch 25/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0093]

Epoch 25 | train_loss=0.0197 | val_loss=0.9402 | val_f1_mean=0.7408 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.728838,0.726316,0.6605,0.714037,0.633065,0.716211,0.663546,0.75395,0.866207,0.643991,...,0.75162,0.651139,0.906988,0.456897,0.870988,0.591075,0.899134,0.630491,0.578742,0.717264

  → Сохранена лучшая модель (mean F1=0.7408)

Epoch 26/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0182]

Epoch 26 | train_loss=0.0185 | val_loss=0.9255 | val_f1_mean=0.7361 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.76748,0.754789,0.618273,0.696075,0.599206,0.702637,0.669643,0.762353,0.881308,0.585635,...,0.757642,0.640201,0.903273,0.422741,0.861748,0.599641,0.907506,0.588705,0.593541,0.710145

Epoch 27/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0020]

Epoch 27 | train_loss=0.0160 | val_loss=0.9347 | val_f1_mean=0.7409 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.752656,0.729875,0.694836,0.716201,0.582456,0.712634,0.667531,0.746067,0.883191,0.59387,...,0.733471,0.657909,0.90411,0.421717,0.888451,0.575589,0.910292,0.637887,0.576253,0.731317

  → Сохранена лучшая модель (mean F1=0.7409)

Epoch 28/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0010]

Epoch 28 | train_loss=0.0155 | val_loss=1.0613 | val_f1_mean=0.7462 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.772803,0.75,0.67243,0.692593,0.608163,0.737488,0.672909,0.78,0.875261,0.615694,...,0.742004,0.651386,0.909136,0.446309,0.880568,0.609952,0.895916,0.606242,0.582436,0.71875

  → Сохранена лучшая модель (mean F1=0.7462)

Epoch 29/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0021]

Epoch 29 | train_loss=0.0140 | val_loss=1.0284 | val_f1_mean=0.7436 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.741194,0.719424,0.675835,0.694351,0.641975,0.736888,0.68614,0.778325,0.872752,0.618337,...,0.73774,0.665914,0.906588,0.444772,0.888298,0.606061,0.903252,0.623507,0.576923,0.714516

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.741194,0.719424,0.675835,0.694351,0.641975,0.736888,0.68614,0.778325,0.872752,0.618337,...,0.73774,0.665914,0.906588,0.444772,0.888298,0.606061,0.903252,0.623507,0.576923,0.714516

In [21]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR, num_labels=len(le.categories_[0]), local_files_only=True)
model.load_state_dict(torch.load('news_classifier_roberta-base_best.pt', weights_only=True))
model.to(DEVICE)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 10640.92it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: models/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=42, bias=True)
  )
)

In [22]:
model.eval()

pred_labels, mask_labels = [], []

with torch.no_grad():
    for batch in val_dl:
        log = model(batch['input_ids'].to(DEVICE), batch['attention_mask'].to(DEVICE)).logits
        pred_labels.append((torch.sigmoid(log) > 0.5).to('cpu').numpy())
        mask_labels.append(batch['labels'].numpy())
    
    pred_labels = np.vstack(pred_labels)
    mask_labels = np.vstack(mask_labels)
    
    print(classification_report(mask_labels, pred_labels, target_names=le.categories_[0]))

                precision    recall  f1-score   support

          ARTS       0.76      0.80      0.78       302
ARTS & CULTURE       0.79      0.74      0.76       268
  BLACK VOICES       0.68      0.74      0.71       917
      BUSINESS       0.66      0.78      0.72      1198
       COLLEGE       0.63      0.60      0.62       229
        COMEDY       0.74      0.75      0.74      1080
         CRIME       0.63      0.74      0.68       713
CULTURE & ARTS       0.87      0.75      0.81       214
       DIVORCE       0.86      0.91      0.89       685
     EDUCATION       0.63      0.68      0.66       202
 ENTERTAINMENT       0.84      0.88      0.86      3473
   ENVIRONMENT       0.65      0.76      0.70       288
         FIFTY       0.77      0.75      0.76       280
  FOOD & DRINK       0.89      0.93      0.91      1268
     GOOD NEWS       0.71      0.65      0.68       280
         GREEN       0.60      0.74      0.67       524
HEALTHY LIVING       0.75      0.83      0.79      1339
 HOME & LIVING       0.90      0.92      0.91       864
        IMPACT       0.56      0.61      0.58       697
 LATINO VOICES       0.74      0.75      0.74       226
         MEDIA       0.68      0.73      0.70       589
         MONEY       0.74      0.73      0.73       351
     PARENTING       0.86      0.90      0.88      1758
       PARENTS       0.76      0.84      0.80       791
      POLITICS       0.86      0.89      0.87      7120
  QUEER VOICES       0.86      0.88      0.87      1269
      RELIGION       0.72      0.75      0.73       516
       SCIENCE       0.71      0.74      0.72       441
        SPORTS       0.81      0.88      0.84      1016
         STYLE       0.82      0.87      0.84       451
STYLE & BEAUTY       0.94      0.94      0.94      1962
         TASTE       0.84      0.85      0.84       419
          TECH       0.78      0.76      0.77       420
 THE WORLDPOST       0.70      0.68      0.69       733
        TRAVEL       0.91      0.92      0.92      1980
     U.S. NEWS       0.48      0.47      0.48       275
      WEDDINGS       0.85      0.92      0.89       731
    WEIRD NEWS       0.59      0.63      0.61       556
      WELLNESS       0.90      0.93      0.91      3588
         WOMEN       0.65      0.63      0.64       714
    WORLD NEWS       0.56      0.67      0.61       660
     WORLDPOST       0.64      0.83      0.72       516

     micro avg       0.80      0.84      0.82     41903
     macro avg       0.75      0.78      0.76     41903
  weighted avg       0.80      0.84      0.82     41903
   samples avg       0.82      0.84      0.83     41903

d:\Python\Learning\NLP_Classification\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [24]:
test_ids, test_masks = batch_tokenization(tokenizer=tokenizer, texts=test_X.to_list())
test_labels = le.transform(test_y).toarray()

test_ds = TextDataset(test_ids, test_masks, test_labels)
test_dl = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True)

model.eval()

pred_labels, mask_labels = [], []

with torch.no_grad():
    for batch in test_dl:
        log = model(batch['input_ids'].to(DEVICE), batch['attention_mask'].to(DEVICE)).logits
        pred_labels.append((torch.sigmoid(log) > 0.5).to('cpu').numpy())
        mask_labels.append(batch['labels'].numpy())
    
    pred_labels = np.vstack(pred_labels)
    mask_labels = np.vstack(mask_labels)
    
    print(classification_report(mask_labels, pred_labels, target_names=le.categories_[0]))

Токенизация: 100%|██████████| 9/9 [00:06<00:00,  1.35it/s]

                precision    recall  f1-score   support

          ARTS       0.76      0.81      0.79       302
ARTS & CULTURE       0.79      0.73      0.76       268
  BLACK VOICES       0.69      0.72      0.71       916
      BUSINESS       0.63      0.80      0.70      1199
       COLLEGE       0.68      0.71      0.70       229
        COMEDY       0.75      0.76      0.76      1080
         CRIME       0.66      0.74      0.70       712
CULTURE & ARTS       0.84      0.77      0.81       215
       DIVORCE       0.86      0.90      0.88       685
     EDUCATION       0.64      0.69      0.66       203
 ENTERTAINMENT       0.84      0.88      0.86      3472
   ENVIRONMENT       0.66      0.81      0.73       289
         FIFTY       0.76      0.78      0.77       280
  FOOD & DRINK       0.90      0.93      0.92      1268
     GOOD NEWS       0.67      0.63      0.65       279
         GREEN       0.60      0.71      0.65       525
HEALTHY LIVING       0.74      0.79      0.77      1339
 HOME & LIVING       0.92      0.90      0.91       864
        IMPACT       0.55      0.61      0.58       697
 LATINO VOICES       0.78      0.78      0.78       226
         MEDIA       0.68      0.72      0.70       589
         MONEY       0.81      0.74      0.77       351
     PARENTING       0.86      0.91      0.89      1758
       PARENTS       0.78      0.84      0.81       791
      POLITICS       0.86      0.90      0.88      7120
  QUEER VOICES       0.84      0.88      0.86      1270
      RELIGION       0.74      0.76      0.75       515
       SCIENCE       0.73      0.75      0.74       441
        SPORTS       0.83      0.91      0.87      1015
         STYLE       0.82      0.86      0.84       451
STYLE & BEAUTY       0.94      0.94      0.94      1962
         TASTE       0.82      0.85      0.84       419
          TECH       0.72      0.72      0.72       420
 THE WORLDPOST       0.68      0.67      0.68       733
        TRAVEL       0.90      0.92      0.91      1980
     U.S. NEWS       0.48      0.45      0.47       276
      WEDDINGS       0.88      0.93      0.90       730
    WEIRD NEWS       0.64      0.65      0.64       555
      WELLNESS       0.90      0.93      0.91      3589
         WOMEN       0.63      0.61      0.62       714
    WORLD NEWS       0.59      0.71      0.64       660
     WORLDPOST       0.70      0.83      0.76       516

     micro avg       0.80      0.84      0.82     41903
     macro avg       0.75      0.78      0.77     41903
  weighted avg       0.80      0.84      0.82     41903
   samples avg       0.82      0.84      0.83     41903

d:\Python\Learning\NLP_Classification\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])