In [16]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [17]:
import numpy as np
import pandas as pd
import random
from pathlib import Path
import sys
import json

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import StratifiedKFold, train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from tqdm import tqdm
from torch.optim import AdamW
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import f1_score, classification_report
from transformers import get_linear_schedule_with_warmup

from catboost import CatBoostClassifier
import torch.nn as nn
import torch

In [18]:
project_root = Path().resolve().parent

# добавляем в sys.path
sys.path.append(str(project_root))

from core.graf import *
from core.func import *
from core.nn_models import *

In [19]:
# ── Конфиг ──────────────────────────────────────────────────────────────────
DATA_PATH           = '../data/News_Category_Dataset_v3.json'
MODEL_NAME          = 'roberta-base' # 'cointegrated/rubert-tiny2'
MODEL_DIR           = f'models/{MODEL_NAME.split("/")[-1]}' 
SAVE_PATH           = f'news_classifier_{MODEL_NAME.split("/")[-1]}'
MAX_LEN             = 500
BATCH_SIZE          = 32
EPOCHS              = 100
ACCUM_STEPS         = 4
WARMUP_FRAC         = 0.1
LR                  = 2e-5
SEED                = 42
DEVICE              = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if torch.cuda.is_available():
    print("GPU: ", torch.cuda.get_device_name())
    print("VRAM:", round(torch.cuda.get_device_properties().total_memory / 1e9, 1),  'Gb')

random.seed(SEED)
torch.manual_seed(SEED)
np.random.seed(SEED)

GPU:  NVIDIA GeForce RTX 5070
VRAM: 12.8 Gb

In [20]:
with open(DATA_PATH, 'r') as file:
    data = pd.DataFrame([json.loads(line) for line in file])

data.sample(5)

,link,headline,category,short_description,authors,date
128310,https://www.huffingtonpost.com/entry/what-if-w...,What If We Were All Family Generation Changers?,IMPACT,"What if, in doing so, we won't just create new...","Matt Murrie, ContributorEdupreneur, Cofounder/...",2014-06-20
139983,https://www.huffingtonpost.comhttp://www.washi...,Firestorm At AOL Over Employee Benefit Cuts,BUSINESS,It should have been a glorious week for AOL ch...,,2014-02-08
42339,https://www.huffingtonpost.com/entry/time-runs...,Dakota Access Protesters Arrested As Deadline ...,POLITICS,A few protesters who refused to leave remained...,"Michael McLaughlin & Josh Morgan, The Huffingt...",2017-02-22
131494,https://www.huffingtonpost.com/entry/one-glimp...,One Glimpse Of These Baby Kit Foxes And You'll...,GREEN,,,2014-05-14
163649,https://www.huffingtonpost.com/entry/mens-swea...,"Mens' Sweat Pheromone, Androstadienone, Influe...",SCIENCE,Scientists didn't know if humans played that g...,Melissa Cronin,2013-06-02

In [21]:
preprocesed_data = data.copy()
preprocesed_data.drop_duplicates(inplace=True)
preprocesed_data["headline"] = preprocesed_data["headline"].str.replace("’", "'")
preprocesed_data["short_description"] = preprocesed_data["short_description"].str.replace("’", "'")
preprocesed_data["input_text"] = preprocesed_data["headline"] + " [SEP] " + preprocesed_data["authors"] + " [SEP] " + preprocesed_data["short_description"]
y = preprocesed_data[["category"]]
X = preprocesed_data["input_text"]

In [22]:
train_X, val_X, train_y, val_y = train_test_split(X, y, test_size=0.4, random_state=SEED, shuffle=True, stratify=y)
val_X, test_X, val_y, test_y = train_test_split(val_X, val_y, test_size=0.5, random_state=SEED, shuffle=True, stratify=val_y)

In [23]:
# ── Dataset с претокенизацией ─────────────────────────────────────────────────
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
le = OneHotEncoder() # LabelEncoder()

def batch_tokenization(tokenizer, texts, desc: str = "Токенизация", batch_size: int = 5000):
    all_ids, all_masks = [], []
    for i in tqdm(range(0, len(texts), batch_size), desc=desc):
        tokens = tokenizer(
            texts[i : i+batch_size],
            max_length=MAX_LEN,
            padding="max_length",
            truncation=True,
            return_tensors='pt'
        )
        all_ids.append(tokens["input_ids"])
        all_masks.append(tokens["attention_mask"])
    return torch.cat(all_ids), torch.cat(all_masks)

In [24]:
train_ids, train_masks = batch_tokenization(tokenizer=tokenizer, texts=train_X.to_list())
train_labels = le.fit_transform(train_y).toarray()
train_labels

Токенизация: 100%|██████████| 26/26 [00:20<00:00,  1.25it/s]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(125708, 42))

In [25]:
counts = train_labels.sum(axis=0)

pos_weight = torch.tensor([(len(train_labels) - c) / c for c in counts], dtype=torch.float).to(DEVICE)
print('pos_weight:', pos_weight)

pos_weight: tensor([137.9039, 155.5479,  44.7120,  33.9675, 182.2478,  37.7988,  57.8245,
        193.8961,  60.1420, 205.4171,  11.0676, 144.1593, 148.4744,  32.0463,
        148.8307,  78.9161,  30.3018,  47.4985,  59.1474, 184.4100,  70.1823,
        118.2676,  22.8309,  51.9743,   4.8849,  32.0116,  80.3118,  93.9456,
         40.2699,  91.9793,  20.3535,  98.9269,  98.7683,  56.1920,  20.1630,
        151.1889,  56.3485,  74.4550,  10.6775,  57.6598,  62.5210,  80.2592],
       device='cuda:0')

In [26]:
train_ds = TextDataset(train_ids, train_masks, train_labels)
train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True)

In [27]:
val_ids, val_masks = batch_tokenization(tokenizer=tokenizer, texts=val_X.to_list())
val_labels = le.transform(val_y).toarray()

val_ds = TextDataset(val_ids, val_masks, val_labels)
val_dl = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True)

Токенизация: 100%|██████████| 9/9 [00:06<00:00,  1.31it/s]

In [32]:
lstm_model = LSTM_Classifier(num_classes=len(le.categories_[0]),
                             vocab_size=len(tokenizer.get_vocab()),
                             embedding_dim=256,
                             lstm_units=64,
                             num_layers=1,
                             )

In [33]:
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = AdamW(lstm_model.parameters(), lr=0.001, weight_decay=0.01)
lstm_model.to(DEVICE)

training(
    model=lstm_model,
    train_data_loader=train_dl,
    val_data_loader=val_dl,
    optimizer=optimizer,
    epoches=EPOCHS,
    criterion=criterion,
    tokenizator=le,
    accum_steps=ACCUM_STEPS,
    warmup_frac=WARMUP_FRAC,
    device=DEVICE
    )

Epoch 1/100: 100%|██████████| 3929/3929 [00:30<00:00, 130.51it/s, loss=1.2559]

Epoch 1 | train_loss=1.3381 | val_loss=1.2785 | val_f1_mean=0.0678 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.045263,0.01827,0.052476,0.057848,0.015768,0.083439,0.050031,0.018276,0.056818,0.019045,...,0.02572,0.063757,0.145253,0.024345,0.061012,0.057307,0.259575,0.03581,0.051921,0.058248

  → Сохранена лучшая модель (mean F1=0.0678)

Epoch 2/100: 100%|██████████| 3929/3929 [00:29<00:00, 132.18it/s, loss=0.9979]

Epoch 2 | train_loss=1.1787 | val_loss=1.0800 | val_f1_mean=0.0873 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.042772,0.032739,0.064169,0.076159,0.019496,0.103862,0.065129,0.018698,0.071062,0.028948,...,0.029541,0.082064,0.166267,0.052545,0.07951,0.058505,0.302491,0.048738,0.100636,0.080466

  → Сохранена лучшая модель (mean F1=0.0873)

Epoch 3/100: 100%|██████████| 3929/3929 [00:29<00:00, 132.42it/s, loss=0.8644]

Epoch 3 | train_loss=0.9563 | val_loss=0.8772 | val_f1_mean=0.1188 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.064329,0.048524,0.076543,0.113208,0.032802,0.118772,0.106762,0.025751,0.100355,0.051037,...,0.048459,0.136867,0.210202,0.075973,0.103534,0.065492,0.435096,0.082451,0.15135,0.111233

  → Сохранена лучшая модель (mean F1=0.1188)

Epoch 4/100: 100%|██████████| 3929/3929 [00:29<00:00, 133.49it/s, loss=0.8316]

Epoch 4 | train_loss=0.8114 | val_loss=0.7842 | val_f1_mean=0.1364 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.069827,0.052112,0.080821,0.121617,0.035635,0.137872,0.13427,0.027541,0.112754,0.053852,...,0.068812,0.165638,0.205295,0.084181,0.110669,0.099125,0.48833,0.08526,0.158426,0.14985

  → Сохранена лучшая модель (mean F1=0.1364)

Epoch 5/100: 100%|██████████| 3929/3929 [00:29<00:00, 132.05it/s, loss=0.5473]

Epoch 5 | train_loss=0.7161 | val_loss=0.7109 | val_f1_mean=0.1533 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.077187,0.094254,0.092383,0.126907,0.043016,0.154781,0.136314,0.038917,0.119504,0.05494,...,0.079418,0.167087,0.221411,0.079616,0.107728,0.14575,0.50157,0.10789,0.178062,0.178578

  → Сохранена лучшая модель (mean F1=0.1533)

Epoch 6/100: 100%|██████████| 3929/3929 [00:29<00:00, 132.29it/s, loss=0.4779]

Epoch 6 | train_loss=0.6332 | val_loss=0.6742 | val_f1_mean=0.1758 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.089718,0.099866,0.121857,0.151823,0.052121,0.183934,0.160236,0.071369,0.163597,0.068873,...,0.0828,0.190827,0.269182,0.092977,0.151864,0.149739,0.515902,0.11697,0.186032,0.214991

  → Сохранена лучшая модель (mean F1=0.1758)

Epoch 7/100: 100%|██████████| 3929/3929 [00:29<00:00, 132.42it/s, loss=0.7131]

Epoch 7 | train_loss=0.5573 | val_loss=0.6328 | val_f1_mean=0.1921 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.099051,0.113143,0.15443,0.165289,0.054101,0.194019,0.16891,0.075151,0.165283,0.064362,...,0.110754,0.216319,0.367598,0.101403,0.165996,0.168627,0.523481,0.120058,0.215338,0.212965

  → Сохранена лучшая модель (mean F1=0.1921)

Epoch 8/100: 100%|██████████| 3929/3929 [00:29<00:00, 133.69it/s, loss=0.4817]

Epoch 8 | train_loss=0.4899 | val_loss=0.5973 | val_f1_mean=0.2174 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.11599,0.13989,0.154159,0.177619,0.062467,0.259493,0.170921,0.113122,0.193354,0.075658,...,0.153366,0.195215,0.424765,0.105984,0.226244,0.198421,0.573392,0.15298,0.19791,0.203446

  → Сохранена лучшая модель (mean F1=0.2174)

Epoch 9/100: 100%|██████████| 3929/3929 [00:29<00:00, 131.85it/s, loss=0.5271]

Epoch 9 | train_loss=0.4309 | val_loss=0.5927 | val_f1_mean=0.2345 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.165352,0.14088,0.155567,0.193739,0.06591,0.23226,0.201485,0.169154,0.250587,0.092401,...,0.160514,0.247362,0.422095,0.127696,0.287559,0.230514,0.61498,0.128095,0.236502,0.234751

  → Сохранена лучшая модель (mean F1=0.2345)

Epoch 10/100: 100%|██████████| 3929/3929 [00:29<00:00, 133.20it/s, loss=0.2921]

Epoch 10 | train_loss=0.3790 | val_loss=0.5826 | val_f1_mean=0.2436 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.144935,0.15112,0.192733,0.20909,0.073548,0.22288,0.196635,0.165306,0.257701,0.1033,...,0.163636,0.2423,0.477954,0.13058,0.309221,0.198558,0.61882,0.147358,0.242763,0.230349

  → Сохранена лучшая модель (mean F1=0.2436)

Epoch 11/100: 100%|██████████| 3929/3929 [00:29<00:00, 133.26it/s, loss=0.6538]

Epoch 11 | train_loss=0.3319 | val_loss=0.5886 | val_f1_mean=0.2662 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.177141,0.163827,0.174668,0.208447,0.102128,0.266744,0.208871,0.1854,0.312022,0.094488,...,0.171123,0.253224,0.505546,0.11917,0.359837,0.204225,0.625116,0.177947,0.227402,0.265203

  → Сохранена лучшая модель (mean F1=0.2662)

Epoch 12/100: 100%|██████████| 3929/3929 [00:29<00:00, 133.37it/s, loss=0.2240]

Epoch 12 | train_loss=0.2882 | val_loss=0.6036 | val_f1_mean=0.2873 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.260227,0.162005,0.217896,0.231378,0.098709,0.307298,0.251962,0.162137,0.296798,0.130352,...,0.187739,0.266038,0.471304,0.146868,0.407749,0.231589,0.655902,0.180897,0.26524,0.322076

  → Сохранена лучшая модель (mean F1=0.2873)

Epoch 13/100: 100%|██████████| 3929/3929 [00:29<00:00, 131.68it/s, loss=0.2790]

Epoch 13 | train_loss=0.2541 | val_loss=0.6604 | val_f1_mean=0.3123 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.299534,0.20539,0.260601,0.268799,0.136986,0.318429,0.262868,0.197183,0.37818,0.158462,...,0.21611,0.301435,0.509622,0.155615,0.41358,0.257475,0.678189,0.201454,0.257289,0.315202

  → Сохранена лучшая модель (mean F1=0.3123)

Epoch 14/100: 100%|██████████| 3929/3929 [00:29<00:00, 133.88it/s, loss=0.3467]

Epoch 14 | train_loss=0.2234 | val_loss=0.6606 | val_f1_mean=0.3318 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.313997,0.31454,0.250443,0.254308,0.111925,0.397942,0.236789,0.230022,0.407045,0.139324,...,0.224483,0.289914,0.610369,0.176909,0.448206,0.2492,0.697033,0.203995,0.243489,0.276932

  → Сохранена лучшая модель (mean F1=0.3318)

Epoch 15/100: 100%|██████████| 3929/3929 [00:29<00:00, 132.45it/s, loss=0.2040]

Epoch 15 | train_loss=0.1995 | val_loss=0.7202 | val_f1_mean=0.3503 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.350592,0.287518,0.265874,0.331998,0.140238,0.385101,0.266667,0.28093,0.352842,0.173549,...,0.233382,0.36242,0.641853,0.145336,0.462827,0.249861,0.702465,0.210602,0.320749,0.343387

  → Сохранена лучшая модель (mean F1=0.3503)

Epoch 16/100: 100%|██████████| 3929/3929 [00:29<00:00, 131.73it/s, loss=0.0744]

Epoch 16 | train_loss=0.1779 | val_loss=0.7822 | val_f1_mean=0.3807 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.381476,0.344291,0.275779,0.319053,0.167637,0.421566,0.320517,0.288958,0.46419,0.198286,...,0.251152,0.361595,0.628707,0.177008,0.518755,0.274328,0.712559,0.23204,0.31944,0.341021

  → Сохранена лучшая модель (mean F1=0.3807)

Epoch 17/100: 100%|██████████| 3929/3929 [00:29<00:00, 132.73it/s, loss=0.3185]

Epoch 17 | train_loss=0.1607 | val_loss=0.7681 | val_f1_mean=0.3789 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.298021,0.360036,0.309465,0.343048,0.151631,0.350232,0.324964,0.270567,0.500207,0.171946,...,0.282737,0.368486,0.624866,0.195228,0.564685,0.283943,0.731511,0.242424,0.334684,0.362378

Epoch 18/100: 100%|██████████| 3929/3929 [00:29<00:00, 132.67it/s, loss=0.1114]

Epoch 18 | train_loss=0.1445 | val_loss=0.8685 | val_f1_mean=0.4115 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.390127,0.432852,0.305813,0.342346,0.191257,0.437014,0.298094,0.31694,0.525386,0.245696,...,0.292543,0.352314,0.655982,0.202589,0.572707,0.321596,0.748703,0.290111,0.314054,0.377197

  → Сохранена лучшая модель (mean F1=0.4115)

Epoch 19/100: 100%|██████████| 3929/3929 [00:29<00:00, 132.50it/s, loss=0.0983]

Epoch 19 | train_loss=0.1306 | val_loss=0.8907 | val_f1_mean=0.4178 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.457088,0.314088,0.327926,0.320764,0.199409,0.423864,0.370894,0.316684,0.466819,0.224751,...,0.252287,0.401738,0.701834,0.200924,0.640747,0.319206,0.766584,0.270817,0.348606,0.398333

  → Сохранена лучшая модель (mean F1=0.4178)

Epoch 20/100: 100%|██████████| 3929/3929 [00:29<00:00, 131.84it/s, loss=0.1170]

Epoch 20 | train_loss=0.1188 | val_loss=0.9734 | val_f1_mean=0.4352 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.463968,0.320186,0.325763,0.391608,0.195668,0.423467,0.349919,0.271454,0.554273,0.28365,...,0.321671,0.439665,0.678649,0.21474,0.603025,0.344477,0.741619,0.275359,0.374399,0.482505

  → Сохранена лучшая модель (mean F1=0.4352)

Epoch 21/100: 100%|██████████| 3929/3929 [00:29<00:00, 133.10it/s, loss=0.0921]

Epoch 21 | train_loss=0.1076 | val_loss=1.0010 | val_f1_mean=0.4441 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.483193,0.47561,0.370677,0.388184,0.175252,0.456621,0.392763,0.364395,0.512842,0.262626,...,0.314241,0.425422,0.697225,0.196319,0.582267,0.322888,0.745143,0.324883,0.389037,0.444936

  → Сохранена лучшая модель (mean F1=0.4441)

Epoch 22/100: 100%|██████████| 3929/3929 [00:29<00:00, 133.67it/s, loss=0.0447]

Epoch 22 | train_loss=0.0991 | val_loss=1.0922 | val_f1_mean=0.4624 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.453017,0.496164,0.382966,0.385835,0.236626,0.46754,0.391467,0.36,0.591479,0.349127,...,0.327273,0.406548,0.711288,0.226363,0.624572,0.341112,0.766694,0.31272,0.386124,0.455696

  → Сохранена лучшая модель (mean F1=0.4624)

Epoch 23/100: 100%|██████████| 3929/3929 [00:29<00:00, 134.62it/s, loss=0.1190]

Epoch 23 | train_loss=0.0907 | val_loss=1.0855 | val_f1_mean=0.4640 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.464606,0.494208,0.360022,0.419715,0.257046,0.417946,0.377647,0.361076,0.627073,0.320911,...,0.343188,0.441548,0.684785,0.243902,0.635821,0.309071,0.787781,0.312153,0.38867,0.440041

  → Сохранена лучшая модель (mean F1=0.4640)

Epoch 24/100: 100%|██████████| 3929/3929 [00:28<00:00, 135.63it/s, loss=0.0745]

Epoch 24 | train_loss=0.0831 | val_loss=1.1165 | val_f1_mean=0.4681 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.455556,0.422747,0.390704,0.430453,0.22356,0.465385,0.418879,0.428795,0.592593,0.280977,...,0.352522,0.417021,0.730201,0.23748,0.700171,0.366013,0.778207,0.262394,0.36771,0.471323

  → Сохранена лучшая модель (mean F1=0.4681)

Epoch 25/100: 100%|██████████| 3929/3929 [00:29<00:00, 134.11it/s, loss=0.0639]

Epoch 25 | train_loss=0.0765 | val_loss=1.1962 | val_f1_mean=0.4891 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.53819,0.417204,0.40488,0.388502,0.243062,0.490812,0.454717,0.45841,0.64344,0.288789,...,0.32139,0.438001,0.739781,0.244409,0.694318,0.36381,0.769794,0.296027,0.381284,0.491863

  → Сохранена лучшая модель (mean F1=0.4891)

Epoch 26/100: 100%|██████████| 3929/3929 [00:29<00:00, 133.97it/s, loss=0.0316]

Epoch 26 | train_loss=0.0699 | val_loss=1.2679 | val_f1_mean=0.4949 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.480652,0.483912,0.429078,0.420889,0.231041,0.519846,0.447234,0.403535,0.674446,0.306043,...,0.408916,0.480849,0.716039,0.256801,0.659989,0.400447,0.789564,0.319809,0.399674,0.482551

  → Сохранена лучшая модель (mean F1=0.4949)

Epoch 27/100: 100%|██████████| 3929/3929 [00:29<00:00, 134.63it/s, loss=0.1013]

Epoch 27 | train_loss=0.0645 | val_loss=1.2689 | val_f1_mean=0.5001 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.533993,0.505898,0.398617,0.417512,0.239029,0.493207,0.449038,0.455959,0.674419,0.350588,...,0.361582,0.448181,0.754786,0.2633,0.718786,0.376768,0.769848,0.326079,0.410513,0.481303

  → Сохранена лучшая модель (mean F1=0.5001)

Epoch 28/100: 100%|██████████| 3929/3929 [00:29<00:00, 133.71it/s, loss=0.0698]

Epoch 28 | train_loss=0.0598 | val_loss=1.3813 | val_f1_mean=0.5126 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.508159,0.480296,0.392061,0.463706,0.308123,0.528376,0.454241,0.44714,0.661461,0.398217,...,0.418675,0.470438,0.744992,0.249564,0.731971,0.38508,0.801834,0.347248,0.42233,0.50285

  → Сохранена лучшая модель (mean F1=0.5126)

Epoch 29/100: 100%|██████████| 3929/3929 [00:29<00:00, 133.77it/s, loss=0.0315]

Epoch 29 | train_loss=0.0556 | val_loss=1.3308 | val_f1_mean=0.5099 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.484591,0.535565,0.414427,0.45189,0.208167,0.537343,0.423109,0.47037,0.60517,0.34009,...,0.420344,0.461538,0.75085,0.26618,0.692437,0.377358,0.797116,0.339918,0.385754,0.501269

Epoch 30/100: 100%|██████████| 3929/3929 [00:29<00:00, 134.75it/s, loss=0.0921]

Epoch 30 | train_loss=0.0501 | val_loss=1.4289 | val_f1_mean=0.5207 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.552764,0.577982,0.425952,0.444197,0.297987,0.561966,0.43957,0.453571,0.613154,0.396149,...,0.397524,0.48123,0.76098,0.265594,0.712139,0.378863,0.796789,0.367047,0.406022,0.496314

  → Сохранена лучшая модель (mean F1=0.5207)

Epoch 31/100: 100%|██████████| 3929/3929 [00:29<00:00, 134.56it/s, loss=0.0716]

Epoch 31 | train_loss=0.0468 | val_loss=1.5699 | val_f1_mean=0.5317 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.552598,0.498652,0.488652,0.465173,0.302687,0.535193,0.48836,0.393211,0.729503,0.404834,...,0.43735,0.531618,0.781879,0.256785,0.696095,0.408628,0.799153,0.365794,0.442329,0.557557

  → Сохранена лучшая модель (mean F1=0.5317)

Epoch 32/100: 100%|██████████| 3929/3929 [00:29<00:00, 133.33it/s, loss=0.0672]

Epoch 32 | train_loss=0.0432 | val_loss=1.5228 | val_f1_mean=0.5328 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.552163,0.474874,0.461599,0.463517,0.297542,0.584746,0.473075,0.473485,0.709598,0.386842,...,0.449082,0.478165,0.7614,0.271186,0.695504,0.38993,0.790965,0.340503,0.411765,0.501579

  → Сохранена лучшая модель (mean F1=0.5328)

Epoch 33/100: 100%|██████████| 3929/3929 [00:29<00:00, 135.30it/s, loss=0.0228]

Epoch 33 | train_loss=0.0406 | val_loss=1.5438 | val_f1_mean=0.5345 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.594901,0.500677,0.460563,0.474092,0.301546,0.543782,0.454074,0.460993,0.701393,0.377049,...,0.438792,0.491084,0.776091,0.266,0.711649,0.384865,0.803434,0.381827,0.433933,0.552174

  → Сохранена лучшая модель (mean F1=0.5345)

Epoch 34/100: 100%|██████████| 3929/3929 [00:29<00:00, 134.64it/s, loss=0.0103]

Epoch 34 | train_loss=0.0372 | val_loss=1.7025 | val_f1_mean=0.5487 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.562905,0.5728,0.457692,0.477475,0.294737,0.552017,0.496778,0.5074,0.656633,0.407681,...,0.443886,0.502695,0.750623,0.274038,0.705413,0.419686,0.803408,0.380151,0.429916,0.555985

  → Сохранена лучшая модель (mean F1=0.5487)

Epoch 35/100: 100%|██████████| 3929/3929 [00:29<00:00, 134.07it/s, loss=0.0234]

Epoch 35 | train_loss=0.0346 | val_loss=1.6740 | val_f1_mean=0.5460 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.568579,0.531609,0.480514,0.466494,0.318379,0.523887,0.497188,0.463235,0.7199,0.392265,...,0.4384,0.516563,0.759686,0.256696,0.758312,0.419938,0.816616,0.384365,0.419458,0.541126

Epoch 36/100: 100%|██████████| 3929/3929 [00:29<00:00, 134.44it/s, loss=0.0111]

Epoch 36 | train_loss=0.0325 | val_loss=1.7158 | val_f1_mean=0.5503 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.58616,0.563945,0.487701,0.492116,0.291718,0.55776,0.479243,0.481061,0.703794,0.39087,...,0.388203,0.518828,0.762217,0.256236,0.7339,0.404959,0.806911,0.371454,0.424032,0.556322

  → Сохранена лучшая модель (mean F1=0.5503)

Epoch 37/100: 100%|██████████| 3929/3929 [00:29<00:00, 135.15it/s, loss=0.0474]

Epoch 37 | train_loss=0.0298 | val_loss=1.7286 | val_f1_mean=0.5482 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.57513,0.55287,0.480312,0.481385,0.292621,0.574243,0.477968,0.490946,0.73794,0.363636,...,0.462597,0.487276,0.777564,0.261364,0.733493,0.399027,0.800502,0.38316,0.419802,0.53829

Epoch 38/100: 100%|██████████| 3929/3929 [00:28<00:00, 135.57it/s, loss=0.0320]

Epoch 38 | train_loss=0.0287 | val_loss=1.7631 | val_f1_mean=0.5508 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.551365,0.55,0.45283,0.496281,0.32106,0.572886,0.472709,0.479042,0.707921,0.393293,...,0.443163,0.513105,0.780593,0.265033,0.720094,0.413876,0.810769,0.39284,0.43787,0.548901

  → Сохранена лучшая модель (mean F1=0.5508)

Epoch 39/100: 100%|██████████| 3929/3929 [00:28<00:00, 135.84it/s, loss=0.0207]

Epoch 39 | train_loss=0.0259 | val_loss=1.8316 | val_f1_mean=0.5592 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.577291,0.580542,0.474947,0.491333,0.329705,0.606061,0.51187,0.501018,0.729974,0.351282,...,0.461538,0.491279,0.784638,0.292105,0.737288,0.435754,0.806196,0.396818,0.432924,0.51634

  → Сохранена лучшая модель (mean F1=0.5592)

Epoch 40/100: 100%|██████████| 3929/3929 [00:28<00:00, 137.66it/s, loss=0.0339]

Epoch 40 | train_loss=0.0240 | val_loss=1.8674 | val_f1_mean=0.5601 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.553299,0.605442,0.476357,0.481093,0.335423,0.604065,0.51071,0.477318,0.724619,0.419244,...,0.489058,0.490478,0.795743,0.263682,0.764898,0.426182,0.796933,0.395038,0.421851,0.514248

  → Сохранена лучшая модель (mean F1=0.5601)

Epoch 41/100: 100%|██████████| 3929/3929 [00:28<00:00, 135.71it/s, loss=0.0341]

Epoch 41 | train_loss=0.0231 | val_loss=1.8914 | val_f1_mean=0.5622 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.590529,0.612457,0.485837,0.490591,0.359511,0.586089,0.499429,0.50501,0.725064,0.452555,...,0.494706,0.518283,0.779387,0.269555,0.725118,0.417132,0.804528,0.39407,0.427088,0.52888

  → Сохранена лучшая модель (mean F1=0.5622)

Epoch 42/100: 100%|██████████| 3929/3929 [00:28<00:00, 136.54it/s, loss=0.0098]

Epoch 42 | train_loss=0.0220 | val_loss=1.9628 | val_f1_mean=0.5655 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.587393,0.508475,0.500476,0.498316,0.354086,0.617325,0.491822,0.564815,0.728426,0.447227,...,0.396307,0.516708,0.776381,0.271845,0.737355,0.406863,0.809924,0.400193,0.417096,0.5625

  → Сохранена лучшая модель (mean F1=0.5655)

Epoch 43/100: 100%|██████████| 3929/3929 [00:28<00:00, 136.74it/s, loss=0.0202]

Epoch 43 | train_loss=0.0190 | val_loss=2.0124 | val_f1_mean=0.5661 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.575233,0.592593,0.494096,0.500691,0.343972,0.575273,0.50201,0.537931,0.733636,0.416938,...,0.483673,0.532366,0.787512,0.24698,0.715116,0.434396,0.805959,0.391426,0.433806,0.553984

  → Сохранена лучшая модель (mean F1=0.5661)

Epoch 44/100: 100%|██████████| 3929/3929 [00:28<00:00, 136.58it/s, loss=0.0124]

Epoch 44 | train_loss=0.0188 | val_loss=2.0414 | val_f1_mean=0.5713 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.593023,0.583062,0.494009,0.506375,0.340836,0.594097,0.518874,0.527426,0.754362,0.328358,...,0.47413,0.540984,0.792659,0.242553,0.75443,0.433989,0.815491,0.430639,0.442296,0.575365

  → Сохранена лучшая модель (mean F1=0.5713)

Epoch 45/100: 100%|██████████| 3929/3929 [00:28<00:00, 136.17it/s, loss=0.0022]

Epoch 45 | train_loss=0.0168 | val_loss=2.0817 | val_f1_mean=0.5722 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.553411,0.620939,0.490654,0.523722,0.346084,0.586799,0.498876,0.545872,0.752646,0.42732,...,0.509529,0.54157,0.788368,0.252349,0.738213,0.429448,0.819581,0.408247,0.442795,0.544771

  → Сохранена лучшая модель (mean F1=0.5722)

Epoch 46/100: 100%|██████████| 3929/3929 [00:28<00:00, 136.99it/s, loss=0.0095]

Epoch 46 | train_loss=0.0159 | val_loss=2.1092 | val_f1_mean=0.5712 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.580468,0.572785,0.49837,0.536339,0.328358,0.611774,0.500589,0.530702,0.740117,0.434932,...,0.492453,0.516632,0.78744,0.27563,0.763469,0.430939,0.814551,0.419089,0.423615,0.583748

Epoch 47/100: 100%|██████████| 3929/3929 [00:29<00:00, 135.45it/s, loss=0.0177]

Epoch 47 | train_loss=0.0155 | val_loss=2.1098 | val_f1_mean=0.5734 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.616296,0.634686,0.503966,0.525516,0.332805,0.606504,0.502576,0.517787,0.76087,0.368421,...,0.498113,0.530588,0.773232,0.26087,0.728905,0.437322,0.811055,0.419122,0.43519,0.57971

  → Сохранена лучшая модель (mean F1=0.5734)

Epoch 48/100: 100%|██████████| 3929/3929 [00:28<00:00, 136.13it/s, loss=0.3242]

Epoch 48 | train_loss=0.0141 | val_loss=2.1200 | val_f1_mean=0.5726 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.610465,0.638941,0.499772,0.52696,0.369811,0.597271,0.489555,0.515213,0.729367,0.456929,...,0.491928,0.512262,0.794904,0.248292,0.734223,0.415471,0.816706,0.437024,0.437577,0.578526

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.610465,0.638941,0.499772,0.52696,0.369811,0.597271,0.489555,0.515213,0.729367,0.456929,...,0.491928,0.512262,0.794904,0.248292,0.734223,0.415471,0.816706,0.437024,0.437577,0.578526

In [42]:
rnn_model = RNN_Text_Classifier(
    num_classes=len(le.categories_[0]),
    vocab_size=len(tokenizer.get_vocab()),
    embedding_dim=256,
    hidden_size=64,
)

In [43]:
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = AdamW(rnn_model.parameters(), lr=0.001, weight_decay=0.01)
rnn_model.to(DEVICE)

training(
    model=rnn_model,
    train_data_loader=train_dl,
    val_data_loader=val_dl,
    optimizer=optimizer,
    epoches=EPOCHS,
    criterion=criterion,
    tokenizator=le,
    accum_steps=ACCUM_STEPS,
    warmup_frac=WARMUP_FRAC,
    device=DEVICE
    )

Epoch 1/100: 100%|██████████| 3929/3929 [00:20<00:00, 190.26it/s, loss=1.3521]

Epoch 1 | train_loss=1.3567 | val_loss=1.3229 | val_f1_mean=0.0579 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.022503,0.002262,0.043804,0.056737,0.013859,0.076399,0.03666,0.0194,0.055804,0.011261,...,0.019704,0.041123,0.09483,0.022529,0.070015,0.032794,0.183242,0.027478,0.04336,0.115948

  → Сохранена лучшая модель (mean F1=0.0579)

Epoch 2/100: 100%|██████████| 3929/3929 [00:21<00:00, 186.23it/s, loss=1.3959]

Epoch 2 | train_loss=1.2998 | val_loss=1.2739 | val_f1_mean=0.0654 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.037829,0.016033,0.043155,0.068653,0.013879,0.072237,0.038128,0.019319,0.062866,0.011599,...,0.022392,0.043919,0.099471,0.022946,0.075039,0.032161,0.202183,0.040213,0.045643,0.11825

  → Сохранена лучшая модель (mean F1=0.0654)

Epoch 3/100: 100%|██████████| 3929/3929 [00:20<00:00, 189.47it/s, loss=1.2844]

Epoch 3 | train_loss=1.2693 | val_loss=1.2568 | val_f1_mean=0.0670 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.025541,0.017677,0.046915,0.0589,0.013307,0.084607,0.04774,0.020908,0.066552,0.011776,...,0.029109,0.044274,0.103592,0.022947,0.082607,0.042381,0.212494,0.036588,0.043959,0.076677

  → Сохранена лучшая модель (mean F1=0.0670)

Epoch 4/100: 100%|██████████| 3929/3929 [00:20<00:00, 190.14it/s, loss=1.0997]

Epoch 4 | train_loss=1.2057 | val_loss=1.1831 | val_f1_mean=0.0777 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.032444,0.02682,0.053876,0.066263,0.015399,0.064831,0.049772,0.018931,0.071014,0.021504,...,0.026357,0.06136,0.178076,0.03491,0.072626,0.043991,0.318966,0.034537,0.063394,0.09536

  → Сохранена лучшая модель (mean F1=0.0777)

Epoch 5/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.51it/s, loss=1.0622]

Epoch 5 | train_loss=1.1499 | val_loss=1.1501 | val_f1_mean=0.0790 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.034667,0.024868,0.057563,0.068693,0.016624,0.067863,0.052919,0.019389,0.073002,0.021751,...,0.028371,0.065344,0.1641,0.037869,0.07927,0.045755,0.31186,0.035907,0.064535,0.066068

  → Сохранена лучшая модель (mean F1=0.0790)

Epoch 6/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.88it/s, loss=0.9747]

Epoch 6 | train_loss=1.1150 | val_loss=1.1172 | val_f1_mean=0.0827 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.033373,0.027255,0.060047,0.077896,0.016027,0.073615,0.05282,0.019817,0.074078,0.021626,...,0.029688,0.066644,0.170175,0.034796,0.08003,0.046382,0.31278,0.036259,0.068498,0.064561

  → Сохранена лучшая модель (mean F1=0.0827)

Epoch 7/100: 100%|██████████| 3929/3929 [00:20<00:00, 191.73it/s, loss=1.1229]

Epoch 7 | train_loss=1.0837 | val_loss=1.0928 | val_f1_mean=0.0859 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.036237,0.027319,0.064043,0.08128,0.018755,0.089818,0.05842,0.019433,0.069856,0.020509,...,0.034765,0.072418,0.170773,0.037903,0.075577,0.052491,0.299747,0.038383,0.066286,0.11213

  → Сохранена лучшая модель (mean F1=0.0859)

Epoch 8/100: 100%|██████████| 3929/3929 [00:20<00:00, 194.45it/s, loss=1.0115]

Epoch 8 | train_loss=1.0561 | val_loss=1.0925 | val_f1_mean=0.0871 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.036367,0.026341,0.061529,0.098317,0.01853,0.083702,0.059332,0.020256,0.077004,0.019599,...,0.034785,0.068676,0.189327,0.038138,0.083104,0.047588,0.317263,0.046485,0.067389,0.116047

  → Сохранена лучшая модель (mean F1=0.0871)

Epoch 9/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.33it/s, loss=1.0145]

Epoch 9 | train_loss=1.0289 | val_loss=1.0963 | val_f1_mean=0.0906 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.061866,0.029955,0.063797,0.108213,0.033714,0.081125,0.062373,0.021664,0.081216,0.021503,...,0.043614,0.067233,0.18592,0.03546,0.08858,0.047149,0.33216,0.048068,0.065292,0.101299

  → Сохранена лучшая модель (mean F1=0.0906)

Epoch 10/100: 100%|██████████| 3929/3929 [00:20<00:00, 188.42it/s, loss=1.1154]

Epoch 10 | train_loss=1.0012 | val_loss=1.0696 | val_f1_mean=0.0918 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.051146,0.041695,0.066101,0.107193,0.02865,0.092486,0.062899,0.019489,0.072507,0.017869,...,0.055099,0.078626,0.168703,0.03939,0.080042,0.055375,0.307897,0.052162,0.072881,0.114125

  → Сохранена лучшая модель (mean F1=0.0918)

Epoch 11/100: 100%|██████████| 3929/3929 [00:21<00:00, 186.89it/s, loss=0.8060]

Epoch 11 | train_loss=0.9775 | val_loss=1.0650 | val_f1_mean=0.0947 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.052193,0.043946,0.065548,0.098146,0.02612,0.084843,0.065438,0.020425,0.083818,0.018837,...,0.047241,0.07243,0.187518,0.037133,0.103962,0.052685,0.333497,0.052911,0.074676,0.088853

  → Сохранена лучшая модель (mean F1=0.0947)

Epoch 12/100: 100%|██████████| 3929/3929 [00:21<00:00, 186.26it/s, loss=0.8408]

Epoch 12 | train_loss=0.9486 | val_loss=1.1069 | val_f1_mean=0.0974 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.073639,0.042849,0.065518,0.118039,0.036247,0.087405,0.062698,0.021372,0.079341,0.022064,...,0.053512,0.076298,0.188815,0.03676,0.08394,0.051808,0.332026,0.064079,0.068471,0.116895

  → Сохранена лучшая модель (mean F1=0.0974)

Epoch 13/100: 100%|██████████| 3929/3929 [00:21<00:00, 183.05it/s, loss=0.7041]

Epoch 13 | train_loss=0.9207 | val_loss=1.1568 | val_f1_mean=0.1006 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.072031,0.060544,0.065175,0.126226,0.039861,0.08175,0.060974,0.021633,0.081883,0.029161,...,0.067738,0.074689,0.192417,0.037336,0.091325,0.051337,0.337135,0.060377,0.079589,0.121442

  → Сохранена лучшая модель (mean F1=0.1006)

Epoch 14/100: 100%|██████████| 3929/3929 [00:21<00:00, 180.54it/s, loss=1.0082]

Epoch 14 | train_loss=0.8958 | val_loss=1.0569 | val_f1_mean=0.0993 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.063629,0.040826,0.068859,0.117765,0.035749,0.110598,0.071864,0.022805,0.083627,0.029238,...,0.058387,0.089361,0.191328,0.040398,0.089481,0.056925,0.329656,0.05712,0.07416,0.101418

Epoch 15/100: 100%|██████████| 3929/3929 [00:21<00:00, 184.04it/s, loss=0.9482]

Epoch 15 | train_loss=0.8772 | val_loss=1.1587 | val_f1_mean=0.1026 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.083118,0.049228,0.066769,0.133818,0.044199,0.087725,0.062346,0.023153,0.083592,0.035256,...,0.064051,0.085576,0.190886,0.040709,0.088444,0.050712,0.339742,0.07537,0.083294,0.123982

  → Сохранена лучшая модель (mean F1=0.1026)

Epoch 16/100: 100%|██████████| 3929/3929 [00:21<00:00, 182.92it/s, loss=0.6863]

Epoch 16 | train_loss=0.8519 | val_loss=1.2934 | val_f1_mean=0.1014 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.084701,0.047921,0.063414,0.123131,0.039404,0.082942,0.060929,0.022495,0.089136,0.034204,...,0.056936,0.080854,0.197559,0.042448,0.095028,0.050512,0.353925,0.065192,0.097561,0.116447

Epoch 17/100: 100%|██████████| 3929/3929 [00:21<00:00, 185.45it/s, loss=0.6675]

Epoch 17 | train_loss=0.8288 | val_loss=1.1917 | val_f1_mean=0.1070 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.079256,0.049377,0.067783,0.138995,0.038454,0.112898,0.064718,0.024857,0.089243,0.041561,...,0.070326,0.083554,0.195408,0.040556,0.09598,0.053996,0.348792,0.095345,0.090048,0.111323

  → Сохранена лучшая модель (mean F1=0.1070)

Epoch 18/100: 100%|██████████| 3929/3929 [00:21<00:00, 181.83it/s, loss=0.6496]

Epoch 18 | train_loss=0.8136 | val_loss=1.1558 | val_f1_mean=0.1059 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.08559,0.05323,0.072472,0.137343,0.038784,0.102963,0.062823,0.027365,0.082399,0.042351,...,0.063496,0.101078,0.186648,0.049238,0.089674,0.062522,0.336383,0.071331,0.111485,0.120956

Epoch 19/100: 100%|██████████| 3929/3929 [00:21<00:00, 181.30it/s, loss=0.9445]

Epoch 19 | train_loss=0.7935 | val_loss=1.1924 | val_f1_mean=0.1088 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.083973,0.054224,0.071837,0.142602,0.042658,0.100537,0.070747,0.026137,0.084318,0.042905,...,0.076131,0.107675,0.18543,0.047109,0.088007,0.062451,0.339668,0.079082,0.116363,0.140234

  → Сохранена лучшая модель (mean F1=0.1088)

Epoch 20/100: 100%|██████████| 3929/3929 [00:20<00:00, 187.76it/s, loss=0.5798]

Epoch 20 | train_loss=0.7777 | val_loss=1.1569 | val_f1_mean=0.1087 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.084593,0.046961,0.069169,0.1444,0.039539,0.105128,0.06828,0.034238,0.090543,0.039627,...,0.067079,0.108782,0.188545,0.049021,0.098038,0.060966,0.341503,0.06746,0.104294,0.127225

Epoch 21/100: 100%|██████████| 3929/3929 [00:20<00:00, 187.17it/s, loss=0.7515]

Epoch 21 | train_loss=0.7655 | val_loss=1.2083 | val_f1_mean=0.1089 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.076268,0.06109,0.073027,0.14757,0.040382,0.114407,0.068105,0.031741,0.085101,0.039647,...,0.072005,0.103908,0.182501,0.048566,0.089627,0.069512,0.329749,0.079141,0.094498,0.146207

  → Сохранена лучшая модель (mean F1=0.1089)

Epoch 22/100: 100%|██████████| 3929/3929 [00:20<00:00, 187.78it/s, loss=0.4662]

Epoch 22 | train_loss=0.7484 | val_loss=1.1910 | val_f1_mean=0.1131 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.080934,0.04611,0.069126,0.135098,0.035698,0.106496,0.070238,0.027991,0.097491,0.037814,...,0.06711,0.120272,0.191155,0.052071,0.103541,0.064091,0.351927,0.065285,0.115395,0.129866

  → Сохранена лучшая модель (mean F1=0.1131)

Epoch 23/100: 100%|██████████| 3929/3929 [00:19<00:00, 197.48it/s, loss=0.7100]

Epoch 23 | train_loss=0.7315 | val_loss=1.1958 | val_f1_mean=0.1147 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.096722,0.046862,0.07081,0.141768,0.039203,0.124174,0.067941,0.029278,0.088076,0.047142,...,0.068145,0.104437,0.193657,0.052298,0.096641,0.070761,0.351115,0.080999,0.111771,0.142975

  → Сохранена лучшая модель (mean F1=0.1147)

Epoch 24/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.64it/s, loss=0.8135]

Epoch 24 | train_loss=0.7168 | val_loss=1.3514 | val_f1_mean=0.1178 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.099578,0.060347,0.06896,0.153536,0.042821,0.113593,0.068529,0.028302,0.090937,0.052555,...,0.08436,0.117516,0.191507,0.053698,0.095273,0.065158,0.348549,0.094059,0.127527,0.14976

  → Сохранена лучшая модель (mean F1=0.1178)

Epoch 25/100: 100%|██████████| 3929/3929 [00:20<00:00, 190.10it/s, loss=0.7169]

Epoch 25 | train_loss=0.7054 | val_loss=1.2842 | val_f1_mean=0.1173 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.093023,0.054974,0.069489,0.141281,0.043716,0.115064,0.069922,0.03156,0.102157,0.041573,...,0.073203,0.116422,0.19462,0.051323,0.104404,0.072844,0.350024,0.086109,0.116727,0.135296

Epoch 26/100: 100%|██████████| 3929/3929 [00:20<00:00, 189.30it/s, loss=0.7423]

Epoch 26 | train_loss=0.6897 | val_loss=1.4299 | val_f1_mean=0.1181 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.103298,0.057915,0.068773,0.152161,0.051099,0.114493,0.067036,0.038196,0.096434,0.04893,...,0.084639,0.116772,0.192094,0.058824,0.097557,0.071897,0.352778,0.094401,0.129472,0.149714

  → Сохранена лучшая модель (mean F1=0.1181)

Epoch 27/100: 100%|██████████| 3929/3929 [00:20<00:00, 193.13it/s, loss=0.4776]

Epoch 27 | train_loss=0.6790 | val_loss=1.3335 | val_f1_mean=0.1213 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.099287,0.059302,0.069738,0.157076,0.045587,0.118859,0.072546,0.032781,0.093318,0.04942,...,0.082414,0.134503,0.191344,0.049665,0.097129,0.073242,0.35192,0.083778,0.137478,0.138916

  → Сохранена лучшая модель (mean F1=0.1213)

Epoch 28/100: 100%|██████████| 3929/3929 [00:20<00:00, 189.03it/s, loss=0.5549]

Epoch 28 | train_loss=0.6628 | val_loss=1.3862 | val_f1_mean=0.1209 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.106244,0.054193,0.071229,0.159232,0.045639,0.104761,0.074241,0.037158,0.10168,0.049693,...,0.079621,0.137125,0.192514,0.054275,0.102644,0.080486,0.357653,0.085836,0.144223,0.145115

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.106244,0.054193,0.071229,0.159232,0.045639,0.104761,0.074241,0.037158,0.10168,0.049693,...,0.079621,0.137125,0.192514,0.054275,0.102644,0.080486,0.357653,0.085836,0.144223,0.145115

In [44]:
from huggingface_hub import snapshot_download

print("📥 Скачивание модели...")
model_path = snapshot_download(
    repo_id=MODEL_NAME,
    local_dir=MODEL_DIR,
)

📥 Скачивание модели...

Fetching 13 files: 100%|██████████| 13/13 [00:00<00:00, 777.98it/s]

In [45]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR, num_labels=len(le.categories_[0]), local_files_only=True)
model.to(DEVICE)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 9983.18it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: models/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=42, bias=True)
  )
)

In [47]:
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = AdamW(model.parameters(), lr=LR, weight_decay=0.01)
model.to(DEVICE)

training(
    model=model,
    train_data_loader=train_dl,
    val_data_loader=val_dl,
    optimizer=optimizer,
    epoches=EPOCHS,
    criterion=criterion,
    tokenizator=le,
    accum_steps=ACCUM_STEPS,
    warmup_frac=WARMUP_FRAC,
    device=DEVICE,
    save_path=SAVE_PATH,
    )

Epoch 1/100: 100%|██████████| 3929/3929 [18:31<00:00,  3.54it/s, loss=0.8248]

Epoch 1 | train_loss=1.2622 | val_loss=0.9502 | val_f1_mean=0.1363 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.077277,0.040941,0.0826,0.164804,0.054297,0.107239,0.111209,0.080032,0.126306,0.029454,...,0.063844,0.164963,0.315234,0.031488,0.157666,0.048974,0.38517,0.084747,0.160403,0.112924

  → Сохранена лучшая модель (mean F1=0.1363)

Epoch 2/100: 100%|██████████| 3929/3929 [18:38<00:00,  3.51it/s, loss=0.5479]

Epoch 2 | train_loss=0.8181 | val_loss=0.6656 | val_f1_mean=0.2305 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.13674,0.096061,0.131881,0.318536,0.089458,0.210967,0.271674,0.1072,0.249811,0.077849,...,0.157074,0.276371,0.410251,0.065883,0.404624,0.132207,0.504477,0.098958,0.249289,0.179717

  → Сохранена лучшая модель (mean F1=0.2305)

Epoch 3/100: 100%|██████████| 3929/3929 [18:14<00:00,  3.59it/s, loss=0.5391]

Epoch 3 | train_loss=0.6053 | val_loss=0.5047 | val_f1_mean=0.3555 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.334917,0.244456,0.205545,0.427471,0.276334,0.362093,0.35558,0.25229,0.38076,0.204404,...,0.276085,0.306611,0.608225,0.093182,0.525531,0.26094,0.648783,0.16893,0.275,0.230603

  → Сохранена лучшая модель (mean F1=0.3555)

Epoch 4/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.2609]

Epoch 4 | train_loss=0.4510 | val_loss=0.3833 | val_f1_mean=0.4042 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.301486,0.248491,0.288142,0.456611,0.268886,0.40017,0.350116,0.253199,0.467799,0.269578,...,0.337596,0.35315,0.771375,0.10488,0.560128,0.270096,0.720711,0.218599,0.307125,0.246138

  → Сохранена лучшая модель (mean F1=0.4042)

Epoch 5/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.3381]

Epoch 5 | train_loss=0.3440 | val_loss=0.3122 | val_f1_mean=0.4256 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.282524,0.231054,0.250467,0.460543,0.271718,0.432962,0.399173,0.213531,0.508812,0.275915,...,0.4,0.387852,0.845192,0.139995,0.572584,0.283288,0.787335,0.270957,0.353305,0.277793

  → Сохранена лучшая модель (mean F1=0.4256)

Epoch 6/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.1480]

Epoch 6 | train_loss=0.2706 | val_loss=0.2737 | val_f1_mean=0.4860 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.352,0.262552,0.440107,0.470692,0.302496,0.44951,0.46807,0.381783,0.620301,0.277317,...,0.435256,0.42592,0.807782,0.191538,0.652912,0.292599,0.83893,0.309453,0.402184,0.386792

  → Сохранена лучшая модель (mean F1=0.4860)

Epoch 7/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.1458]

Epoch 7 | train_loss=0.2194 | val_loss=0.2699 | val_f1_mean=0.5407 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.504007,0.387443,0.428979,0.47322,0.385496,0.552028,0.476568,0.467312,0.66599,0.28046,...,0.43483,0.473361,0.849078,0.176351,0.752155,0.443815,0.83209,0.416329,0.426319,0.449256

  → Сохранена лучшая модель (mean F1=0.5407)

Epoch 8/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.1324]

Epoch 8 | train_loss=0.1814 | val_loss=0.2557 | val_f1_mean=0.5507 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.544031,0.486486,0.5,0.500906,0.390873,0.510818,0.460047,0.428078,0.677669,0.311847,...,0.505718,0.517857,0.870067,0.18624,0.742464,0.401266,0.868538,0.391239,0.452844,0.412909

  → Сохранена лучшая модель (mean F1=0.5507)

Epoch 9/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.0840]

Epoch 9 | train_loss=0.1519 | val_loss=0.2856 | val_f1_mean=0.5916 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.609784,0.69219,0.460066,0.53493,0.430131,0.601557,0.486875,0.649057,0.706906,0.365931,...,0.500317,0.488534,0.84398,0.208065,0.714214,0.428137,0.868288,0.40236,0.42582,0.550986

  → Сохранена лучшая модель (mean F1=0.5916)

Epoch 10/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.2026]

Epoch 10 | train_loss=0.1289 | val_loss=0.3028 | val_f1_mean=0.6246 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.596983,0.587224,0.48158,0.597879,0.512821,0.542004,0.494938,0.641711,0.808917,0.379421,...,0.616006,0.533589,0.850278,0.244839,0.810215,0.44575,0.855976,0.431454,0.463735,0.590629

  → Сохранена лучшая модель (mean F1=0.6246)

Epoch 11/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.0847]

Epoch 11 | train_loss=0.1098 | val_loss=0.3088 | val_f1_mean=0.6210 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.557214,0.5975,0.511969,0.559688,0.479275,0.598184,0.528497,0.560976,0.688285,0.395951,...,0.63837,0.509358,0.857143,0.28691,0.779436,0.48722,0.871405,0.517241,0.461767,0.608807

Epoch 12/100: 100%|██████████| 3929/3929 [18:10<00:00,  3.60it/s, loss=0.1206]

Epoch 12 | train_loss=0.0918 | val_loss=0.3588 | val_f1_mean=0.6476 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.715673,0.559524,0.530626,0.637899,0.466916,0.643719,0.588951,0.699411,0.752018,0.3878,...,0.694073,0.543384,0.892578,0.306804,0.818824,0.500549,0.858274,0.458396,0.467148,0.643759

  → Сохранена лучшая модель (mean F1=0.6476)

Epoch 13/100: 100%|██████████| 3929/3929 [18:27<00:00,  3.55it/s, loss=0.0406]

Epoch 13 | train_loss=0.0784 | val_loss=0.3942 | val_f1_mean=0.6653 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.690217,0.697389,0.57816,0.583446,0.521008,0.641289,0.561602,0.698413,0.767878,0.446475,...,0.645602,0.535427,0.890905,0.373832,0.774973,0.535671,0.879918,0.500835,0.474011,0.632639

  → Сохранена лучшая модель (mean F1=0.6653)

Epoch 14/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0550]

Epoch 14 | train_loss=0.0681 | val_loss=0.4147 | val_f1_mean=0.6766 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.685185,0.647462,0.619662,0.586754,0.58194,0.609003,0.588563,0.729167,0.827586,0.57193,...,0.6787,0.557785,0.900749,0.326132,0.839685,0.580818,0.87726,0.500208,0.484051,0.64969

  → Сохранена лучшая модель (mean F1=0.6766)

Epoch 15/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0382]

Epoch 15 | train_loss=0.0583 | val_loss=0.4909 | val_f1_mean=0.6901 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.647783,0.716418,0.565156,0.632834,0.601942,0.627152,0.613715,0.664165,0.829457,0.515432,...,0.757642,0.604801,0.896154,0.407231,0.852704,0.577252,0.878888,0.594566,0.520499,0.68393

  → Сохранена лучшая модель (mean F1=0.6901)

Epoch 16/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0224]

Epoch 16 | train_loss=0.0505 | val_loss=0.5152 | val_f1_mean=0.6990 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.733997,0.67356,0.636364,0.672935,0.619137,0.605305,0.658797,0.759825,0.749283,0.566102,...,0.681199,0.574655,0.896602,0.395732,0.830918,0.57262,0.904431,0.593632,0.50187,0.611959

  → Сохранена лучшая модель (mean F1=0.6990)

Epoch 17/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0454]

Epoch 17 | train_loss=0.0444 | val_loss=0.5465 | val_f1_mean=0.6989 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.703956,0.715421,0.642762,0.632982,0.593573,0.653003,0.605946,0.714876,0.845797,0.585821,...,0.721022,0.572996,0.903447,0.45145,0.846154,0.587222,0.890066,0.56189,0.519859,0.672527

Epoch 18/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0219]

Epoch 18 | train_loss=0.0397 | val_loss=0.5915 | val_f1_mean=0.7062 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.745562,0.742475,0.641656,0.653784,0.56314,0.684431,0.629261,0.754098,0.828701,0.518072,...,0.747845,0.600994,0.895573,0.413574,0.860902,0.55375,0.899933,0.549685,0.521895,0.687596

  → Сохранена лучшая модель (mean F1=0.7062)

Epoch 19/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0159]

Epoch 19 | train_loss=0.0343 | val_loss=0.6655 | val_f1_mean=0.7220 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.761146,0.714055,0.648697,0.665991,0.595194,0.657133,0.675245,0.772834,0.822335,0.554007,...,0.739459,0.613508,0.902256,0.419936,0.877238,0.600295,0.881596,0.558396,0.522321,0.704293

  → Сохранена лучшая модель (mean F1=0.7220)

Epoch 20/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0103]

Epoch 20 | train_loss=0.0314 | val_loss=0.6978 | val_f1_mean=0.7236 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.753049,0.707006,0.665069,0.667368,0.588679,0.655391,0.679223,0.775056,0.798503,0.635983,...,0.724761,0.620336,0.892432,0.403226,0.890402,0.594828,0.899933,0.554985,0.521267,0.719611

  → Сохранена лучшая модель (mean F1=0.7236)

Epoch 21/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0044]

Epoch 21 | train_loss=0.0290 | val_loss=0.7204 | val_f1_mean=0.7234 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.712843,0.736111,0.632378,0.680912,0.61477,0.7194,0.647242,0.747788,0.868659,0.585455,...,0.760596,0.620133,0.90651,0.416,0.882431,0.601455,0.869031,0.597701,0.532251,0.673529

Epoch 22/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0295]

Epoch 22 | train_loss=0.0259 | val_loss=0.7053 | val_f1_mean=0.7228 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.623853,0.643258,0.668582,0.672286,0.602837,0.704747,0.638111,0.720648,0.857334,0.592734,...,0.743644,0.63057,0.91214,0.411701,0.877193,0.62342,0.899893,0.571885,0.535797,0.673396

Epoch 23/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0165]

Epoch 23 | train_loss=0.0228 | val_loss=0.8798 | val_f1_mean=0.7363 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.753532,0.713816,0.690625,0.684932,0.604128,0.731665,0.63707,0.788599,0.866941,0.591006,...,0.697765,0.64008,0.906021,0.431871,0.872449,0.594075,0.889265,0.61857,0.528801,0.727273

  → Сохранена лучшая модель (mean F1=0.7363)

Epoch 24/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0097]

Epoch 24 | train_loss=0.0214 | val_loss=0.8657 | val_f1_mean=0.7389 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.75,0.737828,0.665405,0.717586,0.616,0.708333,0.645485,0.77619,0.866988,0.614481,...,0.715578,0.636408,0.906811,0.445813,0.871795,0.571238,0.905429,0.601719,0.558676,0.716443

  → Сохранена лучшая модель (mean F1=0.7389)

Epoch 25/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0093]

Epoch 25 | train_loss=0.0197 | val_loss=0.9402 | val_f1_mean=0.7408 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.728838,0.726316,0.6605,0.714037,0.633065,0.716211,0.663546,0.75395,0.866207,0.643991,...,0.75162,0.651139,0.906988,0.456897,0.870988,0.591075,0.899134,0.630491,0.578742,0.717264

  → Сохранена лучшая модель (mean F1=0.7408)

Epoch 26/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0182]

Epoch 26 | train_loss=0.0185 | val_loss=0.9255 | val_f1_mean=0.7361 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.76748,0.754789,0.618273,0.696075,0.599206,0.702637,0.669643,0.762353,0.881308,0.585635,...,0.757642,0.640201,0.903273,0.422741,0.861748,0.599641,0.907506,0.588705,0.593541,0.710145

Epoch 27/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0020]

Epoch 27 | train_loss=0.0160 | val_loss=0.9347 | val_f1_mean=0.7409 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.752656,0.729875,0.694836,0.716201,0.582456,0.712634,0.667531,0.746067,0.883191,0.59387,...,0.733471,0.657909,0.90411,0.421717,0.888451,0.575589,0.910292,0.637887,0.576253,0.731317

  → Сохранена лучшая модель (mean F1=0.7409)

Epoch 28/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0010]

Epoch 28 | train_loss=0.0155 | val_loss=1.0613 | val_f1_mean=0.7462 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.772803,0.75,0.67243,0.692593,0.608163,0.737488,0.672909,0.78,0.875261,0.615694,...,0.742004,0.651386,0.909136,0.446309,0.880568,0.609952,0.895916,0.606242,0.582436,0.71875

  → Сохранена лучшая модель (mean F1=0.7462)

Epoch 29/100: 100%|██████████| 3929/3929 [18:25<00:00,  3.55it/s, loss=0.0021]

Epoch 29 | train_loss=0.0140 | val_loss=1.0284 | val_f1_mean=0.7436 |

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.741194,0.719424,0.675835,0.694351,0.641975,0.736888,0.68614,0.778325,0.872752,0.618337,...,0.73774,0.665914,0.906588,0.444772,0.888298,0.606061,0.903252,0.623507,0.576923,0.714516

,ARTS,ARTS & CULTURE,BLACK VOICES,BUSINESS,COLLEGE,COMEDY,CRIME,CULTURE & ARTS,DIVORCE,EDUCATION,...,TECH,THE WORLDPOST,TRAVEL,U.S. NEWS,WEDDINGS,WEIRD NEWS,WELLNESS,WOMEN,WORLD NEWS,WORLDPOST
f1,0.741194,0.719424,0.675835,0.694351,0.641975,0.736888,0.68614,0.778325,0.872752,0.618337,...,0.73774,0.665914,0.906588,0.444772,0.888298,0.606061,0.903252,0.623507,0.576923,0.714516

In [21]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR, num_labels=len(le.categories_[0]), local_files_only=True)
model.load_state_dict(torch.load('news_classifier_roberta-base_best.pt', weights_only=True))
model.to(DEVICE)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 10640.92it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: models/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=42, bias=True)
  )
)

In [22]:
model.eval()

pred_labels, mask_labels = [], []

with torch.no_grad():
    for batch in val_dl:
        log = model(batch['input_ids'].to(DEVICE), batch['attention_mask'].to(DEVICE)).logits
        pred_labels.append((torch.sigmoid(log) > 0.5).to('cpu').numpy())
        mask_labels.append(batch['labels'].numpy())
    
    pred_labels = np.vstack(pred_labels)
    mask_labels = np.vstack(mask_labels)
    
    print(classification_report(mask_labels, pred_labels, target_names=le.categories_[0]))

                precision    recall  f1-score   support

          ARTS       0.76      0.80      0.78       302
ARTS & CULTURE       0.79      0.74      0.76       268
  BLACK VOICES       0.68      0.74      0.71       917
      BUSINESS       0.66      0.78      0.72      1198
       COLLEGE       0.63      0.60      0.62       229
        COMEDY       0.74      0.75      0.74      1080
         CRIME       0.63      0.74      0.68       713
CULTURE & ARTS       0.87      0.75      0.81       214
       DIVORCE       0.86      0.91      0.89       685
     EDUCATION       0.63      0.68      0.66       202
 ENTERTAINMENT       0.84      0.88      0.86      3473
   ENVIRONMENT       0.65      0.76      0.70       288
         FIFTY       0.77      0.75      0.76       280
  FOOD & DRINK       0.89      0.93      0.91      1268
     GOOD NEWS       0.71      0.65      0.68       280
         GREEN       0.60      0.74      0.67       524
HEALTHY LIVING       0.75      0.83      0.79      1339
 HOME & LIVING       0.90      0.92      0.91       864
        IMPACT       0.56      0.61      0.58       697
 LATINO VOICES       0.74      0.75      0.74       226
         MEDIA       0.68      0.73      0.70       589
         MONEY       0.74      0.73      0.73       351
     PARENTING       0.86      0.90      0.88      1758
       PARENTS       0.76      0.84      0.80       791
      POLITICS       0.86      0.89      0.87      7120
  QUEER VOICES       0.86      0.88      0.87      1269
      RELIGION       0.72      0.75      0.73       516
       SCIENCE       0.71      0.74      0.72       441
        SPORTS       0.81      0.88      0.84      1016
         STYLE       0.82      0.87      0.84       451
STYLE & BEAUTY       0.94      0.94      0.94      1962
         TASTE       0.84      0.85      0.84       419
          TECH       0.78      0.76      0.77       420
 THE WORLDPOST       0.70      0.68      0.69       733
        TRAVEL       0.91      0.92      0.92      1980
     U.S. NEWS       0.48      0.47      0.48       275
      WEDDINGS       0.85      0.92      0.89       731
    WEIRD NEWS       0.59      0.63      0.61       556
      WELLNESS       0.90      0.93      0.91      3588
         WOMEN       0.65      0.63      0.64       714
    WORLD NEWS       0.56      0.67      0.61       660
     WORLDPOST       0.64      0.83      0.72       516

     micro avg       0.80      0.84      0.82     41903
     macro avg       0.75      0.78      0.76     41903
  weighted avg       0.80      0.84      0.82     41903
   samples avg       0.82      0.84      0.83     41903

d:\Python\Learning\NLP_Classification\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [24]:
test_ids, test_masks = batch_tokenization(tokenizer=tokenizer, texts=test_X.to_list())
test_labels = le.transform(test_y).toarray()

test_ds = TextDataset(test_ids, test_masks, test_labels)
test_dl = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True)

model.eval()

pred_labels, mask_labels = [], []

with torch.no_grad():
    for batch in test_dl:
        log = model(batch['input_ids'].to(DEVICE), batch['attention_mask'].to(DEVICE)).logits
        pred_labels.append((torch.sigmoid(log) > 0.5).to('cpu').numpy())
        mask_labels.append(batch['labels'].numpy())
    
    pred_labels = np.vstack(pred_labels)
    mask_labels = np.vstack(mask_labels)
    
    print(classification_report(mask_labels, pred_labels, target_names=le.categories_[0]))

Токенизация: 100%|██████████| 9/9 [00:06<00:00,  1.35it/s]

                precision    recall  f1-score   support

          ARTS       0.76      0.81      0.79       302
ARTS & CULTURE       0.79      0.73      0.76       268
  BLACK VOICES       0.69      0.72      0.71       916
      BUSINESS       0.63      0.80      0.70      1199
       COLLEGE       0.68      0.71      0.70       229
        COMEDY       0.75      0.76      0.76      1080
         CRIME       0.66      0.74      0.70       712
CULTURE & ARTS       0.84      0.77      0.81       215
       DIVORCE       0.86      0.90      0.88       685
     EDUCATION       0.64      0.69      0.66       203
 ENTERTAINMENT       0.84      0.88      0.86      3472
   ENVIRONMENT       0.66      0.81      0.73       289
         FIFTY       0.76      0.78      0.77       280
  FOOD & DRINK       0.90      0.93      0.92      1268
     GOOD NEWS       0.67      0.63      0.65       279
         GREEN       0.60      0.71      0.65       525
HEALTHY LIVING       0.74      0.79      0.77      1339
 HOME & LIVING       0.92      0.90      0.91       864
        IMPACT       0.55      0.61      0.58       697
 LATINO VOICES       0.78      0.78      0.78       226
         MEDIA       0.68      0.72      0.70       589
         MONEY       0.81      0.74      0.77       351
     PARENTING       0.86      0.91      0.89      1758
       PARENTS       0.78      0.84      0.81       791
      POLITICS       0.86      0.90      0.88      7120
  QUEER VOICES       0.84      0.88      0.86      1270
      RELIGION       0.74      0.76      0.75       515
       SCIENCE       0.73      0.75      0.74       441
        SPORTS       0.83      0.91      0.87      1015
         STYLE       0.82      0.86      0.84       451
STYLE & BEAUTY       0.94      0.94      0.94      1962
         TASTE       0.82      0.85      0.84       419
          TECH       0.72      0.72      0.72       420
 THE WORLDPOST       0.68      0.67      0.68       733
        TRAVEL       0.90      0.92      0.91      1980
     U.S. NEWS       0.48      0.45      0.47       276
      WEDDINGS       0.88      0.93      0.90       730
    WEIRD NEWS       0.64      0.65      0.64       555
      WELLNESS       0.90      0.93      0.91      3589
         WOMEN       0.63      0.61      0.62       714
    WORLD NEWS       0.59      0.71      0.64       660
     WORLDPOST       0.70      0.83      0.76       516

     micro avg       0.80      0.84      0.82     41903
     macro avg       0.75      0.78      0.77     41903
  weighted avg       0.80      0.84      0.82     41903
   samples avg       0.82      0.84      0.83     41903

d:\Python\Learning\NLP_Classification\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])